### ISSUE TITLE
Inconvenient Queue

### ISSUE THREAD

**Issue by LDelOff** [azlux/botamusique#103]
![image](https://user-images.githubusercontent.com/51275636/76703933-89e1a880-66e6-11ea-8606-05a0dd687b5f.png)
Now, when calling !queue, the answer is 3 messages. This is a lot of lines.
It might be better to make the queue a single message with a custom number of items to display.
For example:
!queue - shows the current and 2 next tracks.
!queue 10 - shows the current and 9 next tracks.

**Comment by azlux** [comment]
This shouldn't append. It's all in one message in the default config. 
Have you html messages enable into your murmur config ?

**Comment by TerryGeng** [comment]
Oh, I see. This is the same issue as #83. @LDelOff Your server returned 0 as maximum message length, which caused the problem. Try to set it back to 5000 will fix things up.

I can also post a hotfix tomorrow.

**Comment by LDelOff** [comment]
azlux
; Allow clients to use HTML in messages, user comments and channel descriptions?
allowhtml=true
