### ISSUE TITLE
Opening folders in WebInterface

### ISSUE THREAD

**Issue by LDelOff** [azlux/botamusique#104]
Is it difficult to make it possible to open a folder and add several songs, rather than the entire folder
![image](https://user-images.githubusercontent.com/51275636/76708036-ee136500-6704-11ea-927d-199a2d834289.png)

**Comment by LDelOff** [comment]
Из-за большого количества музыки тормозит, я не заметил, извините

**Comment by LDelOff** [comment]
folders that are named !*** not to disclose.

**Comment by TerryGeng** [comment]
I noticed this problem days ago. If there're too many folders, the browser will react slow (I use Chrome). Possible solution includes Ajax... But I'm thinking about integrating it into a universal music library browser. I will look into it in some days.

**Comment by TerryGeng** [comment]
And, if you just want to classify your music file and add a specific category into your playlist, I think you can try the tagging feature.
