### ISSUE TITLE
New release requests review

### ISSUE THREAD

**Issue by TerryGeng** [azlux/botamusique#105]
I just finished a major update. The web interface was greatly improved (I abused my poor javascript proficiency), now we have this beautiful music library browser and I'm proud of it!

This browser features flexible query options, it even supports tag-editing! Now you can also see music downloaded from youtube and radios, so no need to re-type URL every time.

I also add a lot of animations for both the library browser and the playlist, so they look much smoother now.

The database-query part has been largely refactored due to @Lartza 's compliant.

Now it's you guys' turn to abuse it and see what can go wrong ;).

**Comment by LDelOff** [comment]
Hi, there is a suggestion:
The !duckv command determines the absolute volume value.
This is inconvenient if the tracks have different volumes (then you must manually write !v and !duckv).
I think !duckv should determine the percentage of !v as a percentage.

**Comment by TerryGeng** [comment]
@LDelOff It's a bad thing that having tracks with different volumes. They should always be normalized through apps like Adobe Audition or ffmpeg. For my use case, I don't want 'duckv' to move with volume. I don't plan to implement this, but if you insist, please feel free to leave an issue so we can see other people's thoughts over this feature.

**Comment by azlux** [comment]
Release done after one week working well, and many fixes
https://github.com/azlux/botamusique/releases/tag/6.1

**Comment by azlux** [comment]
@LDelOff please open an issue for you suggestion. I think I've an idea how to manage that.
