### ISSUE TITLE
Reference channel by full path

### ISSUE THREAD

**Issue by HerHde** [azlux/botamusique#106]
**Is your feature request related to a problem? Please describe.**
The bot finds the target channel to join by name (`find_by_name()` in [pymumble's channels](https://github.com/azlux/pymumble/blob/pymumble_py3/pymumble_py3/channels.py)), which is can be ambiguous. If you have multiple (sub-)channels named `test` it will join the first one with no way to reference the second one, e.g. in the following channel structure:

- foo
  - test
- bar
  - test

**Describe the solution you'd like**

Please parse the `channel` config parameter by `find_by_tree()` if it contains a slash (`/`), so the Mumble path can be used, line `bar/test`.

**Describe alternatives you've considered**
None really.

**Additional context**
Nothing I can think of, but I'm open to questions.

**Comment by HerHde** [comment]
Okay, trining to implement this feature I must admit, that I don't have a clue how to use the `find_by_tree()` function.

At first I tried using

```
if '/' in channel:
    self.mumble.channels.find_by_tree(channel.split('/')).move_in()
```

But it just throws a `UnknownChannelError`. I tried to use the function with different parameters, including strings of different channel names at different positions in the tree and different lists.
Only a empty string did not threw the error, returning the root channel. Any hints how to use it?

**Comment by azlux** [comment]
Hi
The code is good. I've found the error, not yours.
I will fix an issue into pymumble

**Comment by HerHde** [comment]
Thank you for the fix! I prepared a fix already which reuses the logic, as there are two references throughout the code.
The code you copied over also breaks, as the `channel` attribute without the class is not defined.

I've tested MR #107 successfully with multiple depth setups and differently and equally named channels.

Cheers!
