### ISSUE TITLE
Crash on adding radio by URL

### ISSUE THREAD

**Issue by HerHde** [azlux/botamusique#109]
**Describe the bug**
Adding an URL which references a stream/radio results in a crash with the following stack trace:

```
[[...] INFO Thread-4] bot: received command url - <a href="http://jazz-wr04.ice.infomaniak.ch/jazz-wr04-128.mp3">http://jazz-wr04.ice.infomaniak.ch/jazz-wr04-128.mp3</a> by HerHde
[[...] INFO Thread-4] cmd: add to playlist: [url]  (http://jazz-wr04.ice.infomaniak.ch/jazz-wr04-128.mp3)
[[...] INFO Validating] url: fetching metadata of url http://jazz-wr04.ice.infomaniak.ch/jazz-wr04-128.mp3 
[generic] jazz-wr04-128: Requesting header
Exception in thread Validating:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "[...]/botamusique/media/playlist.py", line 227, in _check_valid
    if not item.validate() or item.is_failed():
  File "[...]/botamusique/media/cache.py", line 168, in validate
    ret = self.item().validate()
  File "[...]/botamusique/media/url.py", line 90, in validate
    info = self._get_info_from_url()
  File "[...]/botamusique/media/url.py", line 127, in _get_info_from_url
    self.duration = info['duration'] / 60
KeyError: 'duration'
```

**Affected version**
22e705a469c1f54bf34cd4ddf0da6a15aa68838b,
d0d1f538a4706f54e84e58068664f998d8c96273 (my PR)

**To Reproduce**
1. In Mumble, add a radio with `!url http://jazz-wr04.ice.infomaniak.ch/jazz-wr04-128.mp3`
1. It should fail as described

**Expected behavior**
As streams are not expected to have a duration, it should not crash on this missing key.

**Additional context**
As this happens in the [URLItem](url.py) it does not crash when starting a stream with the `!radio` command.

From a look at the source this module expects YouTube-Links, you might run into other problems with SoundCloud or other accepted content.

Please have a look at #108 before taking any measures, even if different modules are affected.

Thank you!

**Comment by TerryGeng** [comment]
The problem is we use youtube-dl to process !url requests.
youtube-dl can not download or parse radio stream, so here comes this problem.

But at least I can beautify the error, let the bot not crash. It's done in `21c8e27`.

@Lartza and @azlux and I have been thinking about automatically determine the type of links, whether it is a radio link, a raw file link or youtube link. But I don't think I'm going to work on it. You are welcome to open a PR for it.

> From a look at the source this module expects YouTube-Links, you might run into other problems with SoundCloud or other accepted content.

youtube-dl support SoundCloud links. In fact, it supports a large number of music websites. You can see this from its project homepage.
We didn't hard-code youtube links in our code, or at least in url.py. Although in url_from_playlist.py we did this to process youtube playlist. !url command should work with SoundCloud links.

**Comment by HerHde** [comment]
> The problem is we use youtube-dl to process !url requests.
> youtube-dl can not download or parse radio stream, so here comes this problem.

Indeed this is a problem with youtube-dl, [which is hard to prevent](https://github.com/ytdl-org/youtube-dl/blob/master/README.md#how-can-i-detect-whether-a-given-url-is-supported-by-youtube-dl).

> We didn't hard-code youtube links in our code, or at least in url.py. Although in url_from_playlist.py we did this to process youtube playlist. !url command should work with SoundCloud links.

Again, indeed. This was more about the general requirement of attributes and the measures against missing ones than any specific problem.

**Comment by HerHde** [comment]
Maybe it's worth a try to guess the type of links by it's HTTP headers and handle it as a stream if 
Content-Type is `audio/*` or `video/*`
AND the Content-Length is empty?

**Comment by TerryGeng** [comment]
@HerHde I think this idea is promising. Just query the URL and if it is audio then we handle it, otherwise we feed it to youtube-dl.
