### ISSUE TITLE
Repeat function and playback youtube playlists

### ISSUE THREAD

**Issue by thejustsoul** [azlux/botamusique#11]
**Is your feature request related to a problem? Please describe.**
No. 
- [x] 1. If possible add Repeat function for current track (url).
- [x] 2. If possible add ability to playback youtube playlists.

**Comment by azlux** [comment]
@thejustsoul Repeat need to add the current music at the begin or end of the playlist ?

**Comment by thejustsoul** [comment]
@azlux I do not even know, at your discretion :)

**Comment by azlux** [comment]
Reminder to myself : playlist -> https://github.com/rg3/youtube-dl/blob/d4a24f4091a622b808ff621e78b5cfd0db3c8c11/youtube_dl/YoutubeDL.py#L169
