### ISSUE TITLE
ffmpeg location in configuration.ini

### ISSUE THREAD

**Issue by FireElementalNE** [azlux/botamusique#110]
**Is your feature request related to a problem? Please describe.**
No. It is not a problem.

**Describe the solution you'd like**
Configurable ffmpeg location within the ini file. If I compile the latest and greatest ffmpeg, it would be nice not to have to edit source locations (i.e. where the ffmpeg command is invoked).

**Describe alternatives you've considered**
Directly edit the source code. Create links in the bin directory, both are a hassle

**Additional context**
Nope.

**Comment by TerryGeng** [comment]
Certainly this can be done, however, why not just create a soft link in your bin directory as you have suggested?

Since we use youtube-dl, which requires ffmpeg as well, it may take some effort to change the default ffmpeg location just in our code.

**Comment by FireElementalNE** [comment]
I see, that makes sense. It might still be nice as a use case for just playing local files (i.e. the file command). That is my usual use case.
