### ISSUE TITLE
ValueError: signal only works in main thread

### ISSUE THREAD

**Issue by bin** [azlux/botamusique#111]
**Describe the bug**
When running on arch linux with `/opt/botamusique/venv/bin/python /opt/botamusique/mumbleBot.py --config /opt/botamusique/configuration.ini`, python version 3.8, 3.7, or 3.6, I get the following error: ```
Exception in thread WebThread:                                                                                                                                                      Traceback (most recent call last):                                                                                                                                                    File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner                                                                                                                 self.run()                                                                                                                                                                        File "/usr/lib/python3.6/threading.py", line 864, in run                                                                                                                              self._target(*self._args, **self._kwargs)                                                                                                                                         File "/opt/botamusique/mumbleBot.py", line 586, in start_web_interface                                                                                                                interface.web.run(port=port, host=addr)                                                                                                                                           File "/opt/botamusique/venv/lib/python3.6/site-packages/flask/app.py", line 990, in run                                                                                               run_simple(host, port, self, **options)                                                                                                                                           File "/opt/botamusique/venv/lib/python3.6/site-packages/werkzeug/serving.py", line 1050, in run_simple                                                                                run_with_reloader(inner, extra_files, reloader_interval, reloader_type)                                                                                                           File "/opt/botamusique/venv/lib/python3.6/site-packages/werkzeug/_reloader.py", line 330, in run_with_reloader                                                                        signal.signal(signal.SIGTERM, lambda *args: sys.exit(0))                                                                                                                          File "/usr/lib/python3.6/signal.py", line 47, in signal                                                                                                                               handler = _signal.signal(_enum_to_int(signalnum), _enum_to_int(handler))                                                                                                        ValueError: signal only works in main thread```

**Affected version**
Tested on latest release and commit ID d24f1095a366019464b16d8e20951007025e33a6.

**To Reproduce**
Run the above command described on arch with python 3.6, 3.7, or 3.8.  

**Expected behavior**
The web interface starts.

Happy to provide any additional info as needed.

**Comment by TerryGeng** [comment]
This is actually a bug for Flask.

But also we need to be blamed for our unconventional use of Flask itself :( .

I have encountered this only once, that is when I tried to set to DEBUG flag. Then it works fine for my Macbook and my Arch server. So I don't know what happened on your server.

Now I disabled other unnecessary flags. Maybe it will solve your problem.

**Comment by bin** [comment]
Yeah my googling mentioned a flask bug as well.  Testing on the new commit yields the same error; testing with FLASK_ENV=production gives the same: ```
 * Serving Flask app "interface" (lazy loading)                                                                                                                                      * Environment: production                                                                                                                                                             WARNING: This is a development server. Do not use it in a production deployment.                                                                                                    Use a production WSGI server instead.                                                                                                                                             * Debug mode: on                                                                                                                                                                   Exception in thread WebThread:                                                                                                                                                      Traceback (most recent call last):                                                                                                                                                    File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner                                                                                                                 self.run()                                                                                                                                                                        File "/usr/lib/python3.6/threading.py", line 864, in run                                                                                                                              self._target(*self._args, **self._kwargs)                                                                                                                                         File "/opt/botamusique/mumbleBot.py", line 592, in start_web_interface                                                                                                                interface.web.run(port=port, host=addr)                                                                                                                                           File "/opt/botamusique/venv/lib/python3.6/site-packages/flask/app.py", line 990, in run                                                                                               run_simple(host, port, self, **options)                                                                                                                                           File "/opt/botamusique/venv/lib/python3.6/site-packages/werkzeug/serving.py", line 1050, in run_simple                                                                                run_with_reloader(inner, extra_files, reloader_interval, reloader_type)                                                                                                           File "/opt/botamusique/venv/lib/python3.6/site-packages/werkzeug/_reloader.py", line 330, in run_with_reloader                                                                        signal.signal(signal.SIGTERM, lambda *args: sys.exit(0))                                                                                                                          File "/usr/lib/python3.6/signal.py", line 47, in signal                                                                                                                               handler = _signal.signal(_enum_to_int(signalnum), _enum_to_int(handler))                                                                                                        ValueError: signal only works in main thread```

**Comment by bin** [comment]
I set it to debug mode because the web app wasn't responding, so while I don't get that message if I set it to production, I can't figure out why I can't load the web interface.

**Comment by TerryGeng** [comment]
According to https://www.semicolonworld.com/question/58571/start-a-flask-application-in-separate-thread ,
I think it's necessary that you don't start Flask in debug mode.

**Comment by TerryGeng** [comment]
If you didn't set any log file, the log will be printed out in stderr. It should looks like

```
[Mar 22 22:02:20 INFO MainThread] bot: botamusique version 6.0, starting...
[Mar 22 22:02:20 DEBUG MainThread] Starting in DEBUG loglevel
[Mar 22 22:02:20 INFO MainThread] Starting web interface on 127.0.0.1:8181
[Mar 22 22:02:20 DEBUG UpdateThread] update: checking for updates...
 * Serving Flask app "interface" (lazy loading)
 * Environment: development
 * Debug mode: off
 * Running on http://127.0.0.1:8181/ (Press CTRL+C to quit)
[Mar 22 22:02:20 DEBUG MainThread] bot: command added: joinme
[Mar 22 22:02:20 DEBUG MainThread] bot: command added: userban
.....
[Mar 22 22:02:20 INFO MainThread] library: rebuild directory cache
[Mar 22 22:02:20 INFO MainThread] bot: load playlist from previous session
[Mar 22 22:02:20 DEBUG Validating] playlist: start validating...
[Mar 22 22:02:20 DEBUG Validating] playlist: validating [file] Sting - Shape of My Heart (uploads/Shape of My Heart-Sting.mp3)
[Mar 22 22:02:20 DEBUG Validating] playlist: validating [file] 井草聖二 - Mellow Sunset (uploads/15.Mellow Sunset-井草聖二.mp3)
[Mar 22 22:02:20 DEBUG Validating] playlist: validating [file] 麗美 - Secret Feelings ～from childhood (uploads/05.Secret Feelings ～from childhood-麗美.mp3)
.....
[Mar 22 22:02:20 DEBUG MainThread] bot: execute ffmpeg command: ffmpeg -v warning -nostdin -i /Users/terrygeng/Desktop/source/python/botamusique/music_folder/uploads/05.Secret Feelings ～from childhood-麗美.mp3 -ac 1 -f s16le -ar 48000 -
[Mar 22 22:02:20 DEBUG MainThread] bot: Async download next asked
[Mar 22 22:02:22 DEBUG UpdateThread] update: no new version found.
127.0.0.1 - - [22/Mar/2020 22:02:27] "GET / HTTP/1.1" 200 -
[Mar 22 22:02:27 DEBUG Thread-3] web: Post request from 127.0.0.1: ImmutableMultiDict([('type', ''), ('dir', ''), ('tags', ''), ('keywords', ''), ('page', '1'), ('action', 'query')])
127.0.0.1 - - [22/Mar/2020 22:02:27] "POST /library HTTP/1.1" 404 -
127.0.0.1 - - [22/Mar/2020 22:02:27] "GET /playlist HTTP/1.1" 200 -
127.0.0.1 - - [22/Mar/2020 22:02:30] "POST /post HTTP/1.1" 200 -
127.0.0.1 - - [22/Mar/2020 22:02:30] "GET /playlist HTTP/1.1" 200 -
[Mar 22 22:02:32 DEBUG Thread-7] web: Post request from 127.0.0.1: ImmutableMultiDict([('type', 'file'), ('dir', ''), ('tags', ''), ('keywords', ''), ('page', '1'), ('action', 'query')])
```

Lines like
```
127.0.0.1 - - [22/Mar/2020 22:02:27] "GET / HTTP/1.1" 200 -
```
indicates your requests has been successfully processed.

**Comment by bin** [comment]
I'm not getting that logging.  Any idea why that might be?

**Comment by TerryGeng** [comment]
Ehhhh.... How many files do you have?

**Comment by bin** [comment]
4722

**Comment by TerryGeng** [comment]
Okay, I guess you need to give the bot some time to index all files. I use the bot with approximately 500 files and it works fine.

The speed of indexing also depends on how fast your server is. If you want to see the progress of indexing, you can add this line

```
print(file)
```

after line 111 of `media/cache.py`.

**Comment by bin** [comment]
Thanks.  I figure it may be pretty slow; it's a bit of a potato and running over a network.

**Comment by TerryGeng** [comment]
You may want to avoid rebuilding the file index every time you start the bot by setting
```
[bot]
refresh_cache_on_startup = True
```

But every time you upload files through the web interface, it will refresh the cache. And in some case you may also need to refresh the cache manually by command `!rescan`.

**Comment by bin** [comment]
Good to know.  Thanks for your help.
