### ISSUE TITLE
No Chat Output

### ISSUE THREAD

**Issue by DeastinY** [azlux/botamusique#114]
AFAIK there is no easy way to mute chat sounds for all ppl on a mumble server, so would it be possible to run the bot with terminal output only?

**Comment by TerryGeng** [comment]
We have tried our best to let the bot send private messages only to the person who initiates the command. There are only limited scenarios where the bot will send messages to the entire channel:
1. "Now playing" message when switching from one song to the other. This can be disabled in the configuration file.
2. When people add songs to the playlist.
2. Errors when music files from URLs can not be downloaded or download is in progress.
3. A prompt message if auto-pause is set.

I think these messages are necessary to be shared across the entire channel. What's your opinion? Do you still believe these messages are too much?

**Comment by TerryGeng** [comment]
If you mean changing the sound for the text message or mute it, please see https://github.com/mumble-voip/mumble/issues/4014.

**Comment by azlux** [comment]
The best way to do it, You can create a user group on mumble server and don't all messages for them.

That the easier way to do it for you.

**Comment by DeastinY** [comment]
Thanks a bunch!
