### ISSUE TITLE
botamusique crashes sometimes when last user leaves the channel

### ISSUE THREAD

**Issue by fefrei** [azlux/botamusique#118]
**Describe the bug**

I've had botamusique crash twice when the last user left the channel. The logs look like this:

```
Apr 01 19:11:52 liebe python[83096]: [Apr 01 19:11:52 INFO Thread-1] bot: Other users in the channel left. Stopping music now.
Apr 01 19:11:52 liebe python[83096]: Exception in thread Thread-1:
Apr 01 19:11:52 liebe python[83096]: Traceback (most recent call last):
Apr 01 19:11:52 liebe python[83096]:   File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
Apr 01 19:11:52 liebe python[83096]:     self.run()
Apr 01 19:11:52 liebe python[83096]:   File "/home/fefrei/botamusique/pymumble/pymumble_py3/mumble.py", line 120, in run
Apr 01 19:11:52 liebe python[83096]:     self.loop()
Apr 01 19:11:52 liebe python[83096]:   File "/home/fefrei/botamusique/pymumble/pymumble_py3/mumble.py", line 197, in loop
Apr 01 19:11:52 liebe python[83096]:     self.read_control_messages()
Apr 01 19:11:52 liebe python[83096]:   File "/home/fefrei/botamusique/pymumble/pymumble_py3/mumble.py", line 271, in read_control_messages
Apr 01 19:11:52 liebe python[83096]:     self.dispatch_control_message(type, message)
Apr 01 19:11:52 liebe python[83096]:   File "/home/fefrei/botamusique/pymumble/pymumble_py3/mumble.py", line 342, in dispatch_control_message
Apr 01 19:11:52 liebe python[83096]:     self.users.update(mess)
Apr 01 19:11:52 liebe python[83096]:   File "/home/fefrei/botamusique/pymumble/pymumble_py3/users.py", line 31, in update
Apr 01 19:11:52 liebe python[83096]:     self.callbacks(PYMUMBLE_CLBK_USERUPDATED, self[message.session], actions)
Apr 01 19:11:52 liebe python[83096]:   File "/home/fefrei/botamusique/pymumble/pymumble_py3/callbacks.py", line 87, in __call__
Apr 01 19:11:52 liebe python[83096]:     self.call_callback(callback, *pos_parameters)
Apr 01 19:11:52 liebe python[83096]:   File "/home/fefrei/botamusique/pymumble/pymumble_py3/callbacks.py", line 83, in call_callback
Apr 01 19:11:52 liebe python[83096]:     func(*pos_parameters)
Apr 01 19:11:52 liebe python[83096]:   File "mumbleBot.py", line 347, in users_changed
Apr 01 19:11:52 liebe python[83096]:     self.pause()
Apr 01 19:11:52 liebe python[83096]:   File "mumbleBot.py", line 562, in pause
Apr 01 19:11:52 liebe python[83096]:     self.pause_at_id = var.playlist.current_item().id
Apr 01 19:11:52 liebe python[83096]: AttributeError: 'bool' object has no attribute 'id'
```

After that, the process keeps running, but the bot disconnects.

**Affected version**

Not sure how to find out (I installed using the instructions, not using Git), but it's recent – I only installed yesterday.

**To Reproduce**

Have the bot set to automatically pause and unpause when alone, and repeatedly join and leave the room.

**Comment by TerryGeng** [comment]
Hi, I need to know more about your case. How many songs are in the playlist when this bug occurs? Was the bot playing something at that time?

**Comment by fefrei** [comment]
Unfortunately, I wasn't around when it happened – but based on the logs, most likely, the playlist had a single entry, and it was in auto-play mode.
(I've set auto play to keep 1 item so there always is something playing, but when a user requests a song, it plays next.)

**Comment by TerryGeng** [comment]
Thanks for your reply. Based on what's shown on the log, I can hardly tell which part is wrong. This error should not happen, and we did make some safeguards to prevent this AttributeError from occurring. 

But you know... Things can go against our will.

Did this happen frequently? Or it just appeared once?

**Comment by fefrei** [comment]
I saw it twice, I always saw it happen within a few hours of leaving the bot alone.
I've now set the bot to stop when the last user leaves instead of pause-play, and haven't seen it happen since then.

**Comment by TerryGeng** [comment]
I manage to have reproduced this error. I think we are going to make a new release for this fix soon so hang tight :)

**Comment by fefrei** [comment]
Wonderful – thanks for your work 🚀

**Comment by fefrei** [comment]
Sorry to bother you again: Is there anything holding back a release of this? I'm wondering whether I should switch to the Git version.

**Comment by azlux** [comment]
Nothing, I will make the release this evening.
Srry, I miss to do it.

**Comment by fefrei** [comment]
Thank you for your work 🚀
