### ISSUE TITLE
Cannot hear bot voice

### ISSUE THREAD

**Issue by asterismo** [azlux/botamusique#120]
I connoct the bot and add some stuff no playlist but bot does not talk in channel

**Comment by azlux** [comment]
Do you have any errors on verbose mode (-v option ) ?

What's your python version and the OS version ?

**Comment by asterismo** [comment]
This happens when i try to add this YT playlist: https://www.youtube.com/watch?v=T-Kgw-GJalY&list=RDQMe7OmlzhE6ts&start_radio=1

[youtube] kXOhSSOyUE4: Downloading webpage
[youtube] Downloading just video kXOhSSOyUE4 because of --no-playlist
[youtube] WEBCj7vRuhY: Downloading webpage
[youtube] Downloading just video WEBCj7vRuhY because of --no-playlist
[youtube] q_KhDcP8q1I: Downloading webpage
[youtube] Downloading just video q_KhDcP8q1I because of --no-playlist
[youtube] 7keC17PvzW0: Downloading webpage
[youtube] Downloading just video 7keC17PvzW0 because of --no-playlist
[youtube] MSshf3bJg_Y: Downloading webpage
[youtube] Downloading just video MSshf3bJg_Y because of --no-playlist
[youtube] JWfYysE_VJM: Downloading webpage
[youtube] Downloading just video JWfYysE_VJM because of --no-playlist
[youtube] uzKJXBz8yIE: Downloading webpage
[youtube] Downloading just video uzKJXBz8yIE because of --no-playlist
[youtube] NvlGjCMp8cY: Downloading webpage
[youtube] Downloading just video NvlGjCMp8cY because of --no-playlist
[youtube] NvB0sFK1sjY: Downloading webpage
[youtube] Downloading just video NvB0sFK1sjY because of --no-playlist
[youtube] bUGs6EZ_kXU: Downloading webpage
[youtube] Downloading just video bUGs6EZ_kXU because of --no-playlist
[youtube] aGbfg75iES0: Downloading webpage
[youtube] Downloading just video aGbfg75iES0 because of --no-playlist
Exception in thread Validating:
Traceback (most recent call last):
  File "/usr/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "/root/botamusique/media/playlist.py", line 225, in _check_valid
    self.log.debug("playlist: validating %s" % item.format_debug_string())
  File "/root/botamusique/media/cache.py", line 189, in format_debug_string
    return self.item().format_debug_string()
  File "/root/botamusique/media/cache.py", line 131, in item
    return self.lib[self.id]
KeyError: 'ec3c15d9b06f6279d41d379409faf492'

**Comment by asterismo** [comment]
Python 3.7.3 and Debian 10 Buster

**Comment by asterismo** [comment]
After adding that playlist, i command it !play and it starts to play a random song (it announces the song in the chat) but the bot is not talking. Maybe mumble server setting? i have set mumble to a max bitrate of 48kbps audio

**Comment by azlux** [comment]
Are simple !url or radio working ?

**Comment by asterismo** [comment]
In chat:

[11:47:08] A RadioBot: !url https://www.youtube.com/watch?v=Nr-kvNnSU94
[11:47:08] (Private) RadioBot: Added https://www.youtube.com/watch?v=Nr-kvNnSU94.

in log:
[youtube] Nr-kvNnSU94: Downloading webpage
[youtube] Downloading just video Nr-kvNnSU94 because of --no-playlist

**Comment by asterismo** [comment]
!url does not play any sound, or the bot is unable to talk to channel

**Comment by asterismo** [comment]
I did !url with the playlist url and it started download something
[youtube:playlist] Downloading just video T-Kgw-GJalY because of --no-playlist
[youtube] T-Kgw-GJalY: Downloading webpage
[youtube] Downloading just video T-Kgw-GJalY because of --no-playlist
[youtube:playlist] Downloading just video T-Kgw-GJalY because of --no-playlist
[youtube] T-Kgw-GJalY: Downloading webpage
[youtube] Downloading just video T-Kgw-GJalY because of --no-playlist
[youtube] T-Kgw-GJalY: Downloading thumbnail ...
[youtube] T-Kgw-GJalY: Writing thumbnail to: /tmp/f7b56999e397bb504da5cf82a3d607b3.jpg
[download] Destination: /tmp/f7b56999e397bb504da5cf82a3d607b3.m4a
[download] 100% of 5.27MiB in 00:00
[ffmpeg] Correcting container in "/tmp/f7b56999e397bb504da5cf82a3d607b3.m4a"
[ffmpeg] Destination: /tmp/f7b56999e397bb504da5cf82a3d607b3.mp3
Deleting original file /tmp/f7b56999e397bb504da5cf82a3d607b3.m4a (pass -k to keep)
[ffmpeg] Adding metadata to '/tmp/f7b56999e397bb504da5cf82a3d607b3.mp3'

and i can see the song thumbnail, but no audio, the bot is not talking.

![radiobot](https://user-images.githubusercontent.com/5679035/78374892-6c478680-75a2-11ea-97aa-14e7a8bd638b.png)

**Comment by asterismo** [comment]
!radio is not working either


[12:04:39] (Private) RadioBot: Preconfigurated Radio available:ponyville - "Here a command of !radio comment"luna - "calm and orchestra music"radiobrony - "Borny music of a friend"celestiaradiojazz - "Jazz Yeah !"
--

**Comment by asterismo** [comment]
After a few minutes it crashed

Traceback (most recent call last):
  File "mumbleBot.py", line 712, in <module>
    var.cache.build_dir_cache(var.bot)
  File "/root/botamusique/media/cache.py", line 114, in build_dir_cache
    item = item_builders['file'](bot, path=file)
  File "/root/botamusique/media/file.py", line 26, in file_item_builder
    return FileItem(bot, kwargs['path'])
  File "/root/botamusique/media/file.py", line 52, in __init__
    self._get_info_from_tag()
  File "/root/botamusique/media/file.py", line 87, in _get_info_from_tag
    assert match is not None
AssertionError

**Comment by TerryGeng** [comment]
Hi. Can you show us the entire log? If you are playing a youtube playlist, at least in the log there would be things like 
```
cmd: fetching media info from playlist url xxxx
```
and
```
cmd: add to playlist: xxxxxxx
```

I could not see these things from what you have posted.

**Comment by TerryGeng** [comment]
I'd also suggest you play a local file first. You said you could not hear the bot from the channel. I need to confirm that is caused simply by the way we handle youtube or the way we play the music.

**Comment by asterismo** [comment]
...
https://www.youtube.com/watch?v=Nr-kvNnSU94</span></a> by SantiagoCF31
[Apr 03 11:47:08 DEBUG Validating] playlist: start validating...
[Apr 03 11:47:08 INFO Thread-2] cmd: add to playlist: [url]  (https://www.youtube.com/watch?v=Nr-kvNnSU94)
[Apr 03 11:47:08 DEBUG Validating] playlist: validating [url]  (https://www.youtube.com/watch?v=Nr-kvNnSU94)
[Apr 03 11:47:08 INFO Validating] url: fetching metadata of url https://www.youtube.com/watch?v=Nr-kvNnSU94 
[Apr 03 11:47:10 DEBUG Validating] library: music save into database: [url] Durazno y Convención (Jaime Roos) Videoclip original con buen audio (https://www.youtube.com/watch?v=Nr-kvNnSU94)
[Apr 03 11:47:11 DEBUG Validating] playlist: validating finished.
[Apr 03 11:54:54 INFO Thread-3] bot: received command url - <a href="https://www.youtube.com/watch?v=T-Kgw-GJalY&amp;list=RDQMe7OmlzhE6ts&amp;start_radio=1"><span style="color:#0b8eb2">https://www.youtube.com/watch?v=T-Kgw-GJalY&amp;list=RDQMe7OmlzhE6ts&amp;start_radio=1</span></a> by SantiagoCF31
[Apr 03 11:54:54 DEBUG Validating] playlist: start validating...
[Apr 03 11:54:54 INFO Thread-3] cmd: add to playlist: [url]  (https://www.youtube.com/watch?v=T-Kgw-GJalY&amp;list=RDQMe7OmlzhE6ts&amp;start_radio=1)
[Apr 03 11:54:54 DEBUG Validating] playlist: validating [url]  (https://www.youtube.com/watch?v=T-Kgw-GJalY&amp;list=RDQMe7OmlzhE6ts&amp;start_radio=1)
[Apr 03 11:54:54 INFO Validating] url: fetching metadata of url https://www.youtube.com/watch?v=T-Kgw-GJalY&amp;list=RDQMe7OmlzhE6ts&amp;start_radio=1 
[Apr 03 11:54:54 DEBUG Thread-3] bot: Async download next asked 
[Apr 03 11:54:55 DEBUG Validating] library: music save into database: [url] JAIME, CANARIO y LA FALTA (Uruguay) brindis por Pierrot (https://www.youtube.com/watch?v=T-Kgw-GJalY&amp;list=RDQMe7OmlzhE6ts&amp;start_radio=1)
[Apr 03 11:54:55 INFO Thread-3] url: start preparing item in thread: [url] JAIME, CANARIO y LA FALTA (Uruguay) brindis por Pierrot (https://www.youtube.com/watch?v=T-Kgw-GJalY&amp;list=RDQMe7OmlzhE6ts&amp;start_radio=1)
[Apr 03 11:54:55 DEBUG Validating] playlist: validating finished.
[Apr 03 11:54:56 INFO Prepare-f7b5699] bot: downloading url (JAIME, CANARIO y LA FALTA (Uruguay) brindis por Pierrot) https://www.youtube.com/watch?v=T-Kgw-GJalY&amp;list=RDQMe7OmlzhE6ts&amp;start_radio=1 
[Apr 03 11:54:59 INFO Prepare-f7b5699] bot: download attempts 1 / 2
[Apr 03 11:55:28 INFO Prepare-f7b5699] bot: finished downloading url (JAIME, CANARIO y LA FALTA (Uruguay) brindis por Pierrot) https://www.youtube.com/watch?v=T-Kgw-GJalY&amp;list=RDQMe7OmlzhE6ts&amp;start_radio=1, saved to /tmp/f7b56999e397bb504da5cf82a3d607b3.mp3.
[Apr 03 11:55:29 DEBUG Prepare-f7b5699] library: music save into database: [url] JAIME, CANARIO y LA FALTA (Uruguay) brindis por Pierrot (https://www.youtube.com/watch?v=T-Kgw-GJalY&amp;list=RDQMe7OmlzhE6ts&amp;start_radio=1)
[Apr 03 11:56:50 INFO Thread-4] bot: received command play -  by SantiagoCF31
[Apr 03 11:59:04 INFO Thread-5] bot: received command play
<p - style="-qt-paragraph-type:empty"><br/></p> by SantiagoCF31
[Apr 03 11:59:33 INFO Thread-6] bot: received command play -  by SantiagoCF31
[Apr 03 11:59:58 INFO Thread-7] bot: received command play -  by SantiagoMovil
[Apr 03 12:04:39 INFO Thread-8] bot: received command radio -  by SantiagoCF31
[Apr 03 12:05:21 INFO Thread-9] bot: received command radio - jazz by SantiagoCF31
[Apr 03 12:05:21 DEBUG Thread-9] radio: fetching radio server description
[Apr 03 12:05:35 DEBUG Validating] playlist: start validating...
[Apr 03 12:05:35 INFO Thread-9] cmd: add to playlist: [radio] http://jazz-wr04.ice.infomaniak.ch/jazz-wr04-128.mp3 (http://jazz-wr04.ice.infomaniak.ch/jazz-wr04-128.mp3)
[Apr 03 12:05:35 DEBUG Validating] playlist: validating [radio] http://jazz-wr04.ice.infomaniak.ch/jazz-wr04-128.mp3 (http://jazz-wr04.ice.infomaniak.ch/jazz-wr04-128.mp3)
[Apr 03 12:05:35 DEBUG Thread-9] radio: fetching radio server description
[Apr 03 12:05:35 DEBUG Validating] library: music save into database: [radio] http://jazz-wr04.ice.infomaniak.ch/jazz-wr04-128.mp3 (http://jazz-wr04.ice.infomaniak.ch/jazz-wr04-128.mp3)
[Apr 03 12:05:35 DEBUG Validating] playlist: validating finished.

**Comment by asterismo** [comment]
How do i play/add/scan for local files?

**Comment by asterismo** [comment]
I had a missing dependency! closing

**Comment by azlux** [comment]
@asterismo what was the dependency ?
We should add check in this case.

**Comment by asterismo** [comment]
i think it was a protobuf library that i ended up installing with pip
