### ISSUE TITLE
Cannot start bots 

### ISSUE THREAD

**Issue by HotoCocoaco** [azlux/botamusique#121]
Traceback (most recent call last):
  File "mumbleBot.py", line 16, in <module>
    import variables as var
  File "/root/botamusique/variables.py", line 9
    bot: 'mumbleBot.MumbleBot' = None
       ^
SyntaxError: invalid syntax

Running in Python 3.5.2, Ubuntu 16.04.
The installion was fine and I get all the dependences. When running `venv/bin/python mumbleBot.py --config configuration.ini` it happens to be a syntax error.

**Comment by azlux** [comment]
It's because some variable are strict type. https://www.python.org/dev/peps/pep-0484/#type-definition-syntax
It's a Python 3.6 feature. Can you upgrade you python version ?

**Comment by HotoCocoaco** [comment]
Working great with python3.6. Thanks.

**Comment by sake** [comment]
I was just hit by this at an upgrade and it would be nice to find a python version requirement (>= 3.6) in the readme file.
