### ISSUE TITLE
Local music playlist

### ISSUE THREAD

**Issue by asterismo** [azlux/botamusique#124]
Is there a possibility to play fixed playlist from local files? maybe a file list txt or make the bot random play music among certain music folders inside the collection and have it play permanently (whenever a user is in the channel)? and some !next commant to forward to next song?

Thanks

**Comment by asterismo** [comment]
or save a playlist of local music for later play?

**Comment by TerryGeng** [comment]
You can save a playlist by adding a tag to that playlist,
```
!addtag * some_tag
```
and next time you can recall the playlist by
```
!tag some_tag
```

Then, you can randomly play these files by 
```
!mode random
```

You can use
```
!skip
```

To forward to the next song.

Hope these could solve your problem. And I suggest you check out `!help` to see a list of commands that are supported by the bot or see the wiki page https://github.com/azlux/botamusique/wiki/Command-Help.

**Comment by TerryGeng** [comment]
I updated the wiki page https://github.com/azlux/botamusique/wiki/Command-Help-and-Examples and you can find some examples there.

**Comment by asterismo** [comment]
> You can save a playlist by adding a tag to all songs on that playlist,
> 
> ```
> !addtag * some_tag
> ```
> 
> and next time you can recall the playlist by
> 
> ```
> !tag some_tag
> ```
> 
> Then, you can randomly play these files by
> 
> ```
> !mode random
> ```
> 
> You can use
> 
> ```
> !skip
> ```
> 
> To forward to the next song.
> 
> Hope these could solve your problem. And I suggest you check out `!help` to see a list of commands that are supported by the bot or see the wiki page https://github.com/azlux/botamusique/wiki/Command-Help.

when you write "some_tag" that is the name you give to the playlist?

**Comment by TerryGeng** [comment]
Yes.

 I think you can have a look on wiki page https://github.com/azlux/botamusique/wiki/Command-Help-and-Examples and you can find some more examples there.
