### ISSUE TITLE
Are you planning to implement ssl for the web interface?

### ISSUE THREAD

**Issue by LDelOff** [azlux/botamusique#126]
I recently set up a site with a certificate from Let's Encrypt.
As a result, they stopped working when accessing the qBittorrent and botamusique domains.
qBittorrent I configured, it works.
But I don't know how to put the necessary certificate in botamusique.
As far as I understand, the "certificate" setting is required for connecting to murmur, not for the web interface.

**Comment by TerryGeng** [comment]
What server are you using? Apache or Nginx? The best way to set up SSL is using reverse proxy. Just searching about "reverse proxy ssl" and you will discover a lot of solutions.

**Comment by TerryGeng** [comment]
I hope your problem have been solved now. I read the manual of thelounge recently and find this link could be useful for you: https://thelounge.chat/docs/guides/reverse-proxies
I think just tweak a little bit then it can work for our bot.
Hope this help, and do you think I can close this issue?
