### ISSUE TITLE
Not working after update. ModuleNotFoundError: No module named 'pymumble_py3'

### ISSUE THREAD

**Issue by LDelOff** [azlux/botamusique#131]
Today I updated the bot with the command !update.
The daemon did not restart after the update. I tried to enable the bot manually. Here is the result:
![image](https://user-images.githubusercontent.com/51275636/79957096-c349c880-8489-11ea-8457-93999e021a4e.png)

Server Orange PI 3, 
python3 -V = Python 3.6.9

**Comment by LDelOff** [comment]
my bad
I had to run it with the command
venv/bin/python mumbleBot.py

**Comment by azlux** [comment]
You can read that : https://github.com/azlux/botamusique/wiki/Run-botamusique-as-a-daemon-In-the-background
