### ISSUE TITLE
Save playlist feature

### ISSUE THREAD

**Issue by TerryGeng** [azlux/botamusique#140]
I have heard several times that on #mumble some people are asking for a "save/load playlist" feature. The perfunctory solution I always provide is using the "tagging" feature instead, but surely it can not keep the order of songs intact.

The feature itself is not hard to implement, but related UI design can be a headache. That's why I start this issue, just trying to know people's demands about the "save playlist" feature.

And, just to reiterate my "tagging" solution, I think people may try

1. Tagging all music file they want to add to a "playlist" with a tag "playlist-1" or something. Tagging can be done by command "!addtag" and in the web interface, as explained in the [wiki](https://github.com/azlux/botamusique/wiki).

2. When recalling a playlist, just switch the play mode to "repeat", clear the playlist, and add all songs with "!tag" or in the filter section of the web interface, the "Add All" button.

This works for me. But I'm also aware that this is "tricky", and people new to botamusique may not come up with at the first glance.

Anyway, if this issue becomes popular, I think I can get this feature and related commands done in the next release, but there might be a significant delay before the web interface is ready.

**Comment by captaingig** [comment]
I can certainly see a use case for this feature with regards to audiobooks and show tunes.

**Comment by TylerVigario** [comment]
Here is a quick ER diagram for multiple playlist support within database tables

![botamusique (1)](https://user-images.githubusercontent.com/1435595/101301167-cc0ac700-37ec-11eb-98ad-3392dc86d446.png)
