### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'comment'

### ISSUE THREAD

**Issue by BafDyce** [azlux/botamusique#141]
**Describe the bug**
When I start the bot (with my custom config) I get the following error:

```
[May 09 11:34:52 INFO MainThread] bot: botamusique version 6.2, starting...
[May 09 11:34:52 INFO MainThread] Starting web interface on 0.0.0.0:8181
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/threading.py", line 932, in _bootstrap_inner
Traceback (most recent call last):
  File "mumbleBot.py", line 745, in <module>
    self.run()
  File "/botamusique/pymumble/pymumble_py3/mumble.py", line 116, in run
    raise ConnectionRejectedError ("Connection error with the Mumble (murmur) Server")
pymumble.pymumble_py3.errors.ConnectionRejectedError: 'Connection error with the Mumble (murmur) Server'
    var.bot = MumbleBot(args)
  File "mumbleBot.py", line 133, in __init__
    self.set_comment()
  File "mumbleBot.py", line 204, in set_comment
    self.mumble.users.myself.comment(var.config.get('bot', 'comment'))
AttributeError: 'NoneType' object has no attribute 'comment'
```

**Affected version**
Latest stable version (downloaded just today from https://packages.azlux.fr/botamusique/sources.tar.gz). I followed the install instructions from the readme.

**To Reproduce**
I just ran botamusique via `python mumbleBot.py --config configuration.ini`

My configuration doesnt have a `comment` specified. However, on the server, I also cannot even see a user connecting. I specified an existing certificate in the config file.  This is running within a docker container with the following Dockerfile:

```
FROM python:3

# install deps
RUN apt-get update && apt-get install -y \
    libopus0 \
    ffmpeg \
    && rm -rf /var/lib/apt/lists/*

# create user
RUN useradd --user-group --no-create-home --uid 4242 botamusique

# install botamusique
RUN curl -Lo botamusique.tar.gz https://packages.azlux.fr/botamusique/sources.tar.gz \
    && tar -xzf botamusique.tar.gz \
    && rm botamusique.tar.gz \
    && cd botamusique \
    && pip3 install wheel \
    && pip3 install -r pymumble/requirements.txt \
    && pip3 install -r requirements.txt

# setup runtime params
USER botamusique
WORKDIR /botamusique
CMD ["python", "mumbleBot.py", "--config", "/configuration.ini"]
```

**Expected behavior**
The bot should be able to connect to the server and be able to change the comment (or disregard the exception if its not possible?)

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: Docker container (based on the python3 image)
 - Browser not applicable
 - Version not applicable

**Additional context**
N/A

**Comment by TerryGeng** [comment]
From the error message you have post, one line reads
```
pymumble.pymumble_py3.errors.ConnectionRejectedError: 'Connection error with the Mumble (murmur) Server'
```

Please check your network connection. Can you connect to you murmur server via a mumble client?

**Comment by azlux** [comment]
Hi, this issue appear when the bot isn't able to connect the mumble server. the first step the bot do it to set it own comment, and fail because it has not answer from the server.

**Comment by BafDyce** [comment]
Hi. Thanks for your fast reply. I already tested that. I can connect to the mumble server from the same host. I can also access it via curl/netcat from within the container, so I'm not sure why botamusique cannot connect to it :/

Is there a way to enable debugging output to see if it actually connects to the server i have configured?

**Comment by TerryGeng** [comment]
I'm afraid not... But one thing you can do is to check the log of your murmur server to see if there is any incoming connection. And, can you please reconfirm the host address and port are set correctly in your configuration.ini file?

**Comment by TerryGeng** [comment]
Hi, how is things going? Did you get your bot running? Shall I close this issue?

**Comment by BafDyce** [comment]
Due to time constraints I couldnt get it running yet. But you can close the issue as it looks like my container cannot reach the mumble server. Will investigate this further once I've got the time for it.

**Comment by HarpyWar** [comment]
Bot can not connect to this host:
mumble-ru.cleanvoice.ru 64738

How to solve the problem?
