### ISSUE TITLE
Copyrighted youtube songs don't work

### ISSUE THREAD

**Issue by hyperak** [azlux/botamusique#143]
**Describe the bug**
When playing certain youtube songs (only songs from pseudo-videos like [this](https://www.youtube.com/watch?v=NKVLl4c35j4) and [this](https://www.youtube.com/watch?v=YVgWQyGOTvk) have failed to download), I get errors that are almost the same as the following:

```
May 10 18:29:52 dieg python[18033]: UnicodeEncodeError: 'ascii' codec can't encode character '\xb7' in position 77: ordinal not in range(128)
```

**Affected version**
The exact version you're using (git commit id). You should **always** only report bugs which you can reproduce on the latest version (`uif` branch), however **always** state the current commit id here (in case there are new commits between your report and us looking at it)

`fbe3383b661d07ef03eabb83477fe7b2e4b445bf`

**To Reproduce**

Just play any copyrighted song from YouTube.

**Expected behavior**

Well, I expected to listen to music I already own... but on a Mumble server ~~by myself :(~~ with other people.

**Screenshots**

![image](https://user-images.githubusercontent.com/29081800/81507752-66de0a00-92cd-11ea-9186-448f638a065c.png)

**Desktop (please complete the following information):**
 - OS: Void Linux on kernel version 5.4.36_1.
 - Browser: why?
 - Version: Mumble 1.3.0

**Additional context**
Server is running Murmur 1.3.0 on CentOS 7, kernel 2.6.32.

**Comment by TerryGeng** [comment]
We dispatch all url requests to youtube-dl, so I guess this is the problem of youtube-dl.

Can you try `youtube-dl [YOUR URL]` to check whether youtube-dl works?

**Comment by azlux** [comment]
It's working on my side :
![image](https://user-images.githubusercontent.com/11210117/81556164-27c1be80-938a-11ea-9c6b-53bbc6d7f2c1.png)

Can you try to update the youtube-dl with the !update feature ?

**Comment by hyperak** [comment]
Aha, some basic googling after seeing the following error on downloading a file:

`WARNING: Assuming --restrict-filenames since file system encoding cannot encode all characters. Set the LC_ALL environment variable to fix this.`

was eliminated simply by running  `export LC_ALL="en_US.UTF-8"`, and adding `Environment="LC_ALL=en_US.UTF-8"` to the systemd service.

**Comment by TerryGeng** [comment]
Thanks for providing a solution!

I will add this to the Known Issue section of the README.
