### ISSUE TITLE
Directory drop-down from web interface

### ISSUE THREAD

**Issue by Elinvention** [azlux/botamusique#145]
**Describe the bug**
In version 6.2 I could select a directory to filter out my local library. When I updated to version 6.3 the directory selection is greyed out and can't select the directory I want. I tried to recreate the database, but I can't still filter by directory.

**Affected version**
6.3 d288bfa658467f3de617b8be13ae6b2b5f4ede22

**Expected behavior**
Be able to filter by directory.

**Screenshots**
![image](https://user-images.githubusercontent.com/5737945/81617435-badc1200-93e5-11ea-80ee-ae4738996059.png)

**Desktop (please complete the following information):**
 - Manjaro Linux
 - Firefox
 - 76.0

**Comment by TylerVigario** [comment]
I'll take a look at this

**Comment by Elinvention** [comment]
Thanks, it works now :100:
