### ISSUE TITLE
Embed metadata to files, use existing files before download

### ISSUE THREAD

**Issue by Lartza** [azlux/botamusique#15]
- [ ] Write metadata to files on download

- [ ] Check for an existing file and read it's metadata to obtain it's information

Old issue for reference:
**Is your feature request related to a problem? Please describe.**
Currently the bot can only cache the mp3 files it gets from youtube-dl to avoid redownloading them, but it doesn't really keep any track of them.

**Describe the solution you'd like**
Create an (optional?) database to hold record of every downloaded url.
Keep an unique id (urlhash?), the original URL, a file path and the title of the video or file in question.

**Describe alternatives you've considered**
Use youtube-dl's download_archive to keep a list of previously downloaded files, would still need to make server requests to fetch titles etc and editing the file wouldn't be nice. This wouldn't really be scalable in my opinion either.

**Additional context**
This feature allows some additional features, like playing random music from what has been previously played on the bot. I'm willing to implement this on myself but would like some feedback and suggestions in both functionality wise (what to store?) and implementation wise (sqlite only? use an ORM like peewee?)

**Comment by Lartza** [comment]
Oh and also implement a deletion command to remove entries and related files of a database cached song.

**Comment by azlux** [comment]
I prefer working with metadata tag than database.
The music can have title into their tag. It's better to manage.

**Comment by Lartza** [comment]
You mean write an id3 tag with the title to the mp3 file? I could probably work with that, since the files are already named after the url_hash, you could just check for existing files before running youtube-dl.

**Comment by azlux** [comment]
Indeed
