### ISSUE TITLE
Jump to time in track

### ISSUE THREAD

**Issue by jcharaoui** [azlux/botamusique#153]
This is a great piece of software, love it! Thank you for making it!

It would be nice if it was possible, within a track, to jump around.

For example, to skip the first few minutes of a longer track.

**Comment by TerryGeng** [comment]
Here you go.
Usage:
`!play {index_to_play} {start_at}`

where start_at can be things like 01:01:01, 01:01, 01:01:01.123, 01:01.123. 1.123, etc.

Documentation will be added later.

**Comment by TerryGeng** [comment]
The newest commit has made this function into the web interface. You may want to have a try!
