### ISSUE TITLE
Web interface privilege settings

### ISSUE THREAD

**Issue by TerryGeng** [azlux/botamusique#154]
One of my friend asked me if I can add a privilege system for the bot. I think he means only granting users in a special ACL group the privilege to control the bot. I think it makes sense, since more and more people are using the bot in a multi-user scenario (like @felix91gr).

I believe I can find some API in pymumble that can be used in seeing the group of a user. The problem is, what password should be used when users log in the web interface. Mumble doesn't use password to authorize users, so I'm wondering is there any good way of doing so?

Perhaps I can invent a command called something like `!webpw {password}` to create a personal password and store them into the database? I think mumble expert @azlux can provide more insights.

**Comment by TylerVigario** [comment]
What about client IP?

**Comment by azlux** [comment]
Hi,
As discuss on the IRC. Here the way to do it we have imagine.
The webpage give nothing except to say :`!web` to the bot.

The bot give you an URL (with unique token in the link) you can use to access to the webpage.

This way:
- Mumble server and bot can be in different server
- The bot don't need anything else than basic server access (we want to avoid using superadmin access)
- It's working with proxy (when an user have proxy, so different IP with https protocol)

@TylerVigario maybe we can add a IP check fallback. I don't know how much work it is.

**Comment by TylerVigario** [comment]
@azlux Your proposal sounds great! It sounds familiar to a token authentication system like for APIs.

**Comment by TerryGeng** [comment]
> The bot give you an URL (with unique token in the link) you can use to access to the webpage.

Yes... The ACL design of mumble requires super user's power to fetch the user group. I can imagine people would feel confused to see a little bot are requesting to be a super user.

Now the parcel has passed to our hands, and we are going to have our own way of managing privilege.

I think the one-URL-per-user way is good. As long as we have generated a link for a user, we can distinguish among users, and users can add that link to his bookmark (we can also choose to generate temporary links).  Links and its expiration time can be stored in the database.

Other options include only granting some users the power of uploading songs, etc.

That will be extremely helpful.

**Comment by azlux** [comment]
first draft done.
We need to check an issue I have with that. We do POST to GET information, that is blocking some read requests is not logged.

**Comment by TerryGeng** [comment]
It looks like the current draft version keep the traditional password authorization and token authorization together, and users can use them at the same time. I think this is somewhat redundant. I'm thinking about put on a switch, and user can select which method to use in the config file.

**Comment by azlux** [comment]
Last question:
Currently the bot make a 403 error if you don't have the access.
Is making read-only the webinterface better or not ?

**Comment by TerryGeng** [comment]
That will be a lot of work.... And I don't think it is useful. I think rather than annoying the user by a not usable web interface, we'd better ask them to get a token link at once.

**Comment by azlux** [comment]
good can we close it ?
