### ISSUE TITLE
Removing jquery

### ISSUE THREAD

**Issue by azlux** [azlux/botamusique#157]
Hi,
This issue is to discuss and track the goal to remove jquery from this project.
Steps:
- [ ] removing inline Jquery uses
- [ ] choosing a replacement to boostrap
- [ ] migrate to the new CSS framework
- [ ] removing Jquery
- [ ] Testing and release

After many discussion with some developers, I think [Bulma](https://bulma.io/) is the best framework to use.

**Comment by TylerVigario** [comment]
I would love to take some inspiration from [AmplitudeJS](https://github.com/521dimensions/amplitudejs)
