### ISSUE TITLE
Refactoring web interface backend and freeze the interface

### ISSUE THREAD

**Issue by TerryGeng** [azlux/botamusique#158]
I think now the web interface has already got all features I've planned. In fact, starting from adapting ajax to the web interface, we are no longer relying on "filling" jinja2 template when requesting the index.html, instead we make nearly all requests made in ajax way and getting json data back from the server.

This move essentially separated the bot and the web interface, because the web interface is almost, just a webpage that is independent of the bot's logic.

I took some time to consider, and I think maybe it is just the time to freeze the backend interface provided by the bot, and separate the development of the web interface from the bot, at least, in another branch, and let web developers do the job in their own ways. 

A new workflow is needed for web design mentioned in #155 make some sense to me. We usually treat the web interface as an auxiliary of the bot, but it is apparently not the entire case now. Web interface has been used by more and more people (and I'm intend to keep it enabled by default config files in the next version). Now the huge "custom.js" has a length of 1000+ lines, makes me struggling even navigating through the file. One way is to separated the custom.js into many modules, but just to avoid linking a bunch of js files in index.html, we need something to bundle up modules into a single js file (#155). At this point I start to feel the need for a workflow actually make some sense.

Other possible advantages include if we adapt some dynamic js bundler, we can select only the part we used in bootstrap4, (or bootstrap5 or maybe Bumla in the future).

 I think next month I'm going to optimized the backend interface in interface.py, and I think PR regarding the bundler mentioned above is welcomed.

**Comment by TylerVigario** [comment]
I've started theses changes and created a draft PR (#159)

**Comment by TerryGeng** [comment]
Good to see @TylerVigario is working on this issue. I will keep track of this PR and will review and merge in the next month, as long as this branch is stable and in good shape.
