### ISSUE TITLE
Preprocess urls before hitting them in the playlist, keep a more detailed playlist

### ISSUE THREAD

**Issue by Lartza** [azlux/botamusique#16]
**Is your feature request related to a problem? Please describe.**
Currently the bot keeps a list of urls as it's playlist, and processes the song when it hits it in the playlist.

**Describe the solution you'd like**
Add music to playlist only after it has been fully processed (with full information of the song, url, title and the path). Download songs the moment they are added and possibly keep a processing queue to prevent messing the processing with fast duplicate requests.

**Describe alternatives you've considered**
I haven't, feel free to have a think.

**Additional context**
Keeps playback interruptions to a minimum and I feel like would improve the flow of #15

**Comment by azlux** [comment]
it's into my Todo list. I think it's better to download music when it's added.
I need to manage : 
- [ ] Maximum storage (This will cause lot of trouble)
- [ ] Delete the music if the song is remove from the playlist.

**Comment by azlux** [comment]
Working on my beta bot, on github in few days

**Comment by azlux** [comment]
Until I finish the code, you can check the branch : https://github.com/azlux/botamusique/tree/dev , all info are download at the moment we add a music.

**Comment by azlux** [comment]
now on master branch
