### ISSUE TITLE
Version 6.4 doesn't scan the music folder

### ISSUE THREAD

**Issue by Elinvention** [azlux/botamusique#163]
**Describe the bug**
Botamusic 6.4 doesn't scan the music folder. After update I deleted all databases (`rm *.db` and `git status` reports a clean working tree).

**Affected version**
58b7600cf95d3a8ca0e893e695370c3ba2fb18ee

**To Reproduce**
1. Install botamusique
2. Run botamusique
3. the `music_folder` isn't being scanned
4. No music files to play from web interface

**Expected behavior**
Botamusique should scan the music folder as in previous version.

**Desktop (please complete the following information):**
 - OS: Manjaro
 - Browser Firefox
 - Version 76.0.1

**Comment by Elinvention** [comment]
I run the `!rescan` command and it started scanning. So the actual issue is that it no longer does it at startup automatically.

**Comment by azlux** [comment]
What's the value of this parameter into you custom config ? https://github.com/azlux/botamusique/blob/master/configuration.default.ini#L70
`refresh_cache_on_startup`

**Comment by Elinvention** [comment]
Ah, I didn't see that. Sorry, it works fine then. I was tricked by this message at startup: `library: rebuild directory cache`.

**Comment by TerryGeng** [comment]
This is actually a bug, which should have been here for a long time.

**Comment by Elinvention** [comment]
I tested latest master and now it seems to hang for a while at `library: rebuild directory cache` at startup, even though I have ` refresh_cache_on_startup = False` in configuration.ini.

**Comment by TerryGeng** [comment]
I think you can run the bot with `-v` argument to see the detailed debug log. File paths will be shown in debug mode when scanning the folders.

**Comment by Elinvention** [comment]
`-v` doesn't show any file paths at startup and when I `!rescan`. However I think it should skip this process at startup if `refresh_cache_on_startup = False`, but it doesn't anymore.

**Comment by TerryGeng** [comment]
Do you think we need to reopen this issue?

**Comment by Elinvention** [comment]
Yes because now I don't want the bot to scan each time at startup. When I opened this issue I didn't know about `!rescan` and `refresh_cache_on_startup = False` and I was puzzled by the empty list of local files. Now I want the bot to rescan only when I know I changed the music directory. This way I can avoid having to wait a few minutes for the bot to startup.

**Comment by TerryGeng** [comment]
Sorry about the typo I have made. This problem should be fixed now.
