### ISSUE TITLE
Quits the channel when the last user disconnects

### ISSUE THREAD

**Issue by Elinvention** [azlux/botamusique#164]
**Describe the bug**
The bot disconnects when the last user leaves the channel. I have `when_nobody_in_channel = pause` in `configuration.ini`

**Affected version**
master 58b7600cf95d3a8ca0e893e695370c3ba2fb18ee

**To Reproduce**
1. Join mumble
2. start botamusique
3. disconnect from mumble
4. reconnect to mumble
5. Where is botamusique?

**Expected behavior**
Botamusique should not disconnect unless `ctrl+c` or `!kill` from admin.

**Comment by azlux** [comment]
you said it quit the channel. Means it get disconnected ? Do you see any error ?

**Comment by TerryGeng** [comment]
Bug reproduced. Caused by the way pymumble invokes the callback function jammed the main loop.
