### ISSUE TITLE
Web interface eat up CPU

### ISSUE THREAD

**Issue by TerryGeng** [azlux/botamusique#166]
After some investigation, I discovered the way I used to move the progress bar inside the little floating player triggers a reflow, which quickly eats up all CPU.

I have made a temporary workaround. I think this fix should also be performed on @TylerVigario 's branch.

**Comment by TylerVigario** [comment]
Nice catch! And no worries, I'll pull the changes into the branch.

**Comment by TylerVigario** [comment]
I've pulled the latest changes from the `master` branch.
