### ISSUE TITLE
Using !ysearch crashes the Bot

### ISSUE THREAD

**Issue by W0rmsy** [azlux/botamusique#167]
**Describe the bug**
After the last update the command !ysearch works one time and the bot crashes the second time the command is used.
There is no logs nor output, actually the PID is still running but the bot is no longer connected to mumble.

**Affected version**
V6.4 (last stable update)
I was able to reproduce the issue after reinstalling the bot and the issue is also present on GlaDoS (Sorry Azlux :'( your bot is gone)

**To Reproduce**
1. use the command: !ys test
2. use again the command !ys whatever
3. after few seconds the bot disconnect.

**Expected behavior**
pretty obvious ;-)

**Screenshots**
N/A

**Comment by TerryGeng** [comment]
Hi! Thanks for reporting to us. Can you provide the log the bot produced before crashing?

I suggest you run the bot with `-v` argument to get the detailed debug log. Maybe I can sniff something out of it.

**Comment by azlux** [comment]
I've see the same on my server.
We you run the search multple time, the bot freeze without any crash or output  after the log ` bot: received command ysearch`

So I've run a trace on the bot. The code stop here when the bot freeze. On a regex.....

```_collections.py(98):             for value in values:
adapters.py(326):         for proxy in self.proxy_manager.values():
sessions.py(732):         for v in self.adapters.values():
util.py(336):         results = re.findall(r"watch\?v=(.*?)\".*?title=\"(.*?)\".*?(?:user|channel).*?>(.*?)<", r.text)  # (id, title, uploader)
 --- modulename: models, funcname: text
models.py(850):         content = None
models.py(851):         encoding = self.encoding
models.py(853):         if not self.content:
 --- modulename: models, funcname: content
models.py(820):         if self._content is False:
models.py(831):         self._content_consumed = True
models.py(834):         return self._content
models.py(857):         if self.encoding is None:
models.py(861):         try:
models.py(862):             content = str(self.content, encoding, errors='replace')
 --- modulename: models, funcname: content
models.py(820):         if self._content is False:
models.py(831):         self._content_consumed = True
models.py(834):         return self._content
models.py(872):         return content
 --- modulename: re, funcname: findall
re.py(241):     return _compile(pattern, flags).findall(string)
 --- modulename: re, funcname: _compile
re.py(291):     if isinstance(flags, RegexFlag):
re.py(293):     try:
re.py(294):         return _cache[type(pattern), pattern, flags]
```

**Comment by TerryGeng** [comment]
@azlux That's something I didn't expect. Since the pymumble loop and the command function work in the same thread, the regex blocked the pymumble loop and made the bot not respond to the ping message, then the server assume the bot is died.

**Comment by azlux** [comment]
While debugging, Look like the youtubewebsite don't return the same output if you query multiple time.
The page is lot bigger and generate a regex Catastrophic backtracking.

**Comment by azlux** [comment]
Any news @W0rmsy ? Did you have time to change the regex according to our last discussion ?

**Comment by LODerror** [comment]
Hi I'm new to this space just wanted to say I have a similar issue, but it does the same for both !yplay and !ysearch. 

Do you have a donate page btw?

**Comment by SmearyQuill** [comment]
i have the same issue since i updated the bot with !Update command, i can add song with !url but using !ysearch disconnects the bot but it keeps running. In my case i can't use !ysearch at all, it crashes the bot the first time i use !ysearch.

**Comment by LODerror** [comment]
Come to think of it I only started having the issue after I used !update too.

**Comment by W0rmsy** [comment]
Hello, oopsy sorry yes I've a new regex that solve the issue. It's not super great but it work. I'll push the change tonight

**Comment by LODerror** [comment]
Will !update now solve the issue?

**Comment by TerryGeng** [comment]
@W0rmsy Hi, we are planning to release a new version in the coming days. Are you ready for the fix?

**Comment by W0rmsy** [comment]
Hi @TerryGeng, I just made a pull request with the fix.

**Comment by azlux** [comment]
I've tested it, it's merged.

**Comment by azlux** [comment]
@LODerror about the donate page, we don't have it.

I've discuss with some user on IRC, I try to open one to see if people so much crazy about botamusique :D 
https://www.bountysource.com/teams/botamusique

Of course, it's will be divide amount between participants.
