### ISSUE TITLE
Add i18n/l10n support

### ISSUE THREAD

**Issue by TylerVigario** [azlux/botamusique#172]
We should seriously consider internationalization support. A solution that works for both Python and JavaScript would probably be best, so people need not edit two separate files.

**Comment by TerryGeng** [comment]
Hi! Do you have any suggestions for localizing the HTML file?
I found "data-i18n" tag but am not sure if it is a good solution.

Recently, @azlux started a translation platform _traduora_ and it would be great if you know anything in npm that can help us integrate traduora into our build procedure.

**Comment by TylerVigario** [comment]
We could use https://arelstone.github.io/traduora-cli/ to export the translations as a JSON file for use within JavaScript.

**Comment by azlux** [comment]
I already have a python script to export everything in different format. We need to think how to include them into the project

**Comment by TerryGeng** [comment]
> Edit 2: As for the HTML you should use your Python back end to output the correct language string. I imagine you guys have found a way to integrate Traduora with Python.

I think we can use ninja2 to populate the HTML every time we build the web interface. Problem solved :).
