### ISSUE TITLE
Music too long indication of what is needed to make it play

### ISSUE THREAD

**Issue by Glowsome** [azlux/botamusique#173]
**Is your feature request related to a problem? Please describe.**
When issueing a download of like a youtube video which exceeds the download/sizelimit defined in the ini it will just report 'this music is too long' and will skip it.

**Describe the solution you'd like**
If a 'music is too long' info appears also indicate what would be needed to 'make it work' as in 
a reply which indicated the total size of the attempted music to play and current limit for adjustment:
Music too long - filesize is x , allow limit is set to y' 

**Describe alternatives you've considered**
None, this is to enhance informational messages

**Comment by TerryGeng** [comment]
Hi, the maximum length of music is defined in the config file, in the unit of minutes. I think if you'd like to fix it, this is the place you can have a look :).

**Comment by Glowsome** [comment]
@TerryGeng i know its defined there, but i am seeking more info as to if it were viable to increase the value or not.

**Comment by Glowsome** [comment]
Motivation as said is to provide more information in regards of the difference of the allowed size .. .i mean if i can allow something which plays for an hour just by configuring a mild increase, or that i am facing a major file of like an 8 Hr stream ... which will proppably fill up my /tmp ... i appreciate the insight so i can decide as admin if i am willing to increse the limit.

**Comment by Glowsome** [comment]
maybe even as an additional thing in this is that an ability/extra info should be restricted to admin only. 
But i would appreciate  a way in which i can determine if a change of this setting is viable or not ( by showing me the difference between bot setting and filesize attempted to download.

**Comment by Glowsome** [comment]
@TerryGeng would it be possible to craft something like an 'admin-only' override for this .. i mean default limit set to value 'x' in ini-file, but if i were to have something like an override by an admin that would ignore this setting, or like an admin can issue a download/play of the file but the limit is doubled'.
in my opinion : Best way to deal with this is to probe the size available on the storage, and then calculate the size of the download file, and then determine if (if you were to devise something like an admin download) to max out at like 80% of storage .. for normal downloads it should be the limit set in the ini.

**Comment by TerryGeng** [comment]
So the demand boils down to making a new option to ignore the duration limit when adding URL into the playlist. I'll see what I can do.
