### ISSUE TITLE
Return a sentinel JSON object instead of a 204 response when the playlist is empty

### ISSUE THREAD

**Issue by MineRobber9000** [azlux/botamusique#175]
**Is your feature request related to a problem? Please describe.**
I'm currently writing a bot to interact with the web interface to give info on the playlist (what's on the playlist, how many songs, etc.).

**Describe the solution you'd like**
It would really help if the web interface gave a sentinel JSON object. For instance, a `current_index` of -1 (like when the bot is paused), an empty `items`, a `length` of 0, and a `start_from` of 0 (or whatever `_from` is).

**Describe alternatives you've considered**
Currently, I'm special-casing the 204 response code to instead store this sentinel object on my side.

**Comment by TerryGeng** [comment]
I think this feature is related to #158. It makes sense to always return a JSON even when the playlist is empty. I'm going to do this in the next release.

**Comment by TerryGeng** [comment]
This feature has been implemented. Please have a look. Thanks!
