### ISSUE TITLE
OGG Upload support

### ISSUE THREAD

**Issue by risturiz** [azlux/botamusique#177]
**Is your feature request related to a problem? Please describe.**
I'm getting error with ogg files upload

![botamusique-web-interface](https://user-images.githubusercontent.com/12375/86053562-4ead8000-ba1e-11ea-9413-b689c534f8dc.png)

**Describe the solution you'd like**
Future support for this format?

Thanks.

**Comment by TerryGeng** [comment]
Can you try rename `.ogg` to `.oga` and try again?

**Comment by TerryGeng** [comment]
Nevermind. We have refined the type check in dbe25cec8e3cb991458db3122bf88312267dac59 and now it will be okay to upload .ogg files.

**Comment by felix91gr** [comment]
This is present in the new release. Should the issue be closed now?
@risturiz @TerryGeng

**Comment by TerryGeng** [comment]
Yes, I believe.
