### ISSUE TITLE
Stereo not working and play on mono mode

### ISSUE THREAD

**Issue by huizichin** [azlux/botamusique#178]
Stereo not working and play on mono mode
and i doing something wrong here 
i am using Mumble 1.3.1 and the stereo is enabled in the config file
it still play on mono idk

**Comment by azlux** [comment]
Mumble server isn't compatible stereo for now, this feature is for mumbler server 1.4
You can enable it if you use mumble server snapshot.

**Comment by huizichin** [comment]
how do i get mumble server 1.4
i tried getting the snapshot but is only able to get 1.3.1

**Comment by azlux** [comment]
1.4 is on Azlure CI : https://github.com/mumble-voip/mumble/issues/4303

https://dev.azure.com/Mumble-VoIP/Mumble/_build?definitionId=1&_a=summary (select the commit then click on "published")

**Comment by huizichin** [comment]
is there any reason that i cannot run the appimage on linux
the windows installer worked though

**Comment by huizichin** [comment]
mumble server 1.4 worked but it have high delay and have weird buzz noise (very buggy)
wont be using until fixed

**Comment by TerryGeng** [comment]
AFAIK (I'm the author of the stereo part of the mumble project https://github.com/mumble-voip/mumble/pull/4209), the newly added stereo support doesn't involve any modification on the server-side, which means an old 1.3.0 server is capable of handling stereo stream.

But users still need a new client (1.4.0) to play the stereo stream. Old clients will simply downmix the stereo stream into the mono stream.

I have no idea why the old server doesn't work for you. I'm using my 1.3.0 server and everything works fine.

**Comment by huizichin** [comment]
1.4 client does work, i did not tried using 1.3 server as i was told 1.4 is needed
Thanks!

**Comment by TerryGeng** [comment]
Sure. If you have more questions regarding mumble itself, I'd suggest you post them to https://github.com/mumble-voip/mumble/issues. I think people there are happy to help :).
