### ISSUE TITLE
Fuzzier search for !li command

### ISSUE THREAD

**Issue by felix91gr** [azlux/botamusique#179]
**Is your feature request related to a problem? Please describe.**

Yes. I have a song under the name `Books & JAZZ (Relax Music) (Books & JAZZ (Relax Music).opus` in my music library, yet when I search like `!li books` I get no results. I only get them when I search for `!li Books`, `!li Boo`, etc. Same for my `lofi` "playlists" (which are just long `.opus` files): I always forget if it is `Lofi`, `lofi` or `lo-fi` in the name. `!li x` only returns the results that have `x` as a substring of the name.

**Describe the solution you'd like**

A fuzzier search with the `!li` command. Case-insensitivity would be the first thing I would add, but sometimes you type very close strings to what you want to find has, like `lo-fi` for `lofi`. Hopefully those kind of "really close matches" could also be addressed.

**Describe alternatives you've considered**

Leaving it as it is today. This would be okay, but I think the amount of work required to have fuzzier search, given the amount of good libraries that are available for python, should not be so high as to not try to make `!li` search better in this regard.

**Comment by felix91gr** [comment]
I'm thinking of something like [`fuzzysearch`](https://pypi.org/project/fuzzysearch/), although since I'm not an active Python developer I don't know exactly what is the "best" package for this feature x3

**Comment by TylerVigario** [comment]
Maybe something like this https://github.com/luozhouyang/python-string-similarity?

**Comment by TerryGeng** [comment]
I think we have to choose between regex and fuzzy search. Of course, we can add some "search options", but I think currently the search function is complicated enough and I'd better keep it simple. What do you think?

**Comment by felix91gr** [comment]
> but I think currently the search function is complicated enough and I'd better keep it simple. What do you think?

You mean the `!li` function? I think it is pretty simple. It is just `!li <search_term>`, right?
If you mean that, yes, I agree, I'd rather keep it simple. I was thinking of keeping the current format, but with more broad searching so that if you have a typo or don't remember the exact letters of the title, you can still find the song you meant with `!li`.

**Comment by TerryGeng** [comment]
Right now, the `li` uses regex.
```
!listfile [{pattern}] - display list of available files (whose paths match the regex pattern if {pattern} is given)
```

I'd suggest we use fuzzy search instead of regex. Or we can only parse `/xxxxx/` as regex patterns.

**Comment by felix91gr** [comment]
> I'd suggest we use fuzzy search instead of regex

+1 :D

> Or we can only parse /xxxxx/ as regex patterns.

That sounds reasonable

**Comment by TerryGeng** [comment]
After some survey, I have decided to implement my own fuzzy algorithm, which will cope with the typo in each keyword and the reordering of the keywords. Will do later.

**Comment by TerryGeng** [comment]
I was trying to sort thing out and then I realized that the command you should is `!search`, `!li` works only for the file path. Since now we have all data saved in the library, I question the usefulness of `!li` and perhaps it would be marked as deprecated in the next version.

The `!search` command offers a "fuzzy" search to a certain degree. It searches the database with native SQL queries of sqlite3. I think any attempts to do the search by ourselves (for a library with several hundreds of songs) will slow the bot down. I won't try to work in this direction unless it is really necessary.

**Comment by felix91gr** [comment]
You are completely right. I would deprecate it and iterate on `!search` instead

**Comment by felix91gr** [comment]
Whoops, closed the issue. Didn't mean to, but hey, that's alright. Anyway, I think I agree :)
