### ISSUE TITLE
Maximum song duration and a blacklist of urls

### ISSUE THREAD

**Issue by Lartza** [azlux/botamusique#18]
**Is your feature request related to a problem? Please describe.**
Prevent, for example, 10 hour (configurable) videos automatically and other annoying videos manually.

**Describe the solution you'd like**
- [x] Add a max duration configuration option and a check to the bot that makes the bot ignore any songs that are over the set value.

- [x] Additionally keep a blacklist of videos (urlhashes?) that admins can add or delete to blacklist any unwanted songs. In the config file?

**Describe alternatives you've considered**
Keep track of the blacklist in a database. Ref #15

**Additional context**
People are jerks.

**Comment by azlux** [comment]
The maximum duration will slower the process. I need to extract info before the download : 
```
ydl.extract_info(url, download=False)
```

But it's look like this request if very low with youtube-dl

**Comment by azlux** [comment]
Max duration is working on my beta bot, on github in few days

**Comment by azlux** [comment]
Until I finish the code, you can check the branch : https://github.com/azlux/botamusique/tree/dev (the web interface isn't functional) , you can already add a max duration.

**Comment by azlux** [comment]
max duration : https://github.com/azlux/botamusique/commit/6aca72eaeebc5076c438bc61f86c2fb6c855ef06
