### ISSUE TITLE
When some user adds either link, local or other music echo back what position in queue it has

### ISSUE THREAD

**Issue by Glowsome** [azlux/botamusique#186]
**Is your feature request related to a problem? Please describe.**
Feature / related to issue #185 

**Describe the solution you'd like**
If a user adds/issues an add to botamusique's queue he/she should be notified of what position in queue the add has.

**Describe alternatives you've considered**
Example : 
- currently playing is like a stream
- user issues a related command which will add a valid entry to the queue.
- user is not aware of other stuff on the queue unless he/she issues !queue command.
- user gets dissapointed in bot, as its not playing what he/she wants (and doesnt know why)

**Additional context**
If something like a stream is playing (assuming it will never end):
- make issuer of queue add aware of this so he/she can issue a !stop so the queue moves on to the entry made.

if a media is playing with fixed length which has an ending time :
- inform player of where the issued add to queue is in regards of position - like "your song is next in queue"/. your song is in position X on the queued playlist.

**Comment by TerryGeng** [comment]
I'd like to remind that please use `!skip` instead of `!stop`.

And sounds reasonable to me.

**Comment by TerryGeng** [comment]
This feature has been implemented. Could you please have a check?

**Comment by Glowsome** [comment]
running a bit low on time - hope to check it soon

**Comment by Glowsome** [comment]
i have updated the bot, but have not seen the/a message as of yet. - is it also on stable or ?

**Comment by TerryGeng** [comment]
Did you check the master branch?
