### ISSUE TITLE
Ignore users, ignore users on different channels and ignore private messages

### ISSUE THREAD

**Issue by Lartza** [azlux/botamusique#19]
**Is your feature request related to a problem? Please describe.**
Stops people from trolling other people with music they aren't even going to listen, etc.

**Describe the solution you'd like**
- [x] Add an admin command to ignore and unignore users. Ignored users will not cause any response from the bot to any command. Keep a list of ignored users somehow.
- [x] Add a configuration option that if true, makes the bot ignore users that are not on the same channel as the bot and aren't admins. Exclude joinme from this condition.
- [x] Add a configuration option to make the bot ignore private messages that aren't from an admin. Exclude joinme from this too.

**Describe alternatives you've considered**
None

**Additional context**
People are jerks vol .2

**Comment by azlux** [comment]
Why don't you want private message ?

**Comment by Lartza** [comment]
That's probably the least important part by far, but think about IRC bots and how with a private message you don't get a public channel response to annoy others hidden. Also kind of announces when someone adds a music to the bot without the bot unnecessarily reading anything.
