### ISSUE TITLE
Add botcommand to display version

### ISSUE THREAD

**Issue by Glowsome** [azlux/botamusique#194]
**Is your feature request related to a problem? Please describe.**
Feature : Add a command to display latest version of the bot and yt-dl.

**Describe the solution you'd like**
implement !version command that shows the version so one can quickly check if you are up-2-date or not.

**Describe alternatives you've considered**
Finding version can sometimes be annoying - introducing a !version command that makes it visible would solve it.

Suggested output : 
`[23:50:51] To The Lounge: !version`
`[23:50:42] (Private) MusicBot: Botamusique version is xx.xx.xx and youtube-dl is version xx.xx`
IF new version is available at repository (for the bot or youtube-dl) (only show this when user who issued command is admin)
`[23:50:42] (Private) MusicBot: a new version is available for [botamusique| youtube-dl] - please update with !update`

**Comment by TerryGeng** [comment]
Implemented. Sorry for the delay. The problem we encountered is to find a way to add new translation items by commits, not by using traduora, and in the last version we finally worked out a solution.
