### ISSUE TITLE
End of sound file not played (200-400ms)

### ISSUE THREAD

**Issue by Rickvlaar** [azlux/botamusique#199]
**Describe the bug**
When playing a sound file, the last few hundred milliseconds are cut off, creating a static sound in Mumble. I mainly use the bot to play short files (2-5 seconds) so it was noticeable for me.

**Affected version**
V7.0 (Commit - 6133c6f0b5ab64513dcb0c395277232411a70848)

**Possible cause**
In the main loop in mumbleBot.py there is a check to keep the buffer size under control (see below). For some reason the ffmpeg command keeps running in the background while this code is running. The causes the ffmpeg job to finish before the rest of the loop is able to read all the buffered data. Around 60-70 thousand bytes are lost in total at the end of the stream.

Starting at line 457:

```
    # Main loop of the Bot
    def loop(self):
        raw_music = ""
        while not self.exit and self.mumble.is_alive():

            while self.is_ffmpeg_running() and self.mumble.sound_output.get_buffer_size() > 0.5 and not self.exit:
                # If the buffer isn't empty, I cannot send new music part, so I wait
                self._loop_status = f'Wait for buffer {self.mumble.sound_output.get_buffer_size():.3f}'
                time.sleep(0.01)
```

**Workaround**
As a workaround I've increased the pcm_buffer_size. The issue was resolved for me when I increased the buffer to over 50.000 bytes.

I changed line 390 of mumbeBot.py to:
`        self.pcm_buffer_size = 48000*channels`

_Really love the bot by the way, my compliments!_

**Comment by TerryGeng** [comment]
Hmmmm... I have used the bot for so long time and this is the first time I've heard this problem. 

In our code, we ask FFmpeg to decode the media file into 48000Hz 16bit-float format, which means for mono files, the bot will get 48000 * 16 / 8 bytes = 9.6KB per second.

Currently, the buffer is 960 bytes per channel, which corresponds to 10ms of music stream, which is the size required by opus to encapsulate one frame and the minimum frame length accepted by mumble (actually if you make this number larger, it will increase the size of each voice data packet, and one beyond a threshold, the pymumble will make them into separated frames and sends them according to the maximum bandwidth allowed by the server, so raw music data will pile up in your memory very fast, as you may have seen). 

Anyway, if the data of FFmpeg did get truncated by one loop, you will lose only 10ms of music. You won't even notice it. So I assume the problem comes elsewhere. Perhaps it depends on the file you play.

Can you examine more files and provide us with one problematic file so we can have more clues?

**Comment by Rickvlaar** [comment]
The issue began when I updated our bot from version 6.1 to 7.0 and this code was added somewhere in the meantime. Removing the while-loop related to the buffer altogether also resolved the truncation issue, but creates a problem with the buffer of course.

It's not a single loop that is missing, it's quite a bit more. The strange thing is that it is independent of buffer size or file length. I've tested with different buffer sizes and also with different files and each time the amount of missing data is around 60-70k bytes. So if 960 bytes per channel equates to  10 ms, that would mean that I would be missing around 0.3 seconds in stereo or 0.6 seconds in mono, which is not a lot, but is noticeable.

The static sound is probably caused by mumble or the server, not quite sure, but I think it is not related to the bot itself, but to the sudden end of the stream. I've noticed similar static noises with noise gates interrupting the stream, this also causes a short static sound. It's most likely unrelated.

You are right about the large buffer size causing some issues, it is not a very good solution for this issue. I will keep digging on my side as well. Thanks for thinking with me!

**Comment by TerryGeng** [comment]
I can write a patch that dumps the audio sends by the bot right before pymumble. Maybe that will tell if our bot is innocent :P

**Comment by Rickvlaar** [comment]
I think the culprit is the `time.sleep()` function, but I'm not sure why it would cause this issue. When I increase the sleep duration to around a second or so, the problem byte-loss is less. The issue could even be OS-specific. I run Catalina btw.

**Comment by TerryGeng** [comment]
Which sleep function?

**Comment by TerryGeng** [comment]
I have made the dump. Please pull the latest commit b3fe43cb1800091b159f1ff61dae73f682151b4e and apply this patch by `git apply [filename]` 

```
diff --git a/mumbleBot.py b/mumbleBot.py
index fec4943..46b5ec3 100644
--- a/mumbleBot.py
+++ b/mumbleBot.py
@@ -456,6 +456,12 @@ class MumbleBot:
 
     # Main loop of the Bot
     def loop(self):
+        import wave
+        wf = wave.open(f"{time.time()}.wav", 'wb')
+        wf.setnchannels(2 if self.stereo else 1)
+        wf.setsampwidth(2)
+        wf.setframerate(48000)
+
         raw_music = ""
         while not self.exit and self.mumble.is_alive():
 
@@ -475,6 +481,8 @@ class MumbleBot:
                 raw_music = self.thread.stdout.read(self.pcm_buffer_size)
                 self.read_pcm_size += self.pcm_buffer_size
 
+                wf.writeframes(raw_music)
+
                 if self.redirect_ffmpeg_log:
                     try:
                         self.last_ffmpeg_err = self.thread_stderr.readline()
@@ -568,6 +576,7 @@ class MumbleBot:
                     and var.config.get("bot", "save_music_library", fallback=True):
                 self.log.info("bot: save playlist into database")
                 var.playlist.save()
+            wf.close()
 
     def volume_cycle(self):
         delta = time.time() - self.last_volume_cycle_time
```

**Comment by Rickvlaar** [comment]
> Which sleep function?

On line 471: `time.sleep(0.01)`

Thanks for the dump patch! Please see these two output files attached. I created two files, one using the master branch code and one where I applied my workaround. The file created by the master branch is truncated by around 0.3s. Also added a screenshot of the two waveforms compared.

[Dumped wavs.zip](https://github.com/azlux/botamusique/files/4975462/Dumped.wavs.zip)
<img width="1024" alt="Waveforms compared" src="https://user-images.githubusercontent.com/43035473/88456043-db5f2880-ce7a-11ea-92e3-38ea727a1707.png">

**Comment by TerryGeng** [comment]
Hi. Did you make this dump with the large buffer size mentioned? Or you have kept the buffer to be 960 bytes? The pipe in *nix platform works in blocking mode by default, which means if ffmpeg has filled the buffer, it will be blocked until we read the buffer. That's why I assert we can only lose 10ms. Now such a 0.3s of truncation is what I can't understand.

BTW I run Catalina as well.

**Comment by TerryGeng** [comment]
Okay. I tried to generate some artificial samples and now I have also seen this ~0.3s cut. Let me investigate...

**Comment by Rickvlaar** [comment]
I used the standard buffer size of 960 bytes for these dumps.  

I find it very mysterious, it might be an issue with the sleep method not immediately halting the ffmpeg job running on the thread.

**Comment by TerryGeng** [comment]
Whoops... Accidentally closed this by the commit message. I think this problem has been fixed now. Can you check it for me?

**Comment by Rickvlaar** [comment]
Your fix works perfectly! I've been trying to find the reason for the unexpected behaviour from the .poll() function, but haven't been able to yet. I will let you know if I manage to find anything. Thanks for the help Terry!
