### ISSUE TITLE
Record option

### ISSUE THREAD

**Issue by risturiz** [azlux/botamusique#200]
Hi, its possible to add something like "!record" to save the audio? (useful for podcast record). Maybe we can have podcast playlist saved on database and ppl can listen when enter bot channel.

Thanks for the bot... It´s great

**Comment by TerryGeng** [comment]
Hello! Well, I think the bot is just a music player. It doesn't make sense to record local music. So I assume you mean to record the radio stream?

I can think of a handful of problems that would come with this feature. If we are going to implement this, should we limit this feature to just admin or all users? Should we impose a length limit to avoid blowing up your storage? How to name the file, with a name the user provides, or grabbing the ICE message from the stream?

I happen to know a bot https://github.com/Robert904/mumblerecbot that can record the audio of a channel. Does it fit your demands?

**Comment by risturiz** [comment]
Hi... Yes you are right... Im gonna test mumblerecbot... Thanks!
