### ISSUE TITLE
Feature request: Interfacing between configuration.ini and ydl_opts

### ISSUE THREAD

**Issue by pqp** [azlux/botamusique#201]
**Is your feature request related to a problem? Please describe.**
I run botamusique on a Digital Ocean VPS. Since YouTube seems to blocked my server's [entire IPv6 block](https://github.com/ytdl-org/youtube-dl/issues/21729#issuecomment-510342989), I have to force IPv4 usage with youtube-dl in order to circumvent the "HTTP Error 429: Too Many Requests" errors that follow `!url` calls.

**Describe the solution you'd like**
I'd really appreciate some sort of interfacing between configuration.ini and the [ydl_opts dictionaries](https://github.com/azlux/botamusique/blob/14668bb2b84e7873fae7772c2611ce0f14d9ebb6/media/url.py#L119) throughout [media/url.py](https://github.com/azlux/botamusique/blob/14668bb2b84e7873fae7772c2611ce0f14d9ebb6/media/url.py#L155). Currently I just manually patch into the dicts a simple `'source_address': var.config.get('bot', 'ydl_source_address'),` and then I specify `ydl_source_address = 0.0.0.0` in configuration.ini. This ensures IPv4 usage until someone in our Mumble server has botamusique update itself, and then those code changes are lost. Not a big deal, but slightly annoying. 

**Describe alternatives you've considered**
I first tried to specify system-wide settings for youtube-dl in `/etc/youtube-dl.conf`. Here I can also force IPv4, but this seems to only be recognized when youtube-dl is called directly through the command-line. That configuration file doesn't seem to be read in cases like botamusique's, where youtube-dl is _embedded_. Please correct me if I'm wrong.

**Additional context**
That's it. Thank you for botamusique--it's really quite fun to use on our Mumble server!

**Comment by azlux** [comment]
Hi,
Why don't you use a dns cache (like dnsmasq) and deny ipv6 resolution on youtube domains ?
Look like the faster way to resolve your issue.

**Comment by pqp** [comment]
Hello,

I will look into that! Thank you very much.
