### ISSUE TITLE
Option to disable deletion of music in library

### ISSUE THREAD

**Issue by bitconnector** [azlux/botamusique#202]
I started to link the music on my pc into the "music_folder" to have access to them on mumble. I realized, that it is possible to delete my local files using the web interface.

It would be nice to have a option to disable the deletion of entrys in the library

**Comment by TerryGeng** [comment]
Yes this make a lot of sense. Will do in 7.1.

**Comment by TerryGeng** [comment]
Sorry for my extremely late action... But I finally got it done. Would you like to test it? Just add the following lines to your config file:
```
[webinterface]
delete_allowed = False
```

**Comment by bitconnector** [comment]
Thanks I will try it out :D
