### ISSUE TITLE
HTML from command output mixes with text from other users on latest Mumble builds (1.4)

### ISSUE THREAD

**Issue by Gert-dev** [azlux/botamusique#207]
**Describe the bug**
When using the latest Mumble builds, the HTML sent by commands such as `!help` interfere with the formatting of user text.

**Affected version**
Tag 7.1 or commit `e5a2d810fc0fb2443582af07ca1b3d75cbaec8c6`. Only translation updates appear to have happened on latest `master`.

**To Reproduce**
1. Start the bot.
2. Fire up mumble and join the server.
3. Type `!help`.
4. Type something else and send it. It will now be put in a bullet list along with the command output.

**Expected behavior**
The output is put on a separate line.

**Screenshots**
![Before](https://user-images.githubusercontent.com/24809863/93479963-7230ea00-f8ec-11ea-890d-5e56c9039baa.png)

**Additional context**
I don't believe this happens on stable Mumble. A fix appears to be to simply insert a `<br>` at the end of the `admin_help` and `help` translation strings, which gives the expected result:

![After](https://user-images.githubusercontent.com/24809863/93479968-74934400-f8ec-11ea-9e97-64eab03fa7a2.png)

I would be happy to send a pull request, but can I modify these JSON files in Git? I see Traduora is used for translations and am not familiar with that, so perhaps these translations need to go through there instead?

**Comment by Gert-dev** [comment]
I've tested this in stable Mumble to be sure and, indeed, it does not appear to happen there. Perhaps it would be more suitable to report this upstream to Mumble? What do you think?

**Comment by azlux** [comment]
Hi,
Thank for the report, It's indeed a bug from mumble.
We can make a temporary fix into the translation strings.

**Comment by TerryGeng** [comment]
Since this is a bug of mumble, I guess I'd close this issue.
