### ISSUE TITLE
Configuration Option for less verbose chat output

### ISSUE THREAD

**Issue by ScorchedMuffin** [azlux/botamusique#211]
**Is your feature request related to a problem? Please describe.**
Would prefer if botamusique was less chatty. My users all have text-to-speech enabled and we primarily use botamusique to play short audio clips. In recent updates the bot puts a lot of text in the chat and the text-to-speech can drown out the audio being played.  

**Describe the solution you'd like**
It would be wonderful if there was a setting in the configuration.ini that would allow us to minimize how much text botamusique puts into the chat, or have a setting to disable it from putting text into the channel chat.

**Describe alternatives you've considered**
I've tried using ACLs to solve this unsuccessfully.

**Comment by TerryGeng** [comment]
Hi. We have two types of messages: one is the public message, which is displayed only on occasions when the info of the song and some important operation has been performed other users (like adding new songs into the playlist).
The other type is the private messages, which is basically the reply to users' command.

Which of these in your opinion is too verbose?

**Comment by ScorchedMuffin** [comment]
Thanks for the reply Terry! 

Mostly the public message. We don't need the bot to publicly announce when it's going to play an audio file. I believe this was the default behavior in the past.

**Comment by TerryGeng** [comment]
Hi. Actually we have one config option to disable this feature.

![image](https://user-images.githubusercontent.com/2306637/94504234-e64b8600-023a-11eb-832f-f6bdc0d8574f.png)

Would you like to have a try?

**Comment by ScorchedMuffin** [comment]
I do have that setting set to False, but it doesn't seem to have any effect. Let me know if I have something blatently wrong in my config:

![configfile](https://user-images.githubusercontent.com/43730639/94506833-4f4fe100-01dc-11eb-9d95-20ba6d8e534d.png)

**Comment by TerryGeng** [comment]
Hi. I have checked and confirmed that this option does work. And I think there's nothing strange in your config file. I'm not really sure what is wrong. I just want to make sure you are editing the right file. Which file did you edit?

**Comment by ScorchedMuffin** [comment]
I'm editing the configuration.ini file:
![image](https://user-images.githubusercontent.com/43730639/94881767-3e99a800-0434-11eb-83f1-aeec08099ddd.png)

And this is the systemd service file I'm using:
![image](https://user-images.githubusercontent.com/43730639/94881854-77398180-0434-11eb-87b4-d7f2b62d9e63.png)

Thanks for all your help :smile:

**Comment by TerryGeng** [comment]
I'd suggest you confirm that if all other config options take effects. When setting up services, I used the -c option to explicitly specify the absolute path of my config file. I think this could make a difference.

**Comment by TerryGeng** [comment]
Any update on this issue? If you have already solved this problem, I think I would close this issue.
