### ISSUE TITLE
duck: Command failed with error

### ISSUE THREAD

**Issue by KnightWhoSaysNeeeowWumPing** [azlux/botamusique#213]
**Describe the bug**
When trying to enable ducking with the `!duck` command, the command fails with the following error message and ducking does not get enabled.
```
duck: Command failed with error: AttributeError: module 'pymumble_py3' has no attribute 'c'.
```

**Affected version**
v7.1 (*using the recommended install, updated with `!update`*)

**To Reproduce**
1. Updating the bot as described in the readme via `!update` to version 7.1
2. Enable ducking via `!duck` or `!duck on`

**Expected behavior**
Enable the ducking function as stated in the command list (through `!help`)

**Comment by azlux** [comment]
I suppose it's a typo. Should be fix on beta release (or next stable)
