### ISSUE TITLE
Error Whilst Launching - Invalid Syntax

### ISSUE THREAD

**Issue by JordansplaceYT** [azlux/botamusique#217]
Im not sure what im doing wrong , ive been following the steps but i keep getting the lines 
_______________________________________________________________________
venv/bin/python mumbleBot.py --config configuration.ini
  File "mumbleBot.py", line 40
    self.log.info(f"bot: botamusique version {self.version}, starting...")
                                                                        ^
SyntaxError: invalid syntax
________________________________________________________________________

im not sure if im missing somthing in the config or if its wrong info but if you know a solution to this it would be greatly appreciated ,thanks

**Comment by TerryGeng** [comment]
Hmmmm... not really sure what is wrong. Perhaps your python version?

What does it show if you type in `venv/bin/python --version`?

**Comment by JordansplaceYT** [comment]
Version 3.5.2

**Comment by TerryGeng** [comment]
Great. Thanks for the quick reply. Actually out bot requires python version greater than 3.6. Can you update your python?

**Comment by JordansplaceYT** [comment]
absolutely

**Comment by JordansplaceYT** [comment]
i have installed python 3.9 but the venv command sais 3.5.3 - is there a install you would reccomend i get ?

**Comment by JordansplaceYT** [comment]
So I Manged to Get my version to 1.8 - but now when i do the commands its telling me that i dont have pip.

and when trying to launch mumblebot.py it gives this telling me i dont have python.


Traceback (most recent call last):
  File "mumbleBot.py", line 15, in <module>
    import pymumble_py3 as pymumble
ModuleNotFoundError: No module named 'pymumble_py3'

**Comment by TerryGeng** [comment]
Basically I'd suggest you reinstall the bot completely after you have updated your python version. Would you please try a full reinstall?

**Comment by JordansplaceYT** [comment]
im doing this thru ssh , how would i go about doing it ?

**Comment by JordansplaceYT** [comment]
thank you so much for your time by the way !

**Comment by TerryGeng** [comment]
Oh that should be pretty simple ;). Just delete the bot, and redo all the instructions in the README.

**Comment by JordansplaceYT** [comment]
em , yeah what command would i use to delete the directory ?

**Comment by JordansplaceYT** [comment]
im using ubuntu

**Comment by TerryGeng** [comment]
In this case, I'd actually suggest you look up on the Internet.

Just for your information, do `rm -rf {the folder of your bot}`

**Comment by JordansplaceYT** [comment]
in about 30 minutes ill plug the computer into my monitor and do it manually, i hope that is not a inconvience

**Comment by JordansplaceYT** [comment]
jordan@bt3mumble:~/botamusique$ python3 -m venv venv
Error: Command '['/home/jordan/botamusique/venv/bin/python3', '-Im', 'ensurepip', '--upgrade', '--default-pip']' returned non-zero exit status 1.  

this is what i was greeted with on install

**Comment by TerryGeng** [comment]
See https://stackoverflow.com/questions/24123150/pyvenv-3-4-returned-non-zero-exit-status-1 and make sure you replace all python3.4 into something that makes sense for you python version.

**Comment by JordansplaceYT** [comment]
Its in my server ! thank you so much !
that worked perfectly :)

**Comment by TerryGeng** [comment]
You are welcome :) However, I would like to remind you that Google can always offer you better answers for most of your problems. Please make good use of it.

**Comment by JordansplaceYT** [comment]
i apoligise xD , i was quite stuck here thanks so much for the help have a good one mate !
