### ISSUE TITLE
Changing playlist mode to random yields error

### ISSUE THREAD

**Issue by seijikun** [azlux/botamusique#222]
**Describe the bug**
Changing the playlist mode to random in the webinterface doesn't work, every other mode works.
Changing the playlist mode using a chat-command yields a python error:
```
mode: Command failed with error: TypeError: launch_music() missing 1 required positional argument: 'music_wrapper'.
```

**Affected version**
ff7baabe94ff8453b56e9ebc90f319a98f030c9f

**To Reproduce**
1. Type `!mode random` in the chat

**Expected behavior**
The playlist mode should change to random.

**Desktop (please complete the following information):**
 - OS: Linux, openSUSE Tumbleweed
 - Browser Firefox
 - Version 84.0a1 (2020-11-06)

**Comment by TerryGeng** [comment]
Thanks for reporting to us.

Fixed in 014086305d54a2b585839f34e8d279c384658596.
