### ISSUE TITLE
Doesn't play youtube or soundcloud songs

### ISSUE THREAD

**Issue by Sforg26** [azlux/botamusique#224]
Hello, thank for your works! I assume that the issue could be for some steps that I didn't make, i'm new in the bot usage, so thanks for the support. 
I'm using botamusique 7.1 on Kubuntu 20. 
When I put some youtube or soundcloud video they result in the queue and the bot show the message which it take them, but then they don't play neither with !skip or !play. 
The radios, instead, works flawless.
When i try do download an url, this is an example of the terminal messages that appears:

[Nov 08 17:48:32 INFO] bot: start preparing item in thread: [url] SHOOTIN' IN DA CLUB (https://soundcloud.com/berrymane/shootin-in-da-club)
Exception in thread Prepare-8bb48f2:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "mumbleBot.py", line 445, in _download
    item.prepare()
  File "/home/myfolder/botamusique/media/cache.py", line 160, in prepare
    ret = self.item().prepare()
  File "/home/myfolder/botamusique/media/url.py", line 112, in prepare
    return self._download()
  File "/home/myfolder/botamusique/media/url.py", line 144, in _download
    media.system.clear_tmp_folder(var.tmp_folder, var.config.getint('bot', 'tmp_folder_max_size'))
  File "/home/myfolder/botamusique/media/system.py", line 29, in clear_tmp_folder
    if get_size_folder(path=path) > size:
  File "/home/myfolder/botamusique/media/system.py", line 14, in get_size_folder
    folder_size += os.path.getsize(filename)
  File "/usr/lib/python3.8/genericpath.py", line 50, in getsize
    return os.stat(filename).st_size
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/.org.chromium.Chromium.VCFRaZ/SingletonCookie'

I hope to have been clear. Thank you for the help!

**Comment by Sforg26** [comment]
I was forgetting, the  '/tmp/.org.chromium.Chromium.VCFRaZ/SingletonCookie' file exist, but the folder is hidden.

**Comment by azlux** [comment]
Hi,
It's currently working. Can you do a `!update` ? Maybe your youtube-dl isn't up-to-date.

**Comment by Sforg26** [comment]
I try it but it doesn't work, maybe there are any connection reason due to my internet settings. I try also without vpn, it seems to work better but the message in terminal is the same, the song appear on the playlist but when played there is no sound. I will keep trying thanks a lot

**Comment by TerryGeng** [comment]
Looks like this is purely a file access problem. The problem comes when the bot is calculating the size of the tmp folder to see if it is too big and cleaning is needed. Can you try to remove everything under /tmp, or can you just change the folder where the downloaded music files are saved? You can find this option in the configuration file.

**Comment by TerryGeng** [comment]
Any update on this issue? Can I close it now?

**Comment by Sforg26** [comment]
> Any update on this issue? Can I close it now?

Yes, I think you can. Sometimes it doesn't work yet but i think it's due to youtube or internet connection problems in downloading the tracks.
Thank you for the help!

**Comment by TerryGeng** [comment]
Great. Let me know if you need further help.

**Comment by AdelKS** [comment]
Hello,

I have been having this same output error when I try to play a youtube song:
```
➜  botamusique venv/bin/python mumbleBot.py --config configuration.ini
[Feb 27 22:14:52 INFO] database: no settings table found. Creating settings table version 2.
[Feb 27 22:14:52 INFO] database: no settings table found. Creating settings table version 2.
[Feb 27 22:14:52 INFO] database: no music table found. Creating music table version 4.
[Feb 27 22:14:52 INFO] database: no music table found. Creating music table version 4.
[Feb 27 22:14:52 INFO] library: rebuild directory cache
[Feb 27 22:14:52 INFO] library: rebuild directory cache
[Feb 27 22:14:52 INFO] bot: botamusique version 7.2, starting...
[Feb 27 22:14:52 INFO] bot: botamusique version 7.2, starting...
[Feb 27 22:14:52 INFO] bot: load playlist from previous session
[Feb 27 22:14:52 INFO] bot: load playlist from previous session
[Feb 27 22:15:08 INFO] bot: received command search - wahran randall by Adel
[Feb 27 22:15:08 INFO] bot: received command search - wahran randall by Adel
[Feb 27 22:15:59 INFO] bot: received command ysearch - randall wahran by Adel
[Feb 27 22:15:59 INFO] bot: received command ysearch - randall wahran by Adel
[Feb 27 22:16:05 INFO] bot: received command play - 1 by Adel
[Feb 27 22:16:05 INFO] bot: received command play - 1 by Adel
[Feb 27 22:16:30 INFO] bot: received command sl - 1 by Adel
[Feb 27 22:16:30 INFO] bot: received command sl - 1 by Adel
[Feb 27 22:16:30 INFO] url: fetching metadata of url https://www.youtube.com/watch?v=LiqIQ5He7_4 
[Feb 27 22:16:30 INFO] url: fetching metadata of url https://www.youtube.com/watch?v=LiqIQ5He7_4 
[Feb 27 22:16:30 INFO] cmd: add to playlist: [url]  (https://www.youtube.com/watch?v=LiqIQ5He7_4)
[Feb 27 22:16:30 INFO] cmd: add to playlist: [url]  (https://www.youtube.com/watch?v=LiqIQ5He7_4)
[youtube] LiqIQ5He7_4: Downloading webpage
[youtube] Downloading just video LiqIQ5He7_4 because of --no-playlist
[Feb 27 22:16:30 INFO] bot: current music isn't ready, start downloading.
[Feb 27 22:16:30 INFO] bot: current music isn't ready, start downloading.
[Feb 27 22:16:30 INFO] bot: start preparing item in thread: [url] RANDALL - Wahran (Official Audio) (https://www.youtube.com/watch?v=LiqIQ5He7_4)
[Feb 27 22:16:30 INFO] bot: start preparing item in thread: [url] RANDALL - Wahran (Official Audio) (https://www.youtube.com/watch?v=LiqIQ5He7_4)
Exception in thread Prepare-ad1063a:
Traceback (most recent call last):
  File "/usr/lib/python3.9/threading.py", line 954, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.9/threading.py", line 892, in run
    self._target(*self._args, **self._kwargs)
  File "/home/adel/Documents/Gethings/botamusique/mumbleBot.py", line 446, in _download
    item.prepare()
  File "/home/adel/Documents/Gethings/botamusique/media/cache.py", line 160, in prepare
    ret = self.item().prepare()
  File "/home/adel/Documents/Gethings/botamusique/media/url.py", line 112, in prepare
    return self._download()
  File "/home/adel/Documents/Gethings/botamusique/media/url.py", line 144, in _download
    media.system.clear_tmp_folder(var.tmp_folder, var.config.getint('bot', 'tmp_folder_max_size'))
  File "/home/adel/Documents/Gethings/botamusique/media/system.py", line 29, in clear_tmp_folder
    if get_size_folder(path=path) > size:
  File "/home/adel/Documents/Gethings/botamusique/media/system.py", line 14, in get_size_folder
    folder_size += os.path.getsize(filename)
  File "/usr/lib/python3.9/genericpath.py", line 50, in getsize
    return os.stat(filename).st_size
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/.org.chromium.Chromium.DUOJ8d/SingletonCookie'
```
This file though, does exist and is indeed in the `/tmp` folder :thinking: 

This is a fresh `manual install` from README though, and I have everything up to date from `pip`, youtube-dl from the pip venv works if I used it directly :thinking:

**Comment by TerryGeng** [comment]
@AdelKS Hi. Please open a new issue. This issue is already closed. Please also provide the information on your OS.

**Comment by TerryGeng** [comment]
I suppose this bug is fixed now. But my advice is: don't use `/tmp` directly, instead use something like `/tmp/bot` instead.

**Comment by AdelKS** [comment]
Hello, thank you very much for your fast feedback and fix. I will give it a shot as soon as I can and report back.

**Comment by sethidden** [comment]
To fellow clueless people - seems like the `tmp_folder` config param is only available through configuration.ini file https://github.com/azlux/botamusique/blob/5436aee3c8f0d0a0b96ce8e43db36dadd6dd6012/configuration.default.ini#L50

I just changed it from /tmp to a folder in the botamusique folder that I created (eg `mkdir downloaded_songs` then `tmp_folder = downloaded_songs/`
