### ISSUE TITLE
Bot not reconnecting after a disconnection

### ISSUE THREAD

**Issue by SlimGary** [azlux/botamusique#231]
Hi ! First of all, thanks a lot for your work, I use the bot everyday !

I have a little bug, not that annoying usually but since my ISP is getting crazy these days and gives me a lot of DC everyday, it's a little bit more; 

When my internet connection is down, the bot disconnects but doesn't reconnect by himself when the connection is back. Is it a bug ? If not, is there a way to make an auto-reconnect feature a thing ? Since i'm using docker, it's not that hard to restart the whole container, but sometimes i'm not available to restart it and my friends can't use the bot until i'm available.

Thanks a lot again for your work !

**Comment by TerryGeng** [comment]
I think the bot will just quit if the connection is lost. Is that the behavior you have observed?

Actually, I run the bot as a daemon with _Supervisor_, and it will help me restart the bot if it quits. Please check out this page to see how to set it up this way: https://github.com/azlux/botamusique/wiki/Run-botamusique-as-a-daemon-In-the-background.

**Comment by peylight** [comment]
I have the same problem.
Supervisor or Systemd service can not help, Because the service is up but the Bot has gone.

**Comment by TerryGeng** [comment]
We use the `is_alive` function of pymumble to determine if the connection is lost. That's all. This could be a bug in pymumble. What do you think about it? @azlux

**Comment by azlux** [comment]
Can you try again with the new release ?
Pymumble have been updated since the previous stable version.

**Comment by SlimGary** [comment]
I'm already on Testing , but I'll update it and will update . It happens too when the bot is kicked (Happens sometimes due to missclicks) , and I have to restart the container

**Comment by TerryGeng** [comment]
Okay. Seems like a bug in pymumble. I will spend some time investigating.

**Comment by azlux** [comment]
Can you check again with this new commit ?

**Comment by SlimGary** [comment]
it works ! Thanks a lot !!
