### ISSUE TITLE
!next does not work

### ISSUE THREAD

**Issue by ayockel** [azlux/botamusique#24]
**Describe the bug**
!next produces "Incorrect command"

**Affected version**
Current version

**To Reproduce**
Connect the bot and type !next

**Expected behavior**
Move to the next track in the playlist.

**Comment by Lartza** [comment]
This is fixed with #22. In the meantime you should be able to fix it by adding repeat = repeat to the configuration file command section.

**Comment by azlux** [comment]
Merged !
