### ISSUE TITLE
Add IPv6 support for downloading the bot

### ISSUE THREAD

**Issue by wnhre2ur8cxx8** [azlux/botamusique#242]
The installation instructions do not work in an IPv6 only network. Requests on Port 80 always timeout:

`curl -Lo botamusique.tar.gz http://packages.azlux.fr/botamusique/sources-stable.tar.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:00:31 --:--:--     0
curl: (7) Failed to connect to packages.azlux.fr port 80: Connection timed out
`

or telnet on the Port:

`telnet packages.azlux.fr 80
Trying 2a01:728:401:13::1:1...
telnet: Unable to connect to remote host: Connection timed out
`

You have AAAA records for the domain but you seem to not have opened port 80 in your firewall or something.

Can you please add this? Or host the packages somewhere else? Or fix the instructions so they work on IPv6 only hosts? :) thanks a lot the bot looks super promising.

**Comment by wnhre2ur8cxx8** [comment]
Whoops also realized the autoupdate breaks the bot because of this. So its not only an installation issue.

**Comment by azlux** [comment]
Weird, ipv6 look find here.
Do you have better analyses
 ?
```[dmichel@jumpy ~]$ curl http://packages.azlux.fr -vvv
*   Trying 2a01:728:401:13::1:1:80...
* Connected to packages.azlux.fr (2a01:728:401:13::1:1) port 80 (#0)
> GET / HTTP/1.1
> Host: packages.azlux.fr
> User-Agent: curl/7.72.0
> Accept: */*
>
* Mark bundle as not supporting multiuse
< HTTP/1.1 200 OK
< Server: nginx
< Date: Mon, 18 Jan 2021 21:23:38 GMT
< Content-Type: text/html
< Content-Length: 4423
< Connection: keep-alive
< Last-Modified: Tue, 01 Dec 2020 16:32:05 GMT
< ETag: "5fc67005-1147"
< Accept-Ranges: bytes
<
```

**Comment by TerryGeng** [comment]
Hello! It has been a few days since you have started this issue. If there's no further update on this matter, I will assume it has been resolved and close this issue.

**Comment by wnhre2ur8cxx8** [comment]
Please give me this weekend, I will check the issue again.

**Comment by wnhre2ur8cxx8** [comment]
OK I checked it and weirdly enough it works on another machine in another network, just like that.

BUT: on the same machine it refuses to connect I can reach other servers no problem. 

``` bash
curl http://packages.debian.org -vvv -6
*   Trying 2a02:16a8:dc41:100::132...
* TCP_NODELAY set
* Connected to packages.debian.org (2a02:16a8:dc41:100::132) port 80 (#0)
> GET / HTTP/1.1
> Host: packages.debian.org
> User-Agent: curl/7.64.0
> Accept: */*
> 
< HTTP/1.1 302 Found
....
```

Your domain, same client:

``` bash
curl http://packages.azlux.fr -6 -vvv
*   Trying 2a01:728:401:13::1:1...
* TCP_NODELAY set
* connect to 2a01:728:401:13::1:1 port 80 failed: Connection timed out
* Failed to connect to packages.azlux.fr port 80: Connection timed out
* Closing connection 0
curl: (7) Failed to connect to packages.azlux.fr port 80: Connection timed out
```

Again maybe something is blocking my IP range or something? The hoster is hetzner, and the server is physically located in Finnland. Maybe you have some weird geoblocking activated? Sorry maybe I am completely wrong in my analysis here, but it doesnt feel like the error is on my end. I even disabled the whole firewall while trying the above commands.

**Comment by TerryGeng** [comment]
This sounds like some local network issue. I'm afraid we can not provide more help regarding this.

I would suggest you check your link status `ip addr` to see if IPv6 is up. Meanwhile, I think you should also look into the routing table.

**Comment by wnhre2ur8cxx8** [comment]
I know my IPv6 is up because I am hosting the mumble server over it :) but OK, I will have a deeper look into it. Thanks

**Comment by azlux** [comment]
You can join me on IRC tomorrow evening , I can help you to debug. I'm my own provider, so I kown I don't have any geoblocking.

**Comment by Lartza** [comment]
I might add that while my server (dedicated) might be in a different IP block it's also located at Hetzner Finland and connection to the packages server works, there is certainly thus no widespread issue in this route.

**Comment by wnhre2ur8cxx8** [comment]
It all sounds like I have some network configuration issue. Thanks so much you all. I am just diving into IPv6 and I still have so much to learn :D

**Comment by Lartza** [comment]
I spoke too soon! I tested it before and it worked yesterday or the day before but now I am having issues too. Might not be on you :P

**Comment by azlux** [comment]
Like @Lartza say, look like Hertzer (Finland only) have routing issue.
Lot of RIPE Atlas probes are working in IPv6. I will check with my provider.
