### ISSUE TITLE
Configuration option to disable commands

### ISSUE THREAD

**Issue by wnhre2ur8cxx8** [azlux/botamusique#243]
**Is your feature request related to a problem? Please describe.**
I want to disable commands I do not use without editing the source code.

**Describe the solution you'd like**
Have an option in the configuration.ini like `play_file = null` or something.

**Describe alternatives you've considered**
editing the command.py and removing irrelevant commands. Its annoying because it will break after updates.

**Additional context**
I dont use any web features or local media, so most options are unnecessary and overwhelming for users.

**Comment by TerryGeng** [comment]
You can just try `play_file = ` in the configuration file to set that command to be an empty string. The bot will ignore empty commands.

**Comment by wnhre2ur8cxx8** [comment]
Thats nice I guess, but it would be nicer to have the `!help` command output only the activated commands then :) Thats whats overwhelming the most for users.

**Comment by TerryGeng** [comment]
That's something I have thought about but was too lazy to get it done. I will see if I can find some time to implement this.
