### ISSUE TITLE
Problems with web interface

### ISSUE THREAD

**Issue by CodingArctic** [azlux/botamusique#244]
**Describe the bug**
When enabling web interface, I can't access it from my browser on my main pc. I'm running botamusique on an amazon aws server, and have tested opening all ports to everything, with no success.

**Affected version**
Latest

**To Reproduce**
1. Enable web interface
2. Try to access web interface online
3. See it not work

**Expected behavior**
I expect it to let me open the web interface :p

**Screenshots**
https://i.imgur.com/Fwp9rco.png
https://i.imgur.com/MooOLAy.png

**Desktop (please complete the following information):**
 - OS: The server is running Ubuntu Server 20.04.1, my home pc is running windows 10
 - Browser: Firefox Nightly

**Additional context**

**Comment by azlux** [comment]
Did you have any reverse proxy front of the botamusique ? If not, you should listen 0.0.0.0 (all networks)
I recommend a reverse proxy if you can have one (nginx for example).

**Comment by CodingArctic** [comment]
@azlux setting it to 0.0.0.0 worked! would it be better to setup a reverse proxy? and if so how should i do that

**Comment by CodingArctic** [comment]
now my console spamming with these: https://i.imgur.com/fmZ1dDY.png

music is playing fine tho? and web interface is working

**Comment by TerryGeng** [comment]
These outputs are fine. It indicates the web interface is talking to the client.

Please let me know if you have further questions.

**Comment by TerryGeng** [comment]
> would it be better to setup a reverse proxy? and if so how should i do that

It would if you have a well-managed website with domains and SSLs done. You can check out the wiki page of this repo. But it is not really necessary for you I think. It's just a good practice.

**Comment by CodingArctic** [comment]
alright, and this a bad place to ask about running botamusique as a daemon? I'm having issues with supervisor @TerryGeng

**Comment by TerryGeng** [comment]
You can ask, but I would strongly recommend you read the official manual and see the examples of supervisor first.

**Comment by CodingArctic** [comment]
I went through their tutorial, and to start it, it said to run `$BINDIR/supervisord` but that just gives me a no such file or directory error.

**Comment by TerryGeng** [comment]
You are seeing the wrong guide. You need to check out how to run supervisors on _your Linux distributions_.

E.g. try a search of "install supervisors on ubuntu/debian/centos"

**Comment by CodingArctic** [comment]
https://i.imgur.com/DQSN4jO.png

getting this when attempting to start. followed a guide on ubuntu

**Comment by TerryGeng** [comment]
Looks like you are asking for very specific help. This is not the purpose of a github issue.

Please come to #mumble at freenode.net so we can continue.
