### ISSUE TITLE
Tags added through command are not escaped

### ISSUE THREAD

**Issue by seijikun** [azlux/botamusique#246]
**Describe the bug**
Tags added through the `addtag` command in the client are not HTML-Escaped.
You can thus use Mumble's HTML-Features (If enabled on the server) to inject HTML into the Web-Interface.

**Affected version**
Botamusique 7.2-13-g49779c2

**To Reproduce**
- Right-Click Channel you are in
- Send Message
- Switch to "Source Text"-Tab
- Paste `!addtag <a href="example.org">Blub</a>`
- Press OK

I have not yet dared to test, but this should also allow to insert other things except link-tags.

**Expected behavior**
Tags should probably be sanitized / escaped somehow.

This might also apply to other commands.

**Comment by TerryGeng** [comment]
Sorry for the late reply. Will investigate.

**Comment by azlux** [comment]
Added a quick fix. This should be enough to remove html injection.
