### ISSUE TITLE
Scan music sub-directories

### ISSUE THREAD

**Issue by paddatrapper** [azlux/botamusique#247]
**Is your feature request related to a problem? Please describe.**
I'm looking at using Botamusique to manage audio playout for live radio studio work. We have a music library managed by our scheduling system which uses a specific file management system with a variable number of sub-directories. Music files are then stored in these sub-directories.

**Describe the solution you'd like**
It would be great for the music library to scan sub-directories and show them to the user.

**Comment by TerryGeng** [comment]
The bot is capable of scanning sub-directories.

If you see the web interface, you can even discover a list of sub-directories that you can select.

![image](https://user-images.githubusercontent.com/2306637/106754657-319df700-6668-11eb-9bb1-1791e3d5d4ac.png)

**Comment by paddatrapper** [comment]
Seems I was running into the issue I fixed in #248 which was why I couldn't see sub-directories
