### ISSUE TITLE
Disk reading behavior

### ISSUE THREAD

**Issue by DataDropp** [azlux/botamusique#250]
I have many thousands of songs (around ~7000 songs) and starting the bot takes a really long time.
Looking at my disk usage I see a ton of reading from where my Music library is stored on.

Disk usage was high for a few minutes, and then it took a ton of processing time to then be done with 'rebuild directory cache'

I feel like the bot is looking at the contents of each music file rather than just looking at the file names.
```
botamusique# ./venv/bin/python3 mumbleBot.py 
[Feb 06 19:16:37 INFO] library: rebuild directory cache


[Feb 06 19:29:51 INFO] bot: botamusique version 7.2, starting...
[Feb 06 19:29:51 INFO] bot: load playlist from previous session
```
Note how long it took to load the bot.
This long delay took this long on first run with the bot. After running it a few more times it took around 3 minutes to load the bot.
Maybe switching to a different database engine would be better?
Is this normal behavior?
https://imgur.com/a/cpGwmOB

**Comment by TerryGeng** [comment]
While it is quite common you see high disk IO when rebuilding the cache. But actually what it does is simply iterate the folder.

The extra step that may seem to be costly is we read the MIME type of each file to determine if it is an audio file. But it just peeks the first few bytes of the file so should take long anyway. What I can do is to check the file type simply by checking the suffix, which may make this process faster. But I'm not sure about the consequence.

As a quick remedy, you can just set `refresh_cache_on_startup = False` to disable automatic cache rebuild when starting the bot. But the next time you added new files into the bot, you still have to rescan manually.

Though we managed to design a flexible structure and the caching mechanism, the bot is never designed to cope with ~7000 files. In my memory, there're people trying to manage ~3000 files on a low-end box and it worked well. The speed of this process is also determined by the machine you are using.

**Comment by TerryGeng** [comment]
I will soon work out a patch that uses suffices to determine file types. You can have a try with the patch later.
