### ISSUE TITLE
!sl is off by one index when selecting > 1

### ISSUE THREAD

**Issue by SeerLite** [azlux/botamusique#252]
**Describe the bug**
`!sl` is off by one if an index above 1 is selected. The previous one will be used

**Affected version**
49779c20aedb70181f9efa5526b179811649ee04

**To Reproduce**
1. Set up the bot with default configuration and have it join a server
2. Send `!ysearch rick astley never gonna give you up` 
3. Send `!sl 2`
4. Get rick rolled with the official video instead of whatever the next result (the wanted one) was.

**Expected behavior**
The correct video is chosen (e.g. index 2)

**Screenshots**
![image](https://user-images.githubusercontent.com/21978144/107448264-1166b000-6b20-11eb-8a41-6ccb620e85f3.png)

**Desktop (please complete the following information):**
 - OS: Arch Linux
 
**Additional context**
Could reproduce by selecting 3 and 4 too.

**Comment by TerryGeng** [comment]
I'm sorry that you got rick rolled.

Bug confirmed. Will be fixed shortly.

**Comment by TerryGeng** [comment]
Should have been fixed in https://github.com/azlux/botamusique/commit/c1671d5eb0cf869f603f941fd5a4f4ee1d43d2fa. Can you please have a look?

**Comment by SeerLite** [comment]
Works perfectly now, thank you!
