### ISSUE TITLE
Add files matching path

### ISSUE THREAD

**Issue by singpolyma** [azlux/botamusique#253]
While I can use the `!listfile` command to search my files by pathname, I cannot add a group of files matching some pathname, I can only add a single file by full path or files by pattern matching filename.  Would be great if I could add a whole folder, say, but saying `!fm Folder1/`

**Comment by TerryGeng** [comment]
You can add a whole folder by `!f {folder_name}`

```
[08:24:12] To music: !f vsq/
[08:24:12] (Channel) botamusique: Multiple items added:
Boulevard of Broken Dreams (vsq/Vitamin String Quartet - Boulevard Of Broken Dreams.mp3)
Windows (vsq/Vitamin String Quartet - Windows (Tom Tally).mp3)
My All (vsq/Vitamin String Quartet - My All.mp3)
Speechless (vsq/Vitamin String Quartet - Speechless.mp3)
...

```

**Comment by singpolyma** [comment]
Thanks!
