### ISSUE TITLE
Playback Countdown

### ISSUE THREAD

**Issue by paddatrapper** [azlux/botamusique#255]
**Is your feature request related to a problem? Please describe.**
It would be nice to be able to see how much longer a track has to play in the web interface

**Describe the solution you'd like**
The currently playing item can have an additional element with the time remaining/total time. For example a 3 minute song with 2 minutes to go: -02:00/03:00.

**Comment by TerryGeng** [comment]
Please click the "Play" button on bottom-right corner:
![image](https://user-images.githubusercontent.com/2306637/108505493-74abcb80-72f2-11eb-99b1-0e44ff57ffca.png)

You will see the mini-player window:
![image](https://user-images.githubusercontent.com/2306637/108505543-87be9b80-72f2-11eb-9dad-e81215602aec.png)

Is this what you want?

**Comment by paddatrapper** [comment]
It is possible to enable this by default or through the config? I'm working on using Botamusique to work as the playout system for a distributed radio station with DJs presenting over mumble. Being able to enable this for all users without them needing to click a button prevents mistakes while on air

**Comment by TerryGeng** [comment]
Okay... will see what I can do.

**Comment by paddatrapper** [comment]
Thanks!
