### ISSUE TITLE
Use multiple bots

### ISSUE THREAD

**Issue by Alterak** [azlux/botamusique#260]
Hey! Tell me how to make multiple bots?
At the moment I have made 2 services that use 2 different nicknames to enter the Mumble program, it all works, but only one bot plays music ... How do I get the second bot to play? Or is there another way to use multiple bots?

```
Unit]
Description=MusicBot1

[Service]
ExecStart=/home/alterak/botamusique/venv/bin/python /home/alterak/botamusique/mumbleBot.py -s 192.168.2.32 -u MusicBot1 -c Гостевая
Restart=always
Type=simple
RestartSec=10s
WorkingDirectory=/home/alterak/botamusique

[Install]
WantedBy=multi-user.target
```

```
Unit]
Description=MusicBot2

[Service]
ExecStart=/home/alterak/botamusique/venv/bin/python /home/alterak/botamusique/mumbleBot.py -s 192.168.2.32 -u MusicBot2 -c Гостевая
Restart=always
Type=simple
RestartSec=10s
WorkingDirectory=/home/alterak/botamusique

[Install]
WantedBy=multi-user.target
```

**Comment by azlux** [comment]
Hi,
Having two bot should work out of the box.
For better use, you need to share the same music database file (`--music-db` parameter), but not the same config database file  (`--db` parameter)
Run the bot in verbose mode, you should have error if the second bot still not working?.

Azlux

**Comment by Alterak** [comment]
> For better use, you need to share the same music database file (`--music-db` parameter), but not the same config database file (`--db` parameter)

But I want each bot to play different music, so it's right if they use different bases ... But I don’t know how to manage them- (

**Comment by azlux** [comment]
On my personnal server, I use two bot, two services like you, and I'm sharing the music db to make the local music folder working.

**Comment by TerryGeng** [comment]
> it all works, but only one bot plays music

Hi! As @azlux has said, multiple bot instances should work out of the box. I'm confused by you saying only one bot plays the music. What happens if you want to command one bot to play when the other one is playing? Does it ignore your command?

Or you actually mean that you want two bots to play in sync?

**Comment by Alterak** [comment]
> I'm confused by you saying only one bot plays the music. What happens if you command one bot to play when the other one is playing?

If you make 2 services as I wrote, then by default 2 bases of settings are created in the folder with the bot, but both bots use only one base of music. Everything seems to be correct. If you specify authorization by token in the main configuration file, then both bots start and play, but in this case there is a big drawback - in the Mumble program I cannot register these bots and cannot assign them to a group with the necessary rights.

And if I use a certificate, I can only use one certificate. In this case, the second bot cannot be launched.

I want that several bots can be launched with their own certificates and that different settings, different volumes, different rooms, different music are available for each bot.

**Comment by TerryGeng** [comment]
> but in this case there is a big drawback - in the Mumble program I cannot register these bots and cannot assign them to a group with the necessary rights.

Please create two configuration files for each of the two bots, and specify different certificates in the configuration file:
```
[server]
certificate = xxxxx.pem
```

> different music are available for each bot.

Please set different music database paths and music folders in the configuration files:
```
[bot]
music_database_path=xxxxx.db
```

For further questions, I would refer you to the README file first. Hope this information help.

**Comment by Alterak** [comment]
> Please create **two configuration files** for each of the two bots, and specify different certificates in the configuration file:

Are you sure you can do this? Can I just make a copy of the configuration.ini file and specify different certificates there?
How then can I correctly specify the config file in the service settings?
`ExecStart=/home/alterak/botamusique/venv/bin/python /home/alterak/botamusique/mumbleBot.py -s 192.168.2.32 -u MusicBot1 -c Гостевая`

But I will not be able to manage different bots from the web interface?

**Comment by TerryGeng** [comment]
> Are you sure you can do this?

https://github.com/azlux/botamusique#run-the-bot

> If you have set up everything in your `configuration.ini`, you can
> `venv/bin/python mumbleBot.py --config configuration.ini`

**Comment by Alterak** [comment]
I made 2 configuration files and specified different certificates in them, as well as different ports for the web interface

`ExecStart=/home/alterak/botamusique/venv/bin/python /home/alterak/botamusique/mumbleBot.py -s 192.168.2.32 -u musicbot1 -c Боты --config config-musicbot1.ini`

`ExecStart=/home/alterak/botamusique/venv/bin/python /home/alterak/botamusique/mumbleBot.py -s 192.168.2.32 -u musicbot1 -c Боты --config config-musicbot2.ini`

And it really works! Now everything is cool! Thanks for the help.

**Comment by TerryGeng** [comment]
Good to know it. Have a nice day :)
