### ISSUE TITLE
Unable to query youtube

### ISSUE THREAD

**Issue by dadidji** [azlux/botamusique#263]
**Describe the bug**
This bug has been mentioned [#261](https://github.com/azlux/botamusique/issues/261).
!url downloads and works just fine, the problem is when it tries to query youtube with !yplay or !ysearch.

**Affected version**
I'm using the testing version which has the latest git commit.

**To Reproduce**
1. Launch botamusique
2. Try to use !yplay or !ysearch
3. See error "Unable to query youtube!"

**Expected behavior**
The search is supposed to go through and then download the song and play it.

**Bot output (with the -v option enabled)**
`[2021-04-20 20:44:47,246] > [Thread-2] > [mumbleBot.py:263] bot: received command yplay - botamusique by didjiOnLinux`
`[2021-04-20 20:44:47,703] > [Thread-2] > [util.py:328] util: can not interpret youtube search web page`

**Screenshots**
![untitled](https://user-images.githubusercontent.com/81387591/115456748-0c566900-a213-11eb-9428-776be77bc494.jpg)

**Desktop (please complete the following information):**
 - OS: Debian 10.9
 - version 7.2-30-gb7232b8

EDIT: As I suspected the issue is related to the new consent page you get when visiting youtube on EU countries, that's why [#261](https://github.com/azlux/botamusique/issues/261) also had the same problem. It's the same thing that affected youtube-dl on April 1st.

I've changed _youtube_search(query)_ in **util.py** so that it prints the response it is actually getting.

```
r = requests.get("https://www.youtube.com/results", params={'search_query': query}, timeout=5)
print (r.text)
```

And this is the [output](https://bin.privacytools.io/?33afbfff482c22bf#89Cg9J6PreXrrxXKnTTsV1QpY88fF3bYkzNdbVZa9eZs)

**Comment by SlimGary** [comment]
Wow, I had this bug until today, I just tried it and it's working again. I did not even pull a newer version

**Comment by azlux** [comment]
Did you run `!update` to the bot to update youtube-dl lib ?

**Comment by dadidji** [comment]
> Wow, I had this bug until today, I just tried it and it's working again. I did not even pull a newer version

Just tested it, still not working for me. Tested both on stable and latest git version.

> Did you run `!update` to the bot to update youtube-dl lib ?

Yes, I'm running the latest youtube-dl version. If it was a youtube-dl problem I'm guessing the !url command also wouldn't work.

**Comment by dadidji** [comment]
Yeah, so after adding my consent cookie to my requests everything works as expected.
If anyone else is still having this issue just get your CONSENT cookie (open youtube on your browser and press F12) and add the following line before you make get requests in **util.py**. It should look something like 'YES+(...)'.

In youtube_search() method add this line after the first try
`cookies = {'CONSENT': 'paste your cookie in here'}`

Now add that parameter to the get request
`r = requests.get("https://www.youtube.com/results", cookies=cookies, params={'search_query': query}, timeout=5)`

**Comment by TerryGeng** [comment]
@dadidji Thanks for your investigation. I think I will add a config option to allow users to define a cookie to query youtube.

**Comment by azlux** [comment]
Youtube change rules every morning. This start to get me angry.
Look like they have created a domain to avoid the "consent" cookie for bot.
youtube-nocookie.com

**Comment by TerryGeng** [comment]
@azlux I can access that page because the certificate of youtube-nocookie.com is not valid and HSTS is enabled.

**Comment by TerryGeng** [comment]
@dadidji would see if the newly added configuration option `youtube_query_cookit` works?

**Comment by dadidji** [comment]
@TerryGeng 

> @dadidji would see if the newly added configuration option `youtube_query_cookie` works?

I will test as soon as possible.

Meanwhile I was thinking about invidious instances. Like [this](https://invidious.snopyta.org) one, I haven't tested but I think searching there wouldn't require a cookie, don't know what it would return and if the current query method can handle it but it might be worth investigating.

**Comment by TerryGeng** [comment]
@dadidji Thanks for the PR.

You asked why other websites can query youtube without encountering an error message.

From what I have known, if we register as a 3rd party developer, we can get an API key and use the official youtube API to query info from it.

However, this means we need to include our key in all distributions in plaintext, which is fairly dangerous others can abuse our key to send malicious requests to youtube.

We can always require everyone who uses the youtube query function themselves to apply for an API key from youtube, but I'm not sure people would like that.

Directly parsing youtube's search result is not a good way. But I don't have other choices.

**Comment by dadidji** [comment]
@TerryGeng Happy to help.

> However, this means we need to include our key in all distributions in plaintext, which is fairly dangerous others can abuse our key to send malicious requests to youtube.

I understand how that might be an issue.

> We can always require everyone who uses the youtube query function themselves to apply for an API key from youtube, but I'm not sure people would like that.

I agree, I wouldn't want to have to go through that trouble myself as I don't even use a youtube account.

> Directly parsing youtube's search result is not a good way. But I don't have other choices.

I meant maybe parsing it from one of those invidious instances, probably not a good idea in terms of stability since they do give errors every now and then. The current method is fine by me, it's fast enough and it should be easily implemented by anyone that's willing to just copy and paste a cookie.

Anyway, feel free to close the issue. Have a nice weekend :)
