### ISSUE TITLE
mode: Command failed with error: NameError: name 'media' is not defined.

### ISSUE THREAD

**Issue by piegamesde** [azlux/botamusique#267]
**Describe the bug**
The `!mode` command fails for me: `mode: Command failed with error: NameError: name 'media' is not defined.`

**Affected version**
[`df38c7d`](https://github.com/azlux/botamusique/commit/df38c7dbd6d59c6790cf2364d1f344b7f6f72107)

**To Reproduce**
1. `!mode repeat`

```
[May 11 01:03:49 ERROR] bot: command mode failed with error: Traceback (most recent call last):
  File "/nix/store/slcm3hnfpv03pyvvqd7rrci1imp52vvm-botamusique-unstable-2021-03-13/share/botamusique/.mumbleBot.py-wrapped", line 321, in message_received
    self.cmd_handle[command_exc]['handle'](self, user, text, command_exc, parameter)
  File "/nix/store/slcm3hnfpv03pyvvqd7rrci1imp52vvm-botamusique-unstable-2021-03-13/share/botamusique/command.py", line 891, in cmd_mode
    var.playlist = media.playlist.get_playlist(parameter, var.playlist)
```

**Comment by TerryGeng** [comment]
Can you try the latest commit? IIRC this bug has been fixed but has not been released yet.

**Comment by mweinelt** [comment]
This is my bot, I will update it in a bit, thanks for the feedback!
