### ISSUE TITLE
URLs parsed from user input are HTML escaped

### ISSUE THREAD

**Issue by mweinelt** [azlux/botamusique#274]
**Describe the bug**
Trying to add a playlist url like `https://www.youtube.com/watch?v=rl_ndy61ON4&list=PLBotQZ6u3kciAUtzpqyZETJ_loczWF9kb` should work, but the URL currently gets HTML escaped.

**Affected version**
https://github.com/azlux/botamusique/commit/f9cc9c78722db8b16375ff34ed097cb70025bb47

**To Reproduce**
1. Try to add a playlist that uses an url with multiple GET parameters
2. `!playlist https://www.youtube.com/watch?v=rl_ndy61ON4&list=PLBotQZ6u3kciAUtzpqyZETJ_loczWF9kb`
3. Notice the bot replies with `Unable to fetch the playlist!`
4. Check the url that the bot sees in the log

```diff
-https://www.youtube.com/watch?v=rl_ndy61ON4&list=PLBotQZ6u3kciAUtzpqyZETJ_loczWF9kb
+https://www.youtube.com/watch?v=rl_ndy61ON4&amp;list=PLBotQZ6u3kciAUtzpqyZETJ_loczWF9kb
```

**Expected behavior**
The URL should be properly unescaped before getting passed on.

**Additional context**
```
May 16 04:21:29 juno botamusique[8720]: [2021-05-16 04:21:29,479] > [Thread-6] > [.mumbleBot.py-wrapped:264] bot: received command "playlist" with arguments "https://www.youtube.com/watch?v=rl_ndy61ON4&amp;list=PLBotQZ6u3kciAUtzpqyZETJ_loczWF9kb" from hexa-
May 16 04:21:29 juno botamusique[8720]: [2021-05-16 04:21:29,492] > [Thread-6] > [command.py:418] cmd: fetching media info from playlist url https://www.youtube.com/watch?v=rl_ndy61ON4&amp;list=PLBotQZ6u3kciAUtzpqyZETJ_loczWF9kb
```

**Comment by TerryGeng** [comment]
I think this is an issue of Mumble. Please fill an issue at https://github.com/mumble-voip/mumble.

**Comment by mweinelt** [comment]
Except `get_url_from_input` clearly claims to parse URLs from HTML

https://github.com/azlux/botamusique/blob/f9cc9c78722db8b16375ff34ed097cb70025bb47/util.py#L300-L305

**Comment by TerryGeng** [comment]
No it doesn't, for sure.

**Comment by mweinelt** [comment]
In the linked code block it applies `re.search` to find a `href` attribute of an `a` tag, so I'm very confident that the input is HTML.

Anyway, I provided a fix in #275 and verified it works.

**Comment by TerryGeng** [comment]
I mean, Mumble will automatically covert a link to HTML. Apparently, URL inside `href` should not be escaped anyway.

**Comment by mweinelt** [comment]
Oh, that might be true. The function doesn't say anything about the remaining user input, whether it is plain text, escaped or unescaped html.

**Comment by mweinelt** [comment]
For the record, this is what the raw message looks like:

```
"!playlist <a href=\"https://www.youtube.com/watch?v=rl_ndy61ON4&amp;list=PLBotQZ6u3kciAUtzpqyZETJ_loczWF9kb\">https://www.youtube.com/watch?v=rl_ndy61ON4&amp;list=PLBotQZ6u3kciAUtzpqyZETJ_loczWF9kb</a>"
```

**Comment by Krzmbrzl** [comment]
I confirm that this is an issue on Mumble's side. I have just created a fix for it: https://github.com/mumble-voip/mumble/pull/5000
