### ISSUE TITLE
Radio URL breaks bot

### ISSUE THREAD

**Issue by Natenom** [azlux/botamusique#282]
**Describe the bug**
The url of my favorite radio breaks the bot completly.

**Affected version**
Current download from azlux.fr

**To Reproduce**
1. Start bot
2. !radio http://air.radiorecord.ru:8102/goa_320
3. Bot starts playing the radio station.
4. Write any command to the bot, it crashes.

See "Screenshots" for the log.

When restarting the bot, it again crashes when you send a command. If you start it with "-v", it crashes instantly. The log then looks like above.

Bot works after music.db was removed.

**Expected behavior**
Not crashing :)

**Screenshots**
![image](https://user-images.githubusercontent.com/385995/119588703-a93b9180-bdd1-11eb-9702-c796270507fc.png)

**Comment by TerryGeng** [comment]
The log redirect function breaks somehow. Would you set
```
[bot]
logfile= # leave this place empty
```
in your configuration to see if things are fixed?

**Comment by Natenom** [comment]
Nice, thank you :)

It works now.

**Comment by TerryGeng** [comment]
I'm not sure whether to label it as a bug. I'm also not sure how many users are experiencing it.

I have to admit the way we adapted to redirect stdout and strerr is too hacky. But according to your log, it looks more like our logger settings was overridden in the middle, but I have no idea what is wrong.

I would make a commit to disable this feature by default and add an config option to enable it.
