### ISSUE TITLE
Implement channel listener

### ISSUE THREAD

**Issue by Natenom** [azlux/botamusique#283]
**Is your feature request related to a problem? Please describe.**
When setting "when_nobody_in_channel" to "pause_resume" the bot stops playing when there is no user in the channel. But in the current git master branch of Mumble there is a feature called channel listener. Everyone can (if enabled on the mumble-server) listen to a channel. The current botamusique does not seem to see those listeners and stops playing music even if there are channel listeners.

**Describe the solution you'd like**
Let botamusique see those channel listeners and handle them as users in a channel. Disabling when_nobody_in_channel is not a solution because it comsumes traffic on the server when there is nobody listening.

**Aditional ...**
If you need a test server you may use my server where this feature is enabled. :)

**Comment by TerryGeng** [comment]
I'm aware of this new feature of Mumble. It is set to be released with Mumble 1.4.0. There will be substantial protocol updates in Mumble 1.4.0 and channel listener is one of them, together with stereo sound and perhaps new encryption methods.

Our bot uses a library called [pymumble](https://github.com/azlux/pymumble) (which is also currently maintained by @azlux) to communicate with Mumble. Supporting all new protocol features in 1.4.0 requires some works on pymumble.

I would suggest you open a new issue on pymumble, asking for the channel listener features. I will see what I can do to get it implemented later.
