### ISSUE TITLE
Not a bug I think, but having ssl connection issues.

### ISSUE THREAD

**Issue by andrewschott** [azlux/botamusique#286]
So both a git pull version and the official docker version both fail connecting to my server.  My server is using a Lets Encrypt cert to enable SSL.  Server is Centos 7, client is a local server actually, running RHEL 8.4.

The logs on my server show the following:

```
(-1)> Connection closed: Error during SSL handshake: error:1408F10B:SSL routines:SSL3_GET_RECORD:wrong version number [13]
```

On my client (the bot system)
```
[Jun 13 11:41:41 INFO] library: rebuild directory cache
[Jun 13 11:41:42 INFO] bot: botamusique version 7.2-52-gba02cde, starting...
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib64/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/home/andrew/.local/lib/python3.6/site-packages/pymumble_py3/mumble.py", line 128, in run
    raise ConnectionRejectedError("Connection error with the Mumble (murmur) Server")
pymumble_py3.errors.ConnectionRejectedError: 'Connection error with the Mumble (murmur) Server'
```

Any ideas on my gaffe?

**Comment by azlux** [comment]
Hi,
Can you check this ticket ? https://github.com/azlux/pymumble/issues/110
Look like your mumble-server is too old.

Best regards
Azlux

**Comment by andrewschott** [comment]
That was indeed the issue.  I used a podman container to get the latest build.  So I shall also thank you for forcing me into doing what I have been planning on doing for a few years now -- start containerizing all my crap on that server.  So I have this and mumo now running happily containeriized :D

Thanks again!  Love the bot sofar!
