### ISSUE TITLE
Cannot login via web interface

### ISSUE THREAD

**Issue by andrewschott** [azlux/botamusique#287]
**Describe the bug**
I am incapable of logging in

**Affected version**
both the latest and testing docker containers

**To Reproduce**

Here is my configuration.ini that I passed into the container.

```
[webinterface]
enabled = true
listening_addr = 0.0.0.0
listening_port = 8181
auth_method = password
username = AnyUserName
password = SomePassword
web_logfile = /config/web_log
is_web_proxified = false
```

My podman launch script (note the :Z is for selinux, in case you were unaware):

```
#!/bin/bash

podman run --name=botamusique -ti -d --rm \
        -e BAM_MUSIC_DB=/config/music_db \
        -e BAM_DB=/config/db \
        -e BAM_CONFIG_file=/config/configuration.ini \
        -p 8181:8181/tcp -p 8181:8181/udp \
        -v /opt/docker/botamusique/music/:/music:Z \
        -v /opt/docker/botamusique/config:/config:Z  \
        azlux/botamusique
```

**Expected behavior**
Was hoping to get to the WebUI

**Desktop (please complete the following information):**
 - Server OS: CentOS Linux release 7.9.2009 (Core) + podman
 - Client OS's: [Fedora 33 x86_64, RHEL 8.4 Workstation x86_64]
 - Browser [Firefox]
 - Version [firefox-89.0-1.fc33.x86_64, firefox-78.11.0-3.el8_4.x86_64]

**Additional context**
So I try to login, I get what appears to be the generic Apache login dialog box (could be wrong, never intentionally used nginx or other alternatives).  I enter the information in and either hit enter or OK, and it reappears.  It was a failed login.  Per the logs, am not able to login.  Using the bot to create a user, this is also the case.  In case it is not clear, although I could setup Apache to proxy this, I have not (yet).  Wanted to make sure all was good first before adding that into the mix.

If I disable authentication things do indeed work.  I haven't bothered as of yet with trying a token based approach, but I prefer not to have to deal with others other than the few I wish to muck with things to mess with things, hence the user approach looked interesting.   I have other ways of locking it down if need be, but this would be a better approach than those from an effort/reward point of view.

Thanks much!
Andrew.

**Comment by TerryGeng** [comment]
Are you using Apache to proxy the request?

I think both @azlux and I use Nginx and things work fine. Would you try using the `http://127.0.0.1:8181` to connect directly and see if the password login works?

**Comment by andrewschott** [comment]
No, I am not proxying as of now.

**Comment by TerryGeng** [comment]
If there's no more update about this issue, I will close it.
