### ISSUE TITLE
Custom ffmpeg options

### ISSUE THREAD

**Issue by 3291823** [azlux/botamusique#288]
I've been using botamusique for a minute & I have noticed that the audio usually comes out sounding tinny or small, with no lower frequencies. I'm sure this is a result of converting to opus/mumble audio protocol. 
I'd like the ability to add a custom ffmpeg option, such as a low pass filter, or whatever else I desire. 
I'm not sure about other alternatives, mumble does not have any built in equalizer function yet. 
TIA.

**Comment by 3291823** [comment]
The volume is not the issue. I set it with !v.
Listening to source material & what comes out thru botamusique is very different.

**Comment by TerryGeng** [comment]
Hi. Thanks for your reply.

I'm still confused by your original post saying you are experiencing tiny volume. Have you succeeded in making the bot sound louder?

As far as I've known, Opus has done a very decent job in compressing the audio material. I have been using botamusique for more than a year and haven't encountered any significant loss of fidelity.

A possibility is the server you are connecting to has enforced a rather low bitrate and that made the loss sounds pretty bad.

Could you try to connect to different servers and play different kinds of music files to see if this problem persists?

**Comment by azlux** [comment]
Hi,
The ffmpeg command is hard coded here : https://github.com/azlux/botamusique/blob/6faadd6669aa27f1c65bf7327f2b2eccf6b15255/mumbleBot.py#L398
This command look like : 
```
ffmpeg -v ffmpeg_debug -nostdin -i uri -ss f"{start_from:f} -ac str(channels) -f 's16le' -ar 48000 - 
```
If you really think that a ffmpeg issue you have, you can customize this command for testing purpose.

**Comment by 3291823** [comment]
Thanks.

**Comment by 3291823** [comment]
If anybody else is wondering, I was able to add a little bit of bass with the following.
```
   command = ("ffmpeg", '-v', ffmpeg_debug, '-nostdin', '-i',
                uri, '-ss', f"{start_from:f}", '-af', 'equalizer=f=40:width_type=h:width=50:g=7', '-ac', str(channels), '-f', 's16le', '-ar', '48000', '-')
```

**Comment by paperbenni** [comment]
Is this an issue with the codec/mumble or the bot? I have noticed this on my server as well, the music has noticeably less bass as if the codec settings were optimized for voice only at the cost of other sounds sounding bad. Discord which also uses the opus codec sounds a lot better when using a music bot. Maybe the music bot has adjusted settings to balance out the weird sound, but I'd definitely love to see this fixed

**Comment by TerryGeng** [comment]
@paperbenni Are you using Mumble 1.3.x?

**Comment by paperbenni** [comment]
yes

**Comment by TerryGeng** [comment]
I believe the problem is, not sure if you have noticed or not, that 1.3.x doesn't support stereo audio. Everything comes out in mono. You lost a huge amount of bass and other things during the converting process.

The RCs of 1.4.0 have been released on Mumble's site, which support stereo audio. I suggest you use that in order to get the best experience.

**Comment by paperbenni** [comment]
Do both the client and the server need mumble 1.4?

**Comment by TerryGeng** [comment]
Only clients.

**Comment by paperbenni** [comment]
Do only.the clients need mumble 1.4 or are there only client builds for Linux?

**Comment by TerryGeng** [comment]
![image](https://user-images.githubusercontent.com/2306637/144273456-de39cc7d-7499-486d-89d1-32dc4373027a.png)

**Comment by paperbenni** [comment]
I tried the mumble client 1.4 and it sounds pretty much like the original sound file. I wildly underestimated how much of an impact stereo makes, my apologies for not checking before. The bass levels are fine, it just sounds a lot more tinny in mono. 
Thanks for your help :)
