### ISSUE TITLE
Unpriveleged users have delete permissions

### ISSUE THREAD

**Issue by Window-Hero** [azlux/botamusique#293]
**Is your feature request related to a problem? Please describe.**
Everyone with access to the web interface of the music bot has the ability to permanently delete files from the music library on the server.

**Describe the solution you'd like**
Ideally, a more robust permissions system in general.

**Describe alternatives you've considered**
Simply making it so only users with the existing administrator permission can delete files, similarly to how this restriction is applied to commands.

*Edit
Actually, I've just realized this may be partly a bug, since there is a setting, delete_allowed, however this seems to eb ignored, because even with it set to false, all users can still delete files.

**Comment by TerryGeng** [comment]
Yes... `allowed_delete` doesn't work for command by now. I will post a quick fix later.

And also, to your feature request, I think it makes sense to allow administrators to delete files while forbidding others to do so. I will also work out a patch to implement it.
