### ISSUE TITLE
extend() debug text printed in normal verbosity

### ISSUE THREAD

**Issue by parnikkapore** [azlux/botamusique#294]
**Describe the bug**
The following messages are printed on the console. I have not changed the bot's verbosity setting.
```
extend to-enter
extend enter
extend leave
extend to-enter
extend enter
extend leave
extend to-enter
extend enter
extend leave
[...]
```
**Affected version**
Release v7.2.1

**To Reproduce**
1. Run the bot in autoplay mode, with music in your library
2. The messages above should appear

**Expected behavior**
These messages should not be printed unless verbose logging is requested (if that's even a thing)

**Additional context**
It looks like someone was doing printf debugging and forgot to remove the print() calls. See [line 90 of media/playlist.py](https://github.com/azlux/botamusique/blob/master/media/playlist.py#L90)

**Comment by TerryGeng** [comment]
I looked into the commit history to see who is the culprit and then discovered it's me...

Anyway, thanks for pointing that out. Merged.
