### ISSUE TITLE
Replace youtube-dl with yt-dlp

### ISSUE THREAD

**Issue by dadidji** [azlux/botamusique#296]
Hello there!

**Is your feature request related to a problem? Please describe.**
I'm suggesting switching to a fork of youtube-dl that gets regular updates. The original youtube-dl project hasn't seen any activity in like 4 months and the devs don't seem too keen about fixing known bugs. The main problem I have with the current version of youtube-dl (2021.6.6) is the bug that slows down the download speed (50-70 kB/s).

**Describe the solution you'd like**
I'm not sure if it's too complicated but I think [this fork](https://github.com/yt-dlp/yt-dlp) of youtube-dl is the best solution because it has tons of cool features and is being actively developed unlike the original youtube-dl project which does not get any updates.

**Additional context**
They have a [pip package](https://pypi.org/project/yt-dlp/) for it as well so I'm assuming keeping it up to date wouldn't be a problem.

Anyway this is just a suggestion, I'm gonna try to implement it on my local machine when I have the time. Let me know your thoughts on this.

**Comment by 5trongthany** [comment]
I second this idea. youtube-dl is alright but considering that development is on hiatus for the foreseable future, I can see less and less services being supported by it, whereas yt-dlp has the development behind it to ensure that sites will be supported.

**Comment by TerryGeng** [comment]
To be honest, I'm very keen on using Youtube, and am not very familiar with the situation of youtube-dl. @azlux What do you think? It seems that yt-dlp has a lot of stars so I assume people do like it?

For me, as long as the interface doesn't change, we can switch to it at any time.

**Comment by elch01** [comment]
yt-dlp is serious bloat, i would suggest using pytube and ffmpeg.

**Comment by azlux** [comment]
I think we can use youtube-dlp without difficulties because it's a fork. The lib should be easy to adapt.

About pytube, this will limit the number of website available.

**Comment by Window-Hero** [comment]
I suspect youtube-dlp is going to get merged into youtube-dl at some point, youtube-dl only hasn't been updated yet because the developer is in the process of moving, but if youtube-dlp works in the meantime, anything to fix the slow.
