### ISSUE TITLE
user_changed resumes when number of users in channel falls from 3 to 2

### ISSUE THREAD

**Issue by mweinelt** [azlux/botamusique#298]
**Describe the bug**
The `user_changed` method unexpectedly resumes playback when the bot is stopped, three users are in a room, and one user leaves the room, so that only two users are left.

**Affected version**
v7.2.2-yt-dlp

**To Reproduce**
1. Set `when_nobody_in_channel = "pause_resume"`
2. Have three people in a room
3. Issue `!stop`
4. Have one person leave the room

**Expected behavior**
Music should only start playing when we go from one user (only botamusique) to two (botamusique + one user), which reflects a rising edge.

**Additional context**
This would require keeping the previous user count somewhere accessible.

**Comment by piegamesde** [comment]
The relevant code is in [`users_changed`](https://github.com/azlux/botamusique/blob/master/mumbleBot.py#L357-L374). Splitting this into a `user_joined_channel` and a `user_left_channel` callback should significantly improve things. I furthermore propose this new, improved semantic:

```
# Configuration options
when_users_leave_channel = ['pause', 'stop', 'stop_clear', 'nothing']
when_users_enter_channel = ['resume', 'nothing']

# State machine
- State=Play
    - User enters channel => Nothing
    - Users leave channel => Pause or Stop or Nothing
- State=Pause
    - User enters channel => Play
    - Users leave channel => Optionally stop/clear playlist
- State=Stop
    - User enters channel => Resume or Nothing
    - Users leave channel => Optionally clear playlist
```

**Comment by TerryGeng** [comment]
I proposed a fix. Can you guys help me test it?
