### ISSUE TITLE
Freshly installed from source or package still update message

### ISSUE THREAD

**Issue by TheWrongGuy** [azlux/botamusique#302]
I always get the update available message in Mumble even with a freshly installed bot only with a previous configuration.ini.

Is this normal?

Update Available!
Version 7.2.2 of botamusique is available! 

Changelog
Hi all, I push a new release to allow everyone to have a working bot with youtube. We have temporary replaced youtube-dl with yt-dlp.

Have a good day Azlux

Send !update to update!

**Comment by azlux** [comment]
This is a mistake of the last update I've done. Sorry for that. I will fix it tomorrow.

**Comment by TheWrongGuy** [comment]
Thank you! :)

**Comment by azlux** [comment]
quick question, what's your version in line 35 ? https://github.com/azlux/botamusique/blob/c624c327c3e50a36cfff47f362d6aa836325a887/mumbleBot.py#L35
And your target_version on the config file ? 

I just checked, and I don't think I've forgot something in the previous release.

**Comment by TerryGeng** [comment]
Any updates? Otherwise, I shall close this issue for now.

**Comment by TheWrongGuy** [comment]
Sorry for the late response! I missed the first response from azlux. My version in line 35 is also 'git'. Where to see the target version? In configuration.example.ini it states target_version = stable. 

I obtained the version from Github. The prepacked package I didn't git clone it
