### ISSUE TITLE
Changing page on web interface reset search results to whole library

### ISSUE THREAD

**Issue by aanze** [azlux/botamusique#305]
Say you want to add a full album to the playlist from the wbe interface:

1. Browse album folder from Directory combobox (with tracklist more than 1 page)
2. Click on page 2 in tracklist results
=> tracks are reset to full library hence the impossibility to select all the tracks of the album

Bonus:  clicking on "add all" will add the entire library and not the current search results

**Comment by TerryGeng** [comment]
This happens to be a bug. I will figure out a fix later.

**Comment by aanze** [comment]
Great !
Thanks for your work anyway, awesome project :)

Le mar. 11 janv. 2022 à 15:54, Terry Geng ***@***.***> a
écrit :

**Comment by TerryGeng** [comment]
Should be fixed now. Thanks for catching this long-living bug :).

**Comment by aanze** [comment]
Great ! Thanks ! Will the project autoupdate ? I'm running the beta branch

**Comment by TerryGeng** [comment]
Yes, auto-update for the testing version should work.
