### ISSUE TITLE
Can't change play mode from web interface

### ISSUE THREAD

**Issue by aanze** [azlux/botamusique#307]
**Describe the bug**
Can't change play mode from web interface

**To Reproduce**
Set play mode to "one shot" in configuration file
Run botamusique
Connect to web interface
Try to change play mode to any other value: combo box selected item never updates

**Comment by TerryGeng** [comment]
I tried to reproduce this bug. It seems to me that I can switch freely among one-shot, autoplay, and repeat mode. The random mode seems to be a little be unresponsive. Is this what you have found? I'm going to fix it very soon.

**Comment by aanze** [comment]
You are indeed right, the other mode seem work, only random cannot be selected at all:
[record of my screen here](https://watch.screencastify.com/v/12XiigX3vf9soEihYPOr)

**Comment by TerryGeng** [comment]
Fixed.

**Comment by aanze** [comment]
so fast ! ty
