### ISSUE TITLE
Pull from Youtube music was a compilation and filled up /tmp

### ISSUE THREAD

**Issue by Glowsome** [azlux/botamusique#31]
**Is your feature request related to a problem? Please describe.**
problem: user of the bot requested a 'compilation' - 2 hour compilation filing up /tmp completely

**Describe the solution you'd like**
- a way to avoid /tmp to fill up when someone requests a file that would fill/overflow filesystem

**Describe alternatives you've considered**
A limit on filesize of a youtube file would be nice if possible. 

**Additional context**
as i am runnig multiple instances i need a way to avoid filling up /tmp completely

**Comment by azlux** [comment]
Until I finish the code, you can check the branch : https://github.com/azlux/botamusique/tree/dev (the web interface isn't functional)
