### ISSUE TITLE
An error occurred in the database during installation

### ISSUE THREAD

**Issue by mmdexb** [azlux/botamusique#312]
An error occurred in the database during installation，This is what the terminal told me

```
Traceback (most recent call last):
  File "mumbleBot.py", line 837, in <module>
    DatabaseMigration(var.db, var.music_db).migrate()
  File "/www/wwwroot/audio.xnatc.ink/botamusique/database.py", line 513, in migrate
    self.settings_database_migrate()
  File "/www/wwwroot/audio.xnatc.ink/botamusique/database.py", line 517, in settings_database_migrate
    conn = sqlite3.connect(self.settings_db.db_path)
sqlite3.OperationalError: unable to open database file


```

**Comment by TerryGeng** [comment]
The error message says it all. Are you sure you have the write access to that path of db file?

**Comment by mmdexb** [comment]
> d
You mean the  “database.py“  ？
I have got the access

**Comment by mmdexb** [comment]
> The error message says it all. Are you sure you have the write access to that path of db file?


You mean the “database.py“ ？
I have got the access

**Comment by mmdexb** [comment]
> No. I mean the path to the db file in your configuration.ini. Namely, these two lines:
> 
> https://github.com/azlux/botamusique/blob/508811cd2a62f60ccfe867f019ff7923af4fe2cf/configuration.example.ini#L40-L41

OK，I will have a check

**Comment by TerryGeng** [comment]
If you didn't change them, then please make sure the user who runs the bot has the write access to the folder of the bot.

It seems that you are running the bot inside wwwroot. I assume you copied the bot with `sudo`. I'm rather sure that you don't have the write access to it usually.

**Comment by mmdexb** [comment]
> If you didn't change them, then please make sure the user who runs the bot has the write access to the folder of the bot.
> 
> It seems that you are running the bot inside wwwroot. I assume you copied the bot with `sudo`. I'm rather sure that you don't have the write access to it usually.

After that ,I got This

`Jan 22 00:00:56 INFO] database: no settings table found. Creating settings table version 2.
[Jan 22 00:00:56 INFO] database: no music table found. Creating music table version 4.
[Jan 22 00:00:56 INFO] library: rebuild directory cache
[Jan 22 00:00:56 INFO] bot: botamusique version 7.2.2, starting...
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/home/musicbot/botamusique/venv/lib/python3.8/site-packages/pymumble_py3/mumble.py", line 134, in run
    self.loop()
  File "/home/musicbot/botamusique/venv/lib/python3.8/site-packages/pymumble_py3/mumble.py", line 219, in loop
    self.read_control_messages()
  File "/home/musicbot/botamusique/venv/lib/python3.8/site-packages/pymumble_py3/mumble.py", line 293, in read_control_messages
    self.dispatch_control_message(type, message)
  File "/home/musicbot/botamusique/venv/lib/python3.8/site-packages/pymumble_py3/mumble.py", line 323, in dispatch_control_message
    raise ConnectionRejectedError(mess.reason)
pymumble_py3.errors.ConnectionRejectedError: 'Invalid username'`


Thank for your help!!!!!!!!!!

**Comment by TerryGeng** [comment]
`pymumble_py3.errors.ConnectionRejectedError: 'Invalid username'`

Are you using some strange username? Like having special characters or spaces in the username? Can you try something as simple as `bot`?

And, the issue space is not supposed to be we holding your hands and teaching you how to run the bot.

Would you join the Matrix channel of Mumble https://app.element.io/#/room/#mumble:matrix.org? That would be a better place to chat.
