### ISSUE TITLE
!version does not display the specific commit id

### ISSUE THREAD

**Issue by hamilton5** [azlux/botamusique#313]
!version should tell you the buildid, or the specific version you are after in this bugreport template. I used the zip dev version.

> If you are using the tarball or zip file downloaded from Github, I'm sure it can display the last commit ID in its version, but you must have Git installed otherwise the bot cannot fetch the commit ID.

I have git installed - git version 2.30.2 but I specifically downloaded from from the link in the quickstart: http://packages.azlux.fr/botamusique/ not github

> Oh, it seems that @azlux drops the .git/ folder in packing the development snapshot. This is something we can fix. Can you start a new issue about this?

Done.

**Comment by TerryGeng** [comment]
Nope... I do see @azlux properly replacing the version number in the tar file.

https://github.com/azlux/botamusique/blob/a034d2a85d9cc9959522bb8802744f3e4299e3f7/.drone.yml#L36-L39

**Comment by TerryGeng** [comment]
What is the output you have seen when sending `!version`?

And, what is the version of line 35 of your `mumbleBot.py`?

**Comment by hamilton5** [comment]
The current version of botamusique is 7.2.2.

    version = '7.2.2'

**Comment by TerryGeng** [comment]
I'm afraid you are using the stable version. Would you check the value of `target_version` inside your `configuration.default.ini`?
