### ISSUE TITLE
thumbnails displayed only sometimes

### ISSUE THREAD

**Issue by hamilton5** [azlux/botamusique#314]
webp images don't load I only see jpg files.

> I don't understand you. I think we save PNG instead.

I have JPG and WEBP files only, of 38 files not 1 PNG, this is a picture of my /tmp folder
![150560803-94cd7650-68e1-4fb9-8c5c-459aeba52b90](https://user-images.githubusercontent.com/2685451/150564922-2c48ada1-6359-40bc-915d-c8731e7878ac.jpg)

> The bot stores pictures in its database (although we had discussions before and admitted this is a bad practice). I don't recall a place the bot save the pictures. Are you using the youtube-download feature? If that is the case, then these files were created by ytb-dl, and you can safely delete them.

I used !url and !playlist - If it is storing PNG files in a database that still does not explain why they are not displayed in the channel.

**Affected version**

7.2.2

**To Reproduce**

!url https://www.youtube.com/watch?v=zqNTltOGh5c
[11:38:56] (Channel) botamusique: Download of Miles Davis - So What (Official Video) in progress...
[11:39:00] (Channel) botamusique: Playing Miles Davis - So What (Official Video) added by MYNICKNAME

**Expected behavior**

All thumbnails should be displayed regardless of filetype. It will display a very tiny thumbnail when the file type is JPG. Can we have options to control the size, and even enable/disable thumbnails completely?

**Comment by TerryGeng** [comment]
Will investigate.

**Comment by azlux** [comment]
Should be fix on testing version, can you check ?

**Comment by hamilton5** [comment]
Yes, it seems fine at the moment. I tried 6 other URLs and had no problems, all jpg files. Playing files already on my playlist don't work. I tried the url from OP and it didn't load. I assume I'll have to wipe and start over to get them in the database?

**Comment by TerryGeng** [comment]
Just use `!delete` to delete them.

**Comment by hamilton5** [comment]
Ok I was using !rm .. so one wipes it from the database/tmp folder and the other is just cosmetic? How do I know what item(index) it is on the 'shortlist' (what is the shortlist even). It does not work like !rm I get 'invalid parameter.'

**Comment by TerryGeng** [comment]
`!rm` removes songs on the playlist. It doesn't affect the library.
You need to use `!delete` instead.

Please read through https://github.com/azlux/botamusique/wiki/Command-Help-and-Examples.

**Comment by TerryGeng** [comment]
You need to perform a query first. Can you `!search`?

**Comment by hamilton5** [comment]
when I !search it adds it to the playlist, I can't just list the library like I can the playlist(!q)? I have no idea how to get the 'index'

**Comment by TerryGeng** [comment]
... Yes I recall this is the expected behavior.

The deal is, people don't usually use the command system to manage the library. Instead, they use the web interface. The commands for managing the library were added after the web interface just to make it possible to at least do some tiny adjustments.

In this case, the command system indeed seems to be cumbersome. I suggest you use the web interface instead. Otherwise, just wipe all the database and start all over if you find it more comfortable.

**Comment by hamilton5** [comment]
Alright, thanks, I think it's solved. I started up the web interface and got it deleted, !url once more and the thumbnail did show.

I see a lot of duplicates in the library! maybe a command to export the library with indexes to text file? Having the urls backed up could be handy too.

**Comment by TerryGeng** [comment]
Good to know it is solved. Have a nice day!
