### ISSUE TITLE
apt slow

### ISSUE THREAD

**Issue by qq2211042368** [azlux/botamusique#322]
**Is your feature request related to a problem? Please describe.**
apt命令慢，我尝试换源会出现public key 问题

**Describe the solution you'd like**
请告诉该怎么做

**Comment by azlux** [comment]
This project don't have any APT repo.
Can you explain yourself ? What's the exact error you're facing ?

**Comment by TerryGeng** [comment]
APT is the package manager of Ubuntu/Debian. We are not the maintainer of APT, hence could not answer your question. Please refer to their maintainer for more details.
