### ISSUE TITLE
Option to add youtube downloads to the normal music library

### ISSUE THREAD

**Issue by karlpip** [azlux/botamusique#331]
**Is your feature request related to a problem? Please describe.**
While using botamusique mainly for playing single songs from YouTube, botamusique saves the files to temporary folder and they might get deleted. The problem is that the files to be downloaded and converted again if someone plays a YouTube video repeatedly.

**Describe the solution you'd like**
Implement an configurable option, to download YouTube music into the normal music library and add them as type `file` to the database. Make the YouTube functions search the local database first to avoid redundant downloads (this might be the case already).

**Describe alternatives you've considered**
Just setting the tmp folder to the same as the music folder leads to a crash while building the database. 

**Additional context**
If this feature request gets accepted in some way, I'm willing to implement it and open an pr as I've already wrote a hacky solution for this that i could improve.

**Comment by TerryGeng** [comment]
I think we have this feature in place.

You can change the download directory (the `tmp_folder`) by tweaking these lines in your configuration file:
https://github.com/azlux/botamusique/blob/0650e7279f5f777cbeda51b9b40fb4155c60d227/configuration.example.ini#L73-L79

Just set it to the folder you want and set the size limit to `-1`.

**Comment by karlpip** [comment]
Solved!!!
Thanks :)
