### ISSUE TITLE
Web Interface: POST request always return 400

### ISSUE THREAD

**Issue by dong628** [azlux/botamusique#339]
As long as I run the bot, it just keep printing the message "192.168.31.1 - - [05/Aug/2022 16:06:58] "POST /post HTTP/1.1" 400". 

![Screenshot_20220805_160501](https://user-images.githubusercontent.com/38680774/183033145-d2e51a27-d5d0-4d9d-8f25-6316c545c0ce.jpg)

Almost all of the operations in web interface **cannot** get a response immediately, unless reload the page or you cannot check the music which is playing now. The developer tools show that **every** post request have got 400 BAD REQUEST

![Screenshot_20220805_160424](https://user-images.githubusercontent.com/38680774/183034885-8a524c2d-2aff-43d4-85d8-5d16841882bf.jpg)

We cannot filter the music files through the folders, for we cannot choose the folder correctly, and I think it is related to this problem.

https://user-images.githubusercontent.com/38680774/183034286-0f869c12-63cb-46d4-8d49-35436724163e.mp4

I can give you my web interface permission if you can't reproduce the problem.

**Comment by TheNamelessWonderer** [comment]
Yep I get the same issue using testing.

**Comment by dong628** [comment]
After testing, 400 problem no longer exists when I use the Docker image. However, the folder-choosing problem in the video still exists.

**Comment by azlux** [comment]
I saw this issue, I need to rework on the code. Not a lot of time.

**Comment by dong628** [comment]
> Can you run the bot in verbose mode with `-v` and post the log?

[bot.log](https://github.com/azlux/botamusique/files/9291918/bot.log)

**Comment by MarioPL98** [comment]
Same issue here, running on Win Server 2019

**Comment by TerryGeng** [comment]
Ok I will have a look into it later today.
