### ISSUE TITLE
Songs with japanese file names do not show up in web interface.

### ISSUE THREAD

**Issue by MarioPL98** [azlux/botamusique#342]
**Describe the bug**
After adding .mp3 file that includes japanese characters, this file does not show up in web interface.

**Affected version**
7.2.2 (built from source)

**To Reproduce**
1. Upload a file with japanese characters.
2. Rescan files
3. Check that the file is not present.

**Expected behavior**
File visible and playable

**Desktop (please complete the following information):**
 - OS: Windows Server 2019 (bot), Windows 10 1.4.274 Mumble
 - Browser Firefox

**Comment by TerryGeng** [comment]
I have tons of mp3 with Japanese names. They worked fine. Can you check that your song has really been uploaded to the upload folder?

**Comment by MarioPL98** [comment]
Yes, The file was uploaded and visible in file explorer but not visible in web interface. Perhaps some encoding configuration issues? Keep in mind that I am using Windows Server 2019 for the bot, with NTFS filesystem as a storage drive.

**Comment by azlux** [comment]
Hi @MarioPL98 , can you check the xhr request into the Network tab of the dev tool of your browser (F12) ?
You should see the music name you're looking for (for exemple when you check the librairy).
Full name should appear here, if not, maybe the server don't send it.
![image](https://user-images.githubusercontent.com/11210117/211863129-2a2cc0b5-f164-4185-9990-3f061f68a61c.png)

**Comment by soloopooo** [comment]
I got this issue. Maybe because of the file name containes spacebar.

Rename the file to 0.mp3 or 1.mp3 fixes that.
