### ISSUE TITLE
Add option for download by URL to download music to music directory, not temporary directory.

### ISSUE THREAD

**Issue by gittigy** [azlux/botamusique#356]
**Is your feature request related to a problem? Please describe.**
I noticed songs that I had added by URL were often re-downloaded because they go to the temp directory and there is a temp directory size threshold to be maintained.

**Describe the solution you'd like**
I would like the option to download a song by URL and it be added to the music folder that uploaded music goes to. This would allow songs to be replayed without having to constantly redownload it as songs are added by URL.

**Describe alternatives you've considered**
I believe the size threshold can be increased but this doesn't really solve the problem.

**Additional context**
Botamusique is a fantastic music bot for mumble. Thank you very much for sharing such a great addition to mumble!

**Comment by wyldeTurkey** [comment]
YES. Where are the files actually being saved to? I want the files placed on the file system permanently so i can store and manage them and possibly restore them in the case of a failure. I do not want a youtube streamer. I want the youtube video's audio downloaded, labeled and stored permanently like mumble-ruby-plugin-bot. At the moment youtube streaming plugin. It should remove the word "download" from it's title.

**Comment by TerryGeng** [comment]
There is a quick solution: change the `tmp_folder` to a permanent location (I point it to my Download folder) and set `tmp_folder_max_size = -1`.

**Comment by gittigy** [comment]
> There is a quick solution: change the `tmp_folder` to a permanent location (I point it to my Download folder) and set `tmp_folder_max_size = -1`.

I tried changing the tmp_folder to my Download folder but doing so seemed to cause an error on the rescan function that is called when a file is uploaded or if the "refresh_cache_on_startup = True". I've attached a screenshot of the error.
![Error_on_tmp_dir_change](https://user-images.githubusercontent.com/4673034/231043355-f1f24d1a-3c7e-4850-a9e8-084654941cc9.png)

I think setting "tmp_folder_max_size = -1" accomplishes the goal I'm seeking in that the temporary size threshold will never be reached, thus songs added by URL will keep being stored in the tmp directory and no songs will be deleted. Am I correct on this? If this is correct, I should be good I think.

@TerryGeng, when you changed the tmp directory, how did you avoid the errors on the refresh/rescan function? did you update something else to make this work? Thanks for your input!

**Comment by TerryGeng** [comment]
@gittigy Sorry for the late response. I think I have never encountered this in the past... I would guess just by changing the download path in the config, the database got confused. Could you completely delete the database and try starting fresh?
