### ISSUE TITLE
Bot does not start: AttributeError: 'Authenticate' object has no attribute 'client_type'

### ISSUE THREAD

**Issue by fuck-shithub** [azlux/botamusique#357]
**Describe the bug**
Bot won't start

**Affected version**
bf321cfda41809d93de43b03737271f8a2050766

**To Reproduce**
1. python3 -m venv venv
2. venv/bin/pip install wheel
3. venv/bin/pip install -r requirements.txt
4. ./venv/bin/python mumbleBot.py

**Expected behavior**
The bot starts

**Log**
```
[Mar 12 15:04:11 INFO] library: rebuild directory cache
[Mar 12 15:04:11 INFO] library: rebuild directory cache
[Mar 12 15:04:11 INFO] bot: botamusique version 7.2.2-46-gbf321cf, starting...
[Mar 12 15:04:11 INFO] bot: botamusique version 7.2.2-46-gbf321cf, starting...
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/var/lib/botamusique/botamusique/venv/lib/python3.10/site-packages/pymumble_py3/mumble.py", line 130, in run
    if self.connect() >= PYMUMBLE_CONN_STATE_FAILED:  # some error occurred, exit here
  File "/var/lib/botamusique/botamusique/venv/lib/python3.10/site-packages/pymumble_py3/mumble.py", line 190, in connect
    authenticate.client_type = self.client_type
AttributeError: 'Authenticate' object has no attribute 'client_type'
```

**Server (please complete the following information):**
 - OS: Alpine Linux 3.17 (kernel 5.15.100)

**Comment by elch01** [comment]
Same behavior here, recently migrated my murmur installation and the bot broke on re-installation.

**Comment by elch01** [comment]
got it to work with
**python3** mumbleBot.py -s HOST -u BOTNAME -P PASSWORD -p PORT -c CHANNEL -C /path/to/botamusique.pem

**Comment by azlux** [comment]
Do you have a server password ?

**Comment by fuck-shithub** [comment]
No I don't have a server password.

**Comment by azlux** [comment]
find the issue, is the new release of pymumble producing the problem

**Comment by azlux** [comment]
I've delete the version (of pymumble) because I forgot to recompile the protobuff file descriptor.
If you remove your image (docker) or pip lib (pymumble), then re-run it again, this should be fix, or way tomorrow (I hope) , I will fix pymumble

**Comment by fuck-shithub** [comment]
It doesn't run at all if I remove `venv/lib/python3.10/site-packages/pymumble_py3/`. I don't know what you mean with remove pip lib.

**Comment by azlux** [comment]
yes, uninstall pymumble, then install it again with `pip install pymumble`

**Comment by fuck-shithub** [comment]
Thanks, that worked
