### ISSUE TITLE
Add to README info about generating certificate for a bot

### ISSUE THREAD

**Issue by thejustsoul** [azlux/botamusique#36]
**Additional context**
Can be to add information about manually generating a certificate for a bot?

Command for generate certificate: 
`$ openssl req -x509 -nodes -days 3650 -newkey rsa:2048 -keyout botamusique.pem -out botamusique.pem -subj "/CN=botamusique"`

Add to bot launch options:
` -C /path/to/botamusique.pem`

UDP: and maybe add param for path certificate in configuration.ini config?

**Comment by slipenbois** [comment]
Readme updated thx.
For the ini we need to wait for azlux.
