### ISSUE TITLE
A question about default radio channels

### ISSUE THREAD

**Issue by Irets** [azlux/botamusique#360]
Hey,

This isn't an issue per se, but rather a freeform request for guidance.
I cloned this project and setup the bot locally on my server. I'm really liking it so far.

I setup my **configuration.ini** by following the clear instructions on this github page but one thing still bothers me.

The header for **configuration.default.ini** quite strictly advices against modifying the file but I saw no other way to remove the pony radio channels from the output of _!radio_ on my server.
The pony channels were not listed in my own **configuration.ini** yet they were still displayed in _!radio_.
Removing the lines got rid of them.

Could there have been a way to do this only by modifying **configuration.ini** without touching the **configuration.default.ini**?
I am aware there be manual work when I proceed to pull any future changes from github to my local repo.

Cheers and thank you for the bot!

**Comment by roughnecks** [comment]
Just wanted to say I did exactly the same!

**Comment by azlux** [comment]
Ho, it's because it's proceed as a list into the configuration, we append into a list not erase value.
I will remove the existing radio in this case.
