### ISSUE TITLE
botamusique/media/file.py", line 88, in _get_info_from_tag    assert match is not None

### ISSUE THREAD

**Issue by AmmarkoV** [azlux/botamusique#371]
**Describe the bug**
Traceback (most recent call last):
  File "/home/ammar/Documents/3dParty/botamusique/mumbleBot.py", line 926, in <module>
    var.cache.build_dir_cache()
  File "/home/ammar/Documents/3dParty/botamusique/media/cache.py", line 128, in build_dir_cache
    item = item_builders['file'](path=file)
  File "/home/ammar/Documents/3dParty/botamusique/media/file.py", line 27, in file_item_builder
    return FileItem(kwargs['path'])
  File "/home/ammar/Documents/3dParty/botamusique/media/file.py", line 53, in __init__
    self._get_info_from_tag()
  File "/home/ammar/Documents/3dParty/botamusique/media/file.py", line 88, in _get_info_from_tag
    assert match is not None
AssertionError

**Affected version**
master 

**To Reproduce**
First run of :
python3 mumbleBot.py 
with a big music library

**Expected behavior**
The bot indexing the music library correctly

**Desktop (please complete the following information):**
 - OS: Ubuntu 22.04.2 LTS
 - Browser firefox
 - Version 116

**Comment by TerryGeng** [comment]
Could you add line `self.logger.info(self.uri())` before line 88 of `botamusique/media/file.py` and see what it spits out? You may need to run the bot with the verbose mode.

**Comment by duarm** [comment]
did it worked before #369? I noticed that commit regressed the special case of a path with a single /

before:
![image](https://github.com/azlux/botamusique/assets/26150581/13639d34-3cf8-4ffc-9c69-a76777a258d8)

after:
![image](https://github.com/azlux/botamusique/assets/26150581/4da8b9b2-986c-471d-95a3-dbc243cf762c)

Does your path look something like that? Can it fail in other ways?

**Comment by TerryGeng** [comment]
> did it worked before #369? I noticed that commit regressed the special case of a path with a single /
> 
> before: ![image](https://user-images.githubusercontent.com/26150581/256997513-13639d34-3cf8-4ffc-9c69-a76777a258d8.png)
> 
> after: ![image](https://user-images.githubusercontent.com/26150581/256997536-4da8b9b2-986c-471d-95a3-dbc243cf762c.png)
> 
> Does your path look something like that? Can it fail in other ways?
> 
> It can be fixed by making the first group optional, and checking if it's null ![image](https://user-images.githubusercontent.com/26150581/256997669-c93f894a-7029-4428-bd05-2747f44ad974.png)
> 
> Although I think using `os.path.split(self.uri())` would be more robust

I agree with you. Plus, under Windows, `\` is the delimiter in file paths, and `/` would not work. Do you mind opening a PR for this?

**Comment by duarm** [comment]
I will
