### ISSUE TITLE
Bad Parsing/Rendering of Queue

### ISSUE THREAD

**Issue by rackoono** [azlux/botamusique#44]
I noticed a bad rendering of the queue using !queue, this has probably something to do with titles parsing.

Playlist used: https://www.youtube.com/playlist?list=PLFSBmHmcw0y_p7eS3omeIX6E_f2GtQ6Ra

Cropped output of !queue command:

> [02:58:20] (Channel) <a href='clientid://78/fm4Tpzq+Y4Jr9zN8C3rk81vz07U=' class='log-user log-source'>RYTHMISGAY</a>: The next items in the queue are:<br />[1] (url) Adieu jolie Candy<br />[2] (url) Aline<br />[3] (url) Comme j'ai toujours envie d'aimer (version 2001)<br />[4] (url) Et tu danses avec lui<br />[5] ... 

Full output here : https://pastebin.com/fY0As0J6

I am trying to investigate this playlist in order to give a more accurate guess at the thing causing the problem.

**Comment by azlux** [comment]
The command queue don't print the current music played.
I will investigate. I'm sorry if the code isn't clear enough. I don't write lot of comments.
Since some people have joined me into the development, I will add comments on my code.
