### ISSUE TITLE
[ffmpeg] Adding metadata to '/tmp/xyz.mp3' - really slow

### ISSUE THREAD

**Issue by satcom886** [azlux/botamusique#48]
Is there a way to make the bot faster? I know it uses youtube-dl, but I do not get stuck on youtube-dl converting the video to mp3, but ffmpeg adding metadata. This is the line: 
[ffmpeg] Adding metadata to '/tmp/1db427d063c1d15195f4c3ebbd246e75.mp3'

Is it really nessesary to have this metadata? Is it something that youtube-dl does on its own? Also contrary to when yt-dl is converting I do not see any load on the CPU nor the HDD during the "metadata adding".

**Comment by azlux** [comment]
It's weird than ffmpeg take time to add the metadata.

I use the metadata to get the title when a user choose a music already download in cache to have instant play.

I do testing, adding metadata never take more than 1second on my side.

```
May 06 14:19:20 python[7245]: [ffmpeg] Destination: /tmp/botamusique_music/d601bd74123eb9067e92c0a33caaa835.mp3 (download)
May 06 14:19:52 python[7245]: Deleting original file /tmp/botamusique_music/d601bd74123eb9067e92c0a33caaa835.webm (pass -k to keep) (remove the video)
May 06 14:19:52 python[7245]: [ffmpeg] Adding metadata to '/tmp/botamusique_music/d601bd74123eb9067e92c0a33caaa835.mp3'
May 06 14:19:53 python[7245]: FFmpeg command : ffmpeg -v warni [...] (Start to play)
```

What is you HDD ?
Can you try to set the option `tmp_folder` on a tmpfs mont to see if there are a difference ?

Az

**Comment by satcom886** [comment]
I am running the bot on a Raspberry Pi, so it probably uses the SD card for the temp files.

**Comment by Mati20187** [comment]
There's definitely something wrong. When playing a single song with !url, everything is fine and the metadata downloads within a couple of seconds but when trying to play even a very short (3 songs) youtube playlist with !playlist, the metadata downloading never finishes.
I've checked htop and there aren't any ffmpeg processes running.
Here's what I'm doing:
`!playlist https://www.youtube.com/playlist?list=PL1qiB_iRKQOg5BWaqWptft_6JOliggUEU`

The bot responds:
`(Channel) MusicBOT: Download of Epic Dark Battle Music • "Where Is Your God Now" by Rok Nardin in progress`

Bot log:
```
Feb 06 19:29:15 raspberrypi python[337]: [youtube] bsvzP8EO65w: Downloading video info webpage
Feb 06 19:29:17 raspberrypi python[337]: [youtube] Downloading just video bsvzP8EO65w because of --no-playlist
Feb 06 19:29:17 raspberrypi python[337]: [youtube] bsvzP8EO65w: Downloading thumbnail ...
Feb 06 19:29:17 raspberrypi python[337]: [youtube] bsvzP8EO65w: Writing thumbnail to: /tmp/3417590f33f69eb9acadfba61e091238.jpg
Feb 06 19:29:17 raspberrypi python[337]: [download] Destination: /tmp/3417590f33f69eb9acadfba61e091238.m4a
Feb 06 19:29:17 raspberrypi python[337]: [674B blob data]
Feb 06 19:29:18 raspberrypi python[337]: [ffmpeg] Correcting container in "/tmp/3417590f33f69eb9acadfba61e091238.m4a"
Feb 06 19:29:18 raspberrypi python[337]: [ffmpeg] Destination: /tmp/3417590f33f69eb9acadfba61e091238.mp3
Feb 06 19:29:31 raspberrypi python[337]: Deleting original file /tmp/3417590f33f69eb9acadfba61e091238.m4a (pass -k to keep)
Feb 06 19:29:31 raspberrypi python[337]: [ffmpeg] Adding metadata to '/tmp/3417590f33f69eb9acadfba61e091238.mp3'
```

**Comment by Mati20187** [comment]
Maybe this will help visualize the issue: https://lbry.tv/untitled:d9

**Comment by Mati20187** [comment]
Terry Geng's pull request fixes this issue for me

**Comment by TerryGeng** [comment]
Ummmm... That's weird. I think the metadata is managed by youtube-dl and my code should not affect it. Lucky me!
