### ISSUE TITLE
Include radio stations from www.radio-browser.info

### ISSUE THREAD

**Issue by elpatron68** [azlux/botamusique#49]
Hi,

thanks for botamusique, it works very smooth on the first try.

To have a great and community-updated variety of internet radio stations, I thought it would be a good idea to implement an interface to the API of http://www.radio-browser.info/webservice

Bye,
Markus

**Comment by azlux** [comment]
Thank for the report.
I don't have time right now, but I will take a look asap.

Az

**Comment by elpatron68** [comment]
I just found a Python library for radio-browser which could make things easier: https://pypi.org/project/pyradios/

**Comment by azlux** [comment]
How to you want to select a radio ? with the name ? the id ?

**Comment by elpatron68** [comment]
If I had a free wish:

_Input:_
`!listradio <station name>`

_Output:_
```
1) <Match 1>
2) <Match 2>
...
```

_Input:_
!radio 1

Or something similar...

**Comment by azlux** [comment]
I need to test something similar, botamusique don't have interaction process.

**Comment by elpatron68** [comment]
Or something like this?

`!findradio <station name>`

_Output:_
`<Station_Name> -  <Station_ID>`

`!radio <Station_ID>`

**Comment by azlux** [comment]
I'm currently waiting for https://github.com/andreztz/pyradios/issues/1 to work on it.

**Comment by elpatron68** [comment]
As @andreztz seems not to solve the requirements problem with pyradios, I had a short look into the project´s code. It should be no problem to include radios.py from it into Botamusique. A small function like

```
from radios import RadioBrowser

rb = RadioBrowser()

def getstations_byname(query):
    results = rb.stations_byname(query)
    stations = []
    for st in results:
        try:
            url = rb.playable_station(st['id'])['url']
            station = {'stationname': st['name'], 'url': url}
            stations.append(station)
        except:
            pass
    return stations


if __name__ == "__main__":
    r = getstations_byname('r.sh')
    pass
```

would then return an array of staions and playable urls.

**Comment by elpatron68** [comment]
Finally found some time to add it. Hope, it´s okay, see pr #52

**Comment by azlux** [comment]
Thanks a lot.
I'm reading the commit,
Let's close the ticket and continue on the PR.
