### ISSUE TITLE
REQ: Modular configuration file implementation

### ISSUE THREAD

**Issue by Glowsome** [azlux/botamusique#50]
**Is your feature request related to a problem? Please describe.**
No,  this is to minimize administration when running multiple instances.

**Describe the solution you'd like**
Possibility to use a construction of a Global configuration file (needed for minimal/global functionality) and to include/attatch an instance-specific add-on configuration so to say.

**Describe alternatives you've considered**
None that i could think of, now whenever i change something (like markup) i need to go thru all instance-ini - files.

**Additional context**
In my case i use a reference to an ini-file per-instance ie. configuration<portnumber>.ini
As this holds the full configuration if i were to change something of the parameters i would like to have on all instances i need to repeat it multiple times.
Preference would be that a 'global' configuration.ini can be used with a reference to a 'per-instance' configuration ini that would act as an addon, where instance-specific parameters can be set (and possibly even override settings from the global configuration)

**Comment by azlux** [comment]
Hi,
I think it's harder for me to implement this requests than you making a script to manage all your config file.
You have a really specific case here.

Azlux
