### ISSUE TITLE
Doesn't skip current song

### ISSUE THREAD

**Issue by Klowd8007** [azlux/botamusique#53]
**Describe the bug**
When using the skip command, it skips the next song in the queue, but not the current song playing

**Affected version**
Version 3 
commit: 3684f54928c081f9d2ac4204758fc6926e13af4c

**Expected behavior**
The command skip should skip the current song playing

**Comment by azlux** [comment]
I've forgot about this issue.
Is the issue still present ? I don't remember having the problem.

**Comment by Klowd8007** [comment]
Yes, it is still present.
![image](https://user-images.githubusercontent.com/54419605/66259340-ddd28380-e77d-11e9-9a2a-5f3f8aff66d4.png)

For example, I have 3 songs in queue. First one is playing, I enter skip, then display the queue and we can see that the second song isn't there anymore although it says it is the song now playing, but in fact, it is still the first song

**Comment by azlux** [comment]
I don't understand.
I try to debug and test multiple times. I don't see the issue.
All times, my current song stop, and the next one start.
