### ISSUE TITLE
slow when lot of folers

### ISSUE THREAD

**Issue by azlux** [azlux/botamusique#55]
Report from a user :

I have some suggestions for improving the performance of the bot:
1. I noticed that when there are a lot of music files, the bot 'thinks' for a very long time. Apparently he reads all the files in all folders. It may be possible to have these actions performed by the team.
For example: !scan_file >> botamusique scans the music folder and writes the names of the tracks (duration and path to the file) in its database.
I think this should speed up the process of displaying all the songs on the list.
2. By default, all music folders are opened in the web interface. Maybe it's better to make them minimized initially?

**Comment by TerryGeng** [comment]
Sorry I haven't fixed this yet. I'm currently working on it.

**Comment by LDelOff** [comment]
I think there is a solution to this problem.
Let the bot create a "database" which will contain information about all the music files.
For example, you can create a table like the one below:
![image](https://user-images.githubusercontent.com/51275636/75681844-732e6100-5ca5-11ea-9a72-76c5a231bc97.png)
You need to create a function: scan files.
During its execution, the database will be supplemented.

Most likely this will speed up the process of finding a file, adding a folder to the playlist.

**Comment by TerryGeng** [comment]
Yes, a database is a good idea. And it is the very reason that I choose sqlite3 in this version in place of the db.ini in the past. Now with powerful sqlite3 I think I can really construct a music library that stores the titles, thumbnails, and paths of songs.

And maybe you can save multiple playlists in the database and query them out when you need them.

I can imagine many cool features with help from the database. Plus, if you have any other suggestions, you are welcome to bring them up. In think in the next version we will have a music library ready. Do please look forward to it :-).

**Comment by TerryGeng** [comment]
Added in #91.
