### ISSUE TITLE
Bot won't run

### ISSUE THREAD

**Issue by asdfjkluiop** [azlux/botamusique#58]
**Describe the bug**
When attempting to run the bot I get

    Traceback (most recent call last):
      File "mumbleBot.py", line 888, in <module>
        botamusique = MumbleBot(args)
      File "mumbleBot.py", line 145, in __init__
        self.set_comment()
      File "mumbleBot.py", line 816, in set_comment
        self.mumble.users.myself.comment(var.config.get('bot', 'comment'))
    AttributeError: 'NoneType' object has no attribute 'comment'

**To Reproduce**
1. Setup the latest bot
2. Copy config over to configuration.ini
3. Run bot

**Comment by azlux** [comment]
Hi,
This error means the bot was not able to connect the mumble server and create the mumble python object.
I really need to make a better error in this case

**Comment by asdfjkluiop** [comment]
Hmmmm, so I did a bit of looking around and it looks like AF_INET6 is not set on the socket created by pymumble and my mumble server is IPv6 exclusive. That might explain the inability to connect. I'll go open a bug report there about this issue and leave this here as a bug related to the error.

**Comment by azlux** [comment]
Should be good now.
Please try to update the submodule, instructions here : https://github.com/azlux/botamusique#update

**Comment by azlux** [comment]
If you need help. You can enable debug mode or contact me on #mumble on freenode.
