### ISSUE TITLE
Support for user certificates

### ISSUE THREAD

**Issue by thejustsoul** [azlux/botamusique#6]
**Is your feature request related to a problem? Please describe.**
There is not enough support for user p12 or PEM certificates for authenticating as a registered user. To obtain privileges on the server and access to private channels.

**Describe the solution you'd like**
It would be nice if there was autogeneration of the certificate for authorization on the server, so you do not have to generate manually.

**Comment by azlux** [comment]
hi @thejustsoul .
I will add the certificate part int the next commit.
But you will not be able to create new one automatically (for now).

**Comment by azlux** [comment]
Oops, I've forgot this issue.
On my todo list !
Sry
