### ISSUE TITLE
Playing stream fills memory 

### ISSUE THREAD

**Issue by Glowsome** [azlux/botamusique#60]
**Describe the bug**
When the bot plays a stream memory is slowly being consumed.
In my case the (LXC) machine has 4Gb mem and 1Gb Swap, dedicaded for the bot.

When bot is idle (after a restart) 
MiB Mem :   4096.0 total,   3362.9 free,    235.6 used,    497.6 buff/cache
MiB Swap:   5120.0 total,   5113.1 free,      6.9 used.   3860.4 avail Mem

As soon as bot is starting to stream the memory count drops by ~0.1 Mb / 12-15 seconds
This will continue to drop untill there is nothing left (mem and swap), bot will stop streaming/go unresponsive.
After ~10 minutes : 
MiB Mem :   4096.0 total,   3303.3 free,    236.7 used,    556.0 buff/cache
MiB Swap:   5120.0 total,   5113.0 free,      7.0 used.   3859.3 avail Mem

Stopping the stream does not release consumed memory, only a reboot will really free it up.

 
**Affected version**
The exact version you're using (git commit id). You should **always** only report bugs which you can reproduce on the latest version (`uif` branch), however **always** state the current commit id here (in case there are new commits between your report and us looking at it)

**To Reproduce**
1. start the bot
2. issue command to start playing a stream like 
3. watch console 'top' memory slowly going down

**Expected behavior**
memory should be released after 'use', so no fillup/out of memory happens.

OS : cat /etc/os-release
PRETTY_NAME="Debian GNU/Linux 10 (buster)"
NAME="Debian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"

ffmpeg :  ffmpeg -version
ffmpeg version 4.1.4-1~deb10u1 Copyright (c) 2000-2019 the FFmpeg developers
built with gcc 8 (Debian 8.3.0-6)

If extra info is required just ask and i will provide

**Comment by azlux** [comment]
Speaking with ffmpeg dev, look like this version can have many leaking.
They ask to try with last version, It's easy to get last build (4.2.1-2).
use : `deb http://ftp.de.debian.org/debian sid main` source list.
Don't forget to lower the priority of this testing repo with `Pin-Priority` apt parameter.

If the issue still present, next step is testing with git head version.

**Comment by Glowsome** [comment]
Hi, 
Implemented the suggested changes according to your suggestions above.
- added the repo
- set prio
- ran  apt-get -t unstable  install ffmpeg

Version of ffmpeg now showing is : 
 ffmpeg -version
ffmpeg version 4.2.1-2+b1 Copyright (c) 2000-2019 the FFmpeg developers
built with gcc 9 (Debian 9.2.1-21)

From a quick look it seems that memory consumption / release of memory is back into order now.
Will leave the stream running for now and see in the morning (its now 3:00 am)

**Comment by Glowsome** [comment]
[03:50] (sorry couldnt sleep :) 
The rate of mem consumption has gone down considerably, but it is still eating away memory, it now comsumed ~50Mb in this timeframe whilst the stream is running on the bot.

**Comment by Glowsome** [comment]
Just an update .. bot's been streaming for a whole day without issues .... so it seems to be resolved .. however this does look concerning, or i am totally mislead : 
MiB Mem :   4096.0 total,     47.7 free,    141.8 used,   3906.5 buff/cache
MiB Swap:   5120.0 total,   4373.7 free,    746.3 used.   3954.2 avail Mem

**Comment by Lartza** [comment]
https://www.linuxatemyram.com/
