### ISSUE TITLE
Bot can't play music from YouTube playlists

### ISSUE THREAD

**Issue by Encryptize** [azlux/botamusique#61]
**Describe the bug**
Bot can't play playlists from YouTube

**Affected version**
Actually stable version when I'm writing this (27.01.2020)

**To Reproduce**
1. Start a bot
2. Issue command to start playing playlist from YouTube
3. 

> [download] Finished downloading playlist: Vatikansky - 2138
> 2020-01-27 21:45:26: Async download next asked
> 2020-01-27 21:45:26: Current music wasn't ready, Downloading...
> Traceback (most recent call last):
>   File "mumbleBot.py", line 888, in <module>
>     botamusique = MumbleBot(args)
>   File "mumbleBot.py", line 151, in __init__
>     self.loop()
>   File "mumbleBot.py", line 795, in loop
>     self.launch_music()
>   File "mumbleBot.py", line 619, in launch_music
>     self.download_music(index=0)
>   File "mumbleBot.py", line 724, in download_music
>     'strings', "download_in_progress") % var.playlist[index]['title'])
> KeyError: 'title'

**Expected behavior**
Can you fix that? I want to play music from playlist.

OS:

> cat /etc/os-release
> NAME="Ubuntu"
> VERSION="18.04.3 LTS (Bionic Beaver)"
> ID=ubuntu
> ID_LIKE=debian
> PRETTY_NAME="Ubuntu 18.04.3 LTS"
> VERSION_ID="18.04"
> HOME_URL="https://www.ubuntu.com/"
> SUPPORT_URL="https://help.ubuntu.com/"
> BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
> PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
> VERSION_CODENAME=bionic
> UBUNTU_CODENAME=bionic

**Comment by azlux** [comment]
Can you send me the link of your playlist.
The bot should be able to play it.

**Comment by Encryptize** [comment]
> Can you send me the link of your playlist.
> The bot should be able to play it.

https://www.youtube.com/playlist?list=PL6edxAMqu2xfxgbf7Q09hSg1qCMfDI7IZ

**Comment by Encryptize** [comment]
Okey, I'm stupid. I'm trying to play playlist with command !url, not !playlist.

**Comment by azlux** [comment]
no problem.
Have fun with the bot
