### ISSUE TITLE
Cant properly play all radio URLs

### ISSUE THREAD

**Issue by nifker** [azlux/botamusique#63]
I tried e.g. this stream URL but it doesnt seem to work and crash botamusique because of the SSL verification.

Traceback (most recent call last):
  File "/usr/lib/python3.7/urllib/request.py", line 1319, in do_open
    encode_chunked=req.has_header('Transfer-encoding'))
  File "/usr/lib/python3.7/http/client.py", line 1252, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.7/http/client.py", line 1298, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.7/http/client.py", line 1247, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.7/http/client.py", line 1026, in _send_output
    self.send(msg)
  File "/usr/lib/python3.7/http/client.py", line 966, in send
    self.connect()
  File "/usr/lib/python3.7/http/client.py", line 1422, in connect
    server_hostname=server_hostname)
  File "/usr/lib/python3.7/ssl.py", line 423, in wrap_socket
    session=session
  File "/usr/lib/python3.7/ssl.py", line 870, in _create
    self.do_handshake()
  File "/usr/lib/python3.7/ssl.py", line 1139, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1076)

Server info:
Nano Pi M1
Debian Bullseye

**Comment by azlux** [comment]
Which url are you speaking about ?
I will check the next week

**Comment by nifker** [comment]
This specifically: https://streams.ilovemusic.de/iloveradio105.mp3
For now I just added the missing certificate to /etc/ssl/certs/

**Comment by Lartza** [comment]
Their server is misconfigured and their certificate chain is incomplete (missing intermediate cert). Not the bot's fault you can use it without https

**Comment by nifker** [comment]
What about a flag to ignore this chain issue(as most browsers seem to do it too)?

**Comment by Lartza** [comment]
The issue with that is the connection isn't secure then. I'm not sure why browsers are ignoring it but even they are ignoring it weirdly. (On Firefox if you click on the lock icon, arrow then more information and go to Security it says connection not encrypted in technical details)

**Comment by Canule** [comment]
Cheap workaround if not forced to https, just loose the "s" in the url http://stream.gal.io/arrow (stream with similar state)

**Comment by azlux** [comment]
What's your youtube-dl version. This error come from them.
There are options to avoid https check, but it's not recommended.

**Comment by TerryGeng** [comment]
@nifker Can we close this issue?

**Comment by nifker** [comment]
For me, yes.
