### ISSUE TITLE
server / default connection transferred from startcommand to configuration-file ?

### ISSUE THREAD

**Issue by Glowsome** [azlux/botamusique#7]
**Is your feature request related to a problem? Please describe.**
No

**A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]
Instead of passing (server-specific) parameters to start the bot on commandline if possible transfer them as configuration parameters to config-file

**Describe the solution you'd like**
If possible create the connection-parameters to be in configuration file : 

```
[connection]
server = mumble.server.dns.name
port = 64738
botname = MusicBot
chan = default_channel to join ( enable escape with quotes for channels with spaces ie: "AFK or Busy"

```
**A clear and concise description of what you want to happen.
Setting the connection parameters in the config-file will make it easyer to start the bot (or run it as a daemon in background)

**Describe alternatives you've considered**
None yet

**Additional context**
None

**Comment by fsteffek** [comment]
Adding those parameters to the config is a good idea IMO. I'd keep the command line parameters though in case one wants to override the config values.
