### ISSUE TITLE
Song title url doesn't recognized

### ISSUE THREAD

**Issue by Imho2000** [azlux/botamusique#73]
Hello everybody,
When i call a song from youtube with !url command, the name of the song is wrong. 
For example:
!url  https://www.youtube.com/watch?v=YlUKcNNmywk
response:
Red Hot Chili Peppers - 359fcc69dc722499b47110344a6f2b49 

The bot can't recognize text after " - " char...

On configuration.ini in line now_playing, there is the parameter %s and %s .
Thank you in advance for your help!!

**Comment by azlux** [comment]
Will be fix with #71
