### ISSUE TITLE
Post a new release?

### ISSUE THREAD

**Issue by TerryGeng** [azlux/botamusique#74]
I think that by now the bot is almost stable. If nothing goes wrong maybe we can post a new release (version 6)?

**Comment by azlux** [comment]
As you can see on last commits, I will finish testing before releasing next version.

**Comment by TerryGeng** [comment]
Got it.

**Comment by azlux** [comment]
After #79 , to not disturb previous users

**Comment by azlux** [comment]
I will try to upload the next stable version this evening (UTC+01)

**Comment by TerryGeng** [comment]
I think we need to re-post the new release since some more bugs went out today...

**Comment by azlux** [comment]
My bad
Srry for that

**Comment by TerryGeng** [comment]
5.2 has been posted. I wish no more bugs would appear....
