### ISSUE TITLE
Password protection for the web interface doens't work

### ISSUE THREAD

**Issue by Imho2000** [azlux/botamusique#75]
Hi guys,
i have enabled the password protection for the web interface but when i go on web page, i don't have any request for user/password.
In config file i have enabled this settings:

[webinterface]
enabled = True
is_web_proxified = False
listening_addr = 0.0.0.0
listening_port = 8181

require_auth = True
user = admin
password = adminpass

Any suggest?
Thank you!

**Comment by TerryGeng** [comment]
That's weird. I have been using this password protection for weeks and nothing went wrong.
Did you restart the bot?
Can you post the log of the bot?

It should read
```
[Feb 25 17:23:48 INFO Thread-1950] Web Interface login failed.
[Feb 25 17:23:48 INFO Thread-1950] xx.xx.xx.xx - - [25/Feb/2020 17:23:48] "GET / HTTP/1.1" 401 -
```

However, in my config, I did enable `is_web_proxified` though I'm not quite sure what it does.

**Comment by Imho2000** [comment]
Thanky for quickly reply.

I have tested web interface protection with is_web_proxified enabled and disabled (you can see the switch on log file) but not have effects.
This is my log file
2020-02-25 10:36:24: Starting web interface on 0.0.0.0:8181
2020-02-25 10:36:24:  * Running on http://0.0.0.0:8181/ (Press CTRL+C to quit)
2020-02-25 10:36:40: 127.0.0.1 - - [25/Feb/2020 10:36:40] "[37mGET / HTTP/1.1[0m" 200 -
2020-02-25 10:36:58: 127.0.0.1 - - [25/Feb/2020 10:36:58] "[37mGET / HTTP/1.1[0m" 200 -
2020-02-25 10:37:22: Starting web interface on 0.0.0.0:8181
2020-02-25 10:37:22:  * Running on http://0.0.0.0:8181/ (Press CTRL+C to quit)
2020-02-25 10:37:23: 127.0.0.1 - - [25/Feb/2020 10:37:23] "[37mGET / HTTP/1.1[0m" 200 -

**Comment by TerryGeng** [comment]
I think you are using the old version of the bot. Can you just pull the master branch of this repo and test again? In the newer version, the log file should not be formatted like what you have posted.

**Comment by azlux** [comment]
If you don't use git but the recommended method (based on stable release), update will appears in few days. We need to tests to changes.

**Comment by Imho2000** [comment]
I have installed botamusique a few minutes ago with curl -Lo botamusique.tar.gz https://azlux.fr/botamusique/sources.tar.gz command... now i have launch update.sh but the issue persist.

**Comment by Imho2000** [comment]
> If you don't use git but the recommended method (based on stable release), update will appears in few days. We need to tests to changes.

Thank you! The issue was fixed with your suggestion. I have installed git version and now work fine. :)
