### ISSUE TITLE
Version upgrade

### ISSUE THREAD

**Issue by azlux** [azlux/botamusique#76]
I think we need to discuss about auto-upgrade.
I've create a folder on my server to avoid git dependency, but It's not the best method.

I think I need to rewrite this part. Maybe an option to follow release or master git.
What do you think ?

**Comment by TerryGeng** [comment]
Ummmm... I have looked into repo https://github.com/filebrowser/filebrowser and the way they do it is fetch the release stores on the github. I think maybe it's a good way.

**Comment by TerryGeng** [comment]
They have an install script
https://filebrowser.xyz/get.sh . I think it may be helpful if you want to have a look.

**Comment by TerryGeng** [comment]
Okay I see. The trick it the API of github. The link https://api.github.com/repos/filebrowser/filebrowser/releases/latest contains the latest release of this repo. One of the useful items is "assets_url". It contains all assets you uploaded when posting releases.
Inside that url there should be something like
```
    "content_type": "application/gzip",
    "state": "uploaded",
    "size": 10673346,
    "download_count": 161,
    "created_at": "2020-01-09T18:11:09Z",
    "updated_at": "2020-01-09T18:11:09Z",
    "browser_download_url": "https://github.com/filebrowser/filebrowser/releases/download/v2.1.0/darwin-amd64-filebrowser.tar.gz"
  },
```
The download link can be directly extracted from here.

**Comment by azlux** [comment]
This will not work because of the subproject pymumble.
I've setup a weebhook to manage creating the files automatically.
I will modify the update feature later today or tomorrow.

**Comment by TerryGeng** [comment]
Maybe the script can try to download the bot first, then download the release of pymumble and extract it?
Or we can just pack the bot with the latest pymumble into a zip file and upload them as an asset in the release?

**Comment by azlux** [comment]
I've close it because I think [this commit](https://github.com/azlux/botamusique/commit/7d5f8fc778fae9d194aaa2586b2a82f0ba001bef#diff-25e6ad8ebc5d26ba06d2bcb0b220149c) will to the job for now. not the best, but I'm github independant for now.
New release are automatically updating the source with a webhook (I assure you It's a lot better thank the previous way)
