### ISSUE TITLE
Stopping and clearing playlist breaks bot

### ISSUE THREAD

**Issue by Lartza** [azlux/botamusique#77]
**Describe the bug**
If you stop playback with !stop and clear the playlist with !clear or the webinterface, the bot can't resume playback without restart.

It also seems while the bot is stopped downloading new songs isn't triggered and that may be part of the issue (it stops at "bot: Async download next asked" and doesn't continue)

**Affected version**
78b11d1fb55a0cea7985c6cb71853a50d403a331

**To Reproduce**
1. Start the bot with no saved playlist and tmp_folder caching
2. Play a youtube song with !url
3. !stop && !clear
4. Play the same youtube song with !url
5. !play
6. botamusique: play: Command failed with error: KeyError: 'path'.

**Expected behavior**
The bot should be able to resume from a stopped state.

**Comment by TerryGeng** [comment]
I think I have fixed this on this commit. I optimized the launch_music logic and put some file path check on it. Please have a look, thanks.

**Comment by Lartza** [comment]
Seems to be fixed, I couldn't get it to break again at least now.

This isn't super related to this issue but something small I did notice at the same time.
Could !play clear is_pause even if the playlist is empty? https://github.com/azlux/botamusique/blob/9ce98196a1c243ef10c39eaf3017f5799faa2763/command.py#L113-L124 Currently if you !stop, !clear, !play, !url the bot does nothing because it's still paused.

**Comment by TerryGeng** [comment]
This sounds like a feature request. I don't have a strong opinion about how the bot should behave under this situation, so I guess I will follow your advice.

**Comment by Lartza** [comment]
Maybe it is yeah. It seems to work and I didn't see how it would break any code even before, and to me it's a logical way to work.

The alternative to me would have been to make !url clear pause but I think that would have been bad.

Closing this issue since everything should be resolved.
