### ISSUE TITLE
Don't query url if we already have the media

### ISSUE THREAD

**Issue by Lartza** [azlux/botamusique#78]
**Is your feature request related to a problem? Please describe.**
Currently cmd_play_url https://github.com/azlux/botamusique/blob/78b11d1fb55a0cea7985c6cb71853a50d403a331/command.py#L253 and the webinterface https://github.com/azlux/botamusique/blob/8622ff1c66f2821150893d88a1d2fe2895c10131/interface.py#L204 always make a call to get_url_info even if we already have the media cached in tmp_folder, causing even more calls to video pages than the bot is already causing (two per download, instead of using the API to get video duration for example)

**Describe the solution you'd like**
Refactor the check for duration so that if a file exists in tmp_folder it never happens since it already passed the check in the past.

**Describe alternatives you've considered**
Do the check later from the file in tmp_folder.
Always do the checks optionally from the YT API with an apikey(needs additional libraries).

**Additional context**
The point is to make as little calls as possible or to at least to them as right as possible to not get anyone blacklisted from services.

**Comment by TerryGeng** [comment]
However, another thing get_url_info does is to fetch the title of that song. I'm currently planning to implement a music library which is managed by bot's database, if that is done, all metadata would be fetched only once. Now what I can do is to remove duplicated get_url_info in download_music. I will see if youtube-dl can write metadata into the ID3 tag of the music.

**Comment by Lartza** [comment]
I see. At one point I already made mutagen write that data to ID3 because ultimately I want the bot to be able to play cached data randomly, without any calls to youtube. (#17)

**Comment by TerryGeng** [comment]
Thanks. Check this out.

**Comment by Lartza** [comment]
Oh the ID3 handling was still there, I just missed it because you moved it to util and I just searched for mutagen in mumbleBot.py :P

Seems !url works just like it did before but now with no youtube-dl if the file exists, awesome.
Amazing work on the bot overall recently by the way.
