### ISSUE TITLE
clear tmp folder

### ISSUE THREAD

**Issue by azlux** [azlux/botamusique#8]
Clear it before the folder explode.
Specially when it's `/tmp`

**Comment by fsteffek** [comment]
I suggest adding a parameter in the config file. Either specify how many music files are allowed to be in the download folder or rather set a Megabyte limit - or both.

It might be a good idea to add a function, that cleans the folder based on song number / how many MBs are used. In both cases, I'd remove the oldest file.

I'm not sure if it's implemented yet, but deleting a file via the web interface is also a possible solution.

**Comment by azlux** [comment]
I think MB folder size is the best. I will do that.

But not on the web interface. You cannot see the cache folder. This issue is only for the cache from youtube-dl.

**Comment by Lartza** [comment]
My wish is that there is also a way to disable the limit. I'd want to cache everything indefinitely in a non ram-backed location personally.

**Comment by azlux** [comment]
Here the feature.
In `Mo` into the config file.
`-1` to have no limit
`0` to have no cache (except the last music)
