### ISSUE TITLE
String instead of int in stable version 

### ISSUE THREAD

**Issue by ajmandourah** [azlux/botamusique#82]
Love your work..

There is a bug in the stable version in line 74 that you have fixed in the github version. 

just so newbies wont get discouraged using your awesome work. 

All the best

**Comment by TerryGeng** [comment]
I think this has been fixed in 904d78b639769d9ad139f14409e5757f738c5dc5. Thank you for reporting :-)

**Comment by azlux** [comment]
I suppose you have install the version before I finish deploying the hotfix for stable version.
It's all fixe now
