### ISSUE TITLE
Search YouTube

### ISSUE THREAD

**Issue by Qwerty-Space** [azlux/botamusique#87]
**Describe the solution you'd like**
Something like `!ytsearch songname` will play the first result

**Additional context**
Similar to music bots on Discord:
![image](https://user-images.githubusercontent.com/6967592/75637675-da093700-5c1f-11ea-874f-5109703720b0.png)

**Comment by TerryGeng** [comment]
e17d5446bf7f226eb6e156d0c13b280737696d71 .

Thanks for your nice idea. Please have a look.

**Comment by Qwerty-Space** [comment]
Works nicely!
However I have a few recommendations

It should work like this:
```!yquery {keyword}
<bot response>
{index}
<plays {index}>```

instead of a separate command.

Then you can have `!ytplay {keywords}` to play the most similar match

**Comment by TerryGeng** [comment]
A. You mean directly add the first item to the playlist after a successful query? 

B. or you mean
- you: !ytquery  xxx
- bot: (some results) 1. xxx, 2. xxx, ....
- you: 1
- bot starts to play 1 immediately

I'm not very sure. A seems a little bit too automatically, while I'd like to grant more control to users over the bot.
B makes sense, but the structure we adapt now doesn't offer an elegant way to let the bot interact with you so casually. The idea I'd like to implement is making a new command
- !ytqa(!ytqueryadd) {keywords}
which will do your job. Is that what you want?

and from your picture I think offering more controls about where to place the music is also a good idea, like place a '@' sign behind the command stands for put the item after current song.
Maybe '@' sounds a bit silly and you have some better idea...

**Comment by LDelOff** [comment]
If this helps, I saw this person’s music search function on YouTube
https://github.com/DuckBoss/JJMumbleBot

**Comment by Qwerty-Space** [comment]
> 
> 
> A. You mean directly add the first item to the playlist after a successful query?
> 
> B. or you mean
> 
>     * you: !ytquery  xxx
> 
>     * bot: (some results) 1. xxx, 2. xxx, ....
> 
>     * you: 1
> 
>     * bot starts to play 1 immediately
> 

B.  when doing `!ytquery`.  However I think there should be a `!ytplay` command that acts like A, because YouTube's algorithm is usually quite good at giving the correct result first:
![image](https://user-images.githubusercontent.com/6967592/75708278-6f580a00-5cb8-11ea-9bc6-e39762d358a6.png)
It just takes longer to do both commands, and just typing `1` feels more correct than typing `ytplay 1`.  

> 
> I'm not very sure. A seems a little bit too automatically, while I'd like to grant more control to users over the bot.
> B makes sense, but the structure we adapt now doesn't offer an elegant way to let the bot interact with you so casually. The idea I'd like to implement is making a new command
> 
>     * !ytqa(!ytqueryadd) {keywords}
>       which will do your job. Is that what you want?
> 
> 
> and from your picture I think offering more controls about where to place the music is also a good idea, like place a '@' sign behind the command stands for put the item after current song.
> Maybe '@' sounds a bit silly and you have some better idea...
> 
> Hope you may provide more advices. I will see what I can do tomorrow (UTC+8).

**Comment by TerryGeng** [comment]
Okay I see. In the IRC channel people prefer `!ytplay` play the first result. I think I will keep both.

**Comment by TerryGeng** [comment]
And I don't like the work 'query' :p, I will use `ytsearch` instead

**Comment by TerryGeng** [comment]
Okay. I rename `ytplay` into `yplay`, `ytquery` into `ysearch` since 't' is not necessary.
You may also try the partial match feature, i.e. just type in `!yp xxx` to call `ytplay`

Now if you feed `!yplay {keywords}` it will just add the first search result into the playlist.

**Comment by TerryGeng** [comment]
@Qwerty-Space Closing this issue. Please reopen it if you find bugs or want any improvement.

**Comment by Qwerty-Space** [comment]
@TerryGeng beautiful, I will try it later tonight

**Comment by Qwerty-Space** [comment]
> 
> 
> Okay. I rename `ytplay` into `yplay`, `ytquery` into `ysearch` since 't' is not necessary.
> You may also try the partial match feature, i.e. just type in `!yp xxx` to call `ytplay`
> 
> Now if you feed `!yplay {keywords}` it will just add the first search result into the playlist.

This hasn't been added to configuration.default.ini
