### ISSUE TITLE
Should we start a 'develop' branch?

### ISSUE THREAD

**Issue by TerryGeng** [azlux/botamusique#88]
I think maybe we need some test field for new features. And only merge features that is fully tested to the master branch.

Therefore in the master branch, we can focus on fixing bugs. And people may just grab the master branch for the newest fix without being annoyed by unmatured features.

**Comment by Lartza** [comment]
I don't know what the wontfix means :P Working in pull requests is always a great option too to implement a feature without breaking master. Merge when ready but it's harder for an user to be on the bleeding edge like that.

**Comment by TerryGeng** [comment]
I have started the develop branch for #91.
