### ISSUE TITLE
Stream -error- resume playback option

### ISSUE THREAD

**Issue by Glowsome** [azlux/botamusique#9]
**Is your feature request related to a problem? Please describe.**
Partially - i have one stream source i use that errors from time to time (source problem)

**Describe the solution you'd like**
Auto-restart after a stream which was playing fails.

**Describe alternatives you've considered**
manual restart of the stream always works, its just annoying.

**Additional context**
Suggestion is to let the bot restart the stream ( define x amounts in ini) after failing (if possible)
- when other stuff is in playlist move on to next item in playlist

***Error received in log/console****

```
[http @ 0x561c223b2760] Stream ends prematurely at 11256986, should be 18446744073709551615
http://91.221.151.155/: Input/output error
```

**Comment by azlux** [comment]
It the southcast is behind a reverse proxy, you can have some timeout.
Do you have de date-time at start and when it's stop ?

**Comment by Glowsome** [comment]
The stream is activated by users at random, but the timeout looks as if it occurs during night-time - i do not have timestamping of console output enabled ( how can i ?)

**Comment by azlux** [comment]
It's maybe a codec error (on the southcast error).
That is most likely due to source timeout. If you use highly efficient codecs, then silence encodes to "nothing" and the southcast server will not get any data and disconnect the source.

**Comment by Glowsome** [comment]
As far as i know now this is the only configured stream which is having this issue, so its not a 'BIG' thing, but was curious if the bot could be made capable of handling such 'crappy' streams :)

**Comment by azlux** [comment]
I don't think I will have time to manage that.

**Comment by azlux** [comment]
Have you test it with the last version ? I've add an auto restart function.
