### ISSUE TITLE
Changing the playlist when downloading messes things up

### ISSUE THREAD

**Issue by TerryGeng** [azlux/botamusique#90]
Currently, the bot will download the next song on the list in advance by async_download. However, since it is in another thread, if people delete items from the playlist, the index of the playlist will change and when the download is completed, download function won't be able to update the item in the playlist.

As you can see, the last part of the download function is to update the item on the playlist, by the index it took down before the download starts.
https://github.com/azlux/botamusique/blob/acf43eed24076d132b66e1246ccf391a589f8192/mumbleBot.py#L401-L403

https://github.com/azlux/botamusique/blob/acf43eed24076d132b66e1246ccf391a589f8192/mumbleBot.py#L465-L472

I have two possible solutions in my mind. 

- The first one is to just kill all downloading thread when removing items from the playlist,

- The second one is, after we build the database, I separate the metadata from the playlist and put the metadata into the database. Downloading thread will update the metadata in the database maybe by some UUID or something.

What do you guys think?

**Comment by azlux** [comment]
Is this commit was for that ? https://github.com/azlux/botamusique/commit/28320ddfe52009ae650d47615337fc0eb5951e94
I see you avoid deleting items on playlist if the download is in progress.

**Comment by TerryGeng** [comment]
Yes. But this only fixed a small part of the problem. I can still manually removes item from the playlist while downloading.

**Comment by TerryGeng** [comment]
Tested. Fixed some small bugs in c32c6c5d9beb91050cb8bc947ebb4d42a751f0da.

We are good now.
