### ISSUE TITLE
Ducking is eating up memory

### ISSUE THREAD

**Issue by ajmandourah** [azlux/botamusique#95]
When setting Ducking on in the config file it seems like the bot is eating up the memory even while the bot is not playing anything. this behavior become worse the more people is connected to the server. VPS and servers with 512mb ram will suffer and the bot eventually get disconnected. Disabling ducking will fix the issue. probably some problem with threading but I am no expert.

Happy to help if needed.

**Comment by TerryGeng** [comment]
Oh no...

This is actually a bug of https://github.com/azlux/pymumble/issues/44.
I tried to make a workaround in the bot, but apparently it didn't work.

https://github.com/azlux/botamusique/blob/c32c6c5d9beb91050cb8bc947ebb4d42a751f0da/mumbleBot.py#L719-L724

Can @azlux explain a little bit?

**Comment by TerryGeng** [comment]
Okay... Although I clear the queue after the ducking is released, it also means if ducking is always not triggered (people's volume is low) or people are always talking so there's no chance for the bot to clear the queue (the bot will release ducking only if people are talking below the threshold for 1s). If you start the bot with argument '-v', but you hardly see anything like
`[Mar 10 20:19:31 DEBUG MainThread] bot: pymumble soundqueue cleared.`
Then this could be the problem.

I just posted a hotfix, which should fix this problem. I hope it works for you.

But this is just a workaround. Maybe @azlux will find a way out in the pymumble repo.

**Comment by TerryGeng** [comment]
@ajmandourah Hi, @azlux has just posted a fix on pymumble. I think you can have a try again. If this problem persists, we will see what we can do.

**Comment by ajmandourah** [comment]
Will give it a try today and see if it will be triggers again

**Comment by TerryGeng** [comment]
Yes. It is in the master branch.

Currently, we are developing and testing a bunch of new features in the develop branch, and are planning to merge them to the master branch in a few days. That would be next stable release.

**Comment by TerryGeng** [comment]
Fixed in https://github.com/azlux/pymumble/pull/55.
Updated in 8013789.
