### ISSUE TITLE
ModuleNotFoundError: No module named 'google'

### ISSUE THREAD

**Issue by LDelOff** [azlux/botamusique#98]
**root@orangepi3:~/botamusique# python3 mumbleBot.py**
Traceback (most recent call last):
  File "mumbleBot.py", line 16, in <module>
    import pymumble.pymumble_py3 as pymumble
  File "/root/botamusique/pymumble/pymumble_py3/__init__.py", line 3, in <module>
    from .mumble import Mumble
  File "/root/botamusique/pymumble/pymumble_py3/mumble.py", line 12, in <module>
    from . import users
  File "/root/botamusique/pymumble/pymumble_py3/users.py", line 7, in <module>
    from . import mumble_pb2
  File "/root/botamusique/pymumble/pymumble_py3/mumble_pb2.py", line 6, in <module>
    from google.protobuf import descriptor as _descriptor
ModuleNotFoundError: No module named 'google'
**root@orangepi3:~/botamusique# pip3 install --upgrade --force-reinstall google**
Collecting google
  Using cached https://files.pythonhosted.org/packages/81/51/36af1d18648574d13d8f43e863e95a97fe6f43d54a13fbcf272c638c10e9/google-2.0.3-py2.py3-none-any.whl
Collecting beautifulsoup4 (from google)
  Using cached https://files.pythonhosted.org/packages/cb/a1/c698cf319e9cfed6b17376281bd0efc6bfc8465698f54170ef60a485ab5d/beautifulsoup4-4.8.2-py3-none-any.whl
Collecting soupsieve>=1.2 (from beautifulsoup4->google)
  Using cached https://files.pythonhosted.org/packages/05/cf/ea245e52f55823f19992447b008bcbb7f78efc5960d77f6c34b5b45b36dd/soupsieve-2.0-py2.py3-none-any.whl
Installing collected packages: soupsieve, beautifulsoup4, google
  Found existing installation: soupsieve 2.0
    Uninstalling soupsieve-2.0:
      Successfully uninstalled soupsieve-2.0
  Found existing installation: beautifulsoup4 4.8.2
    Uninstalling beautifulsoup4-4.8.2:
      Successfully uninstalled beautifulsoup4-4.8.2
  Found existing installation: google 2.0.3
    Uninstalling google-2.0.3:
      Successfully uninstalled google-2.0.3
Successfully installed beautifulsoup4-4.8.2 google-2.0.3 soupsieve-2.0
**root@orangepi3:~/botamusique# python3 mumbleBot.py**
Traceback (most recent call last):
  File "mumbleBot.py", line 16, in <module>
    import pymumble.pymumble_py3 as pymumble
  File "/root/botamusique/pymumble/pymumble_py3/__init__.py", line 3, in <module>
    from .mumble import Mumble
  File "/root/botamusique/pymumble/pymumble_py3/mumble.py", line 12, in <module>
    from . import users
  File "/root/botamusique/pymumble/pymumble_py3/users.py", line 7, in <module>
    from . import mumble_pb2
  File "/root/botamusique/pymumble/pymumble_py3/mumble_pb2.py", line 6, in <module>
    from google.protobuf import descriptor as _descriptor
ModuleNotFoundError: No module named 'google'
root@orangepi3:~/botamusique#

**Comment by azlux** [comment]
Did you install the `requirements.txt` ?
protobuf  is missing from your python modules list.

**Comment by LDelOff** [comment]
Yes, I install the requirements.txt.
I resolve:
https://stackoverflow.com/questions/52038874/modulenotfounderror-no-module-named-google
**pip3 install google-cloud
pip3 install google-cloud-bigquery**

**Comment by azlux** [comment]
what ? We don't use this module.
Which python version do you use ?

**Comment by LDelOff** [comment]
I don't now(
![image](https://user-images.githubusercontent.com/51275636/76344761-2c7adf80-6313-11ea-93f3-30bcd39febac.png)
I use **python3 ...**
**pip3 install**

**Comment by azlux** [comment]
I ask for the output of `python3 -V`

**Comment by LDelOff** [comment]
Python 3.8.2

**Comment by LDelOff** [comment]
Maybe it's my fault, I recently updated the system
apt upgrade
I'll try reinstalling Python

**Comment by azlux** [comment]
you should use `venv` to be sure you don't have conflict between your modules as explained into the doc.

**Comment by LDelOff** [comment]
I removed all versions of Python, installed version 3.8.2. 
Everything works correctly.
Thank you:)
